- .gitignore
- shotover-proxy/src/protocols/cassandra_protocol2.rs
- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/tests/codec/cassandra.rs
* Moving the test_data directory outside of target reduces our cache usage by 1GB which is a sizeable portion of the 5GB GA cache limit. AFAIK this limit can not yet be increased with paid plans.
* Deleted a bunch of println's that add noise to the logs
> various fixes to improve CI

- .github/workflows/bench_run.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- rust-toolchain.toml
- shotover-proxy/src/transforms/load_balance.rs
- shotover-proxy/src/transforms/protect/mod.rs
- shotover-proxy/tests/codec/cassandra.rs
- shotover-proxy/tests/codec/util/packet_capture.rs
- shotover-proxy/tests/codec/util/packet_parse.rs
- shotover-proxy/tests/helpers/mod.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
closes https://github.com/shotover/shotover-proxy/issues/323
My conclusion here is that the AWS + sccache solution would be a bit better, but using the GA cache is easier to setup and manage.
So if we find the GA cache limiting we can investigate going back to AWS + sccache.
The other changes are:
* failing on clippy warnings
+ we can do this because we are now specifying a rust version in the rust-toolchain.toml and we already have our Cargo.lock checked in so there is no way for our build to break due to warnings being added.
- The expectation here is that we will update the rust-toolchain.toml every time a new rust version comes out to take advantage of the speed ups and UX improvements not to mention new features.
* changes the toolchain installer to be a little more efficient and …
> rewrite CI, fixing caching and failing on warnings

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/src/config/topology.rs
- shotover-proxy/src/sources/cassandra_source.rs
- shotover-proxy/src/sources/redis_source.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/src/transforms/coalesce.rs
- shotover-proxy/src/transforms/debug_printer.rs
- shotover-proxy/src/transforms/distributed/consistent_scatter.rs
- shotover-proxy/src/transforms/filter.rs
- shotover-proxy/src/transforms/internal_debug_transforms.rs
- shotover-proxy/src/transforms/kafka_sink.rs
- shotover-proxy/src/transforms/load_balance.rs
- shotover-proxy/src/transforms/loopback.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/noop.rs
- shotover-proxy/src/transforms/null.rs
- shotover-proxy/src/transforms/parallel_map.rs
- shotover-proxy/src/transforms/protect/mod.rs
- shotover-proxy/src/transforms/query_counter.rs
- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/src/transforms/redis/cluster_ports_rewrite.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
- shotover-proxy/src/transforms/redis/timestamp_tagging.rs
- shotover-proxy/src/transforms/sampler.rs
- shotover-proxy/src/transforms/tee.rs
Use [`IntoStaticStr`](https://docs.rs/strum/0.22.0/strum/derive.IntoStaticStr.html) to get the name of transforms instead of a method on the `Transform` trait. 
In some places we need access to the transform name from within the transform itself so I have added `get_name` methods directly to the struct.
> Fix transform names

- shotover-proxy/examples/null-redis/topology.yaml
- shotover-proxy/examples/redis-cluster/topology.yaml
- shotover-proxy/src/server.rs
- shotover-proxy/src/transforms/chain.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/query_counter.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/src/transforms/tee.rs
- shotover-proxy/tests/runner/observability_int_tests.rs
Register all metrics on startup so they can be retrieved from the metrics endpoint without any needed to be actually be recorded yet.
> Register metrics on startup

- Cargo.lock
- shotover-proxy/Cargo.toml
A new release is needed with functionality from #275 for INS-15988. I am bumping the minor version, roughly following SemVer, although we're being flexible with pre-1.0 in regards to the definition of a 'breaking change'.
> Bump version to v0.1.0

- .github/workflows/bench_run.yml
- shotover-proxy/benches/redis_benches.rs
- shotover-proxy/tests/scripts/bench_against_master.sh
* change in bench_run.yml fixes the name used when github actions reports failures
* redis_benches.rs change bumps up the threshold at which failures are detected to 200%
+ Basically I dont believe these tests can be made to give useful results for benchmarking so im giving them absurdly high values so we dont have to worry about them for now. I'm not deleting them yet, as they could be useful as measures of throughput in the future.
* bench_against_master.sh changes are to report the names of the benches that regressed and improved.
+ If this ever breaks I'm rewriting this whole thing as a rust tool. I hate bash.
> Bench CI improvements

- test-helpers/src/docker_compose.rs
I changed them to debug! to help reduce the noise levels when running `cargo test`/`cargo bench`.
The info! logs in shotover itself could probably do with a cleanup but im not sure which ones are important or not.
The problem of shotovers logs could probably do with some more thought both from the perspective of shotover users trying to understand shotovers internal state and from developers trying to not drown in logs.
The info! logs in test infrastructure are of much more dubious value.
Unless your actively working on a test then you dont want to see test infrastructure logging at all.
The docker-compose log is outright removed because we already log the output of that command when the command fails which is the only time we would want to see it anyway. This is the noisiest log taking …
> Test infrastructure uses debug! instead of info!

- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/protocols/cassandra_protocol2.rs
- shotover-proxy/src/protocols/redis_codec.rs
- shotover-proxy/src/transforms/kafka_sink.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
From what I can see it is only created in `redis/sink_cluster.rs` and I cant see any reason we would want to bypass something here.
Would appreciate a thorough review to make sure i'm not missing anything here.
> Remove MessageDetails::Bypass

- .github/workflows/test.yml
- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/build/build_release.sh
- shotover-proxy/src/transforms/redis/cache.rs
The section named "Build & Test" in the GA tagged-release workflow didnt actually do any testing!
This change fixes that, but also moves our test workflows to primarily use 18.04 as that is where our binary is built but also includes an extra 20.04 workflow so that we dont find ourselves stuck when 18.04 is EoL.
In order to fix building on ubuntu 18.04 we had to change rdkafka to build with mklove instead of cmake.
Not sure why we were using cmake in the first place as mklove seems to be shipped with rdkafka.
> Fix testing on ubuntu 18.04

- netlify.toml
fixes the issue where someone pushes a cleanup commit to a docs PR that doesnt change the output and then the netlify preview can no longer be seen due to matching the previous deploy.
e.g. https://app.netlify.com/sites/elegant-joliot-4fcb9b/deploys/6184d3c90542d1000734a86f
I have never seen this problem before so I think it is be caused by mdbook being deterministic while mkdocs is not deterministic.
You can go back to old PRs before we switched to mdbook and see that this never occurred.
> force netlify to always deploy

- shotover-proxy/src/protocols/cassandra_protocol2.rs
The removed test was removed because its now duplicated with the functionality of the improved tests.
> cassandra unittests assert decoded value

- shotover-proxy/tests/helpers/mod.rs
- shotover-proxy/tests/runner/runner_int_tests.rs
- test-helpers/src/docker_compose.rs
This will give a warning on code like this that drops the compose in a non-obvious way:
```rust
let _compose = DockerCompose::new("examples/redis-passthrough/docker-compose.yml");
_compose.wait_for("Ready to accept connections");
```
Example warning:
> Add must_use attribute to test helpers

- shotover-proxy/benches/chain_benches.rs
- shotover-proxy/src/server.rs
- shotover-proxy/src/sources/mpsc_source.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/parallel_map.rs
- shotover-proxy/src/transforms/redis/cache.rs
We wouldn't want to create a `Wrapper` outside of a chain unless testing so I have restricted the use of `new` to tests only. The other 2 `new_xxx` methods ensure that `Wrapper` should always be given a chain name.
> Always pass chain name into Wrapper

- shotover-proxy/tests/cassandra_int_tests/basic_driver_tests.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/helpers/mod.rs
Changes cassandra tests to use the wait_for_socket_to_open implementation that redis uses instead of the current cassandra level protocol level wait/retry system.
wait_for_socket_to_open has a few advantages:
* its simpler
* its reusable across different protocols
* it only fails if the port is closed. This is important because if shotover can be in a state where the port is open but the connection fails then the test should fail!
> Reuse wait for socket implementation across cassandra and redis

- .gitignore
- docs/book.toml
- docs/mdbook.sh
- docs/serve.sh
- docs/src/index.md
- docs/src/transforms.md
- docs/src/user-guide/concepts.md
- docs/src/user-guide/configuration.md
- docs/src/user-guide/introduction.md
- netlify.toml
The setup script is adjusted to run for both netlify and local usage (previously just local usage)
I opted to delete most of the dead-links but im happy to comment them out if we want to keep them around until we bring back the pages they link to.
> Fix broken doc links and enforce via mdbook-linkcheck plugin

- shotover-proxy/src/protocols/cassandra_protocol2.rs
- shotover-proxy/src/transforms/distributed/consistent_scatter.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/protect/mod.rs
The aftermath of running `cargo udeps` on our codebase.
If properly implementing `timeout` and `count` into `ConsistentScatter` is something we want to do I can open a ticket for it.
> Run cargo udeps

- docs/src/contributing.md
Build was broken because CI ran for https://github.com/shotover/shotover-proxy/pull/373 before https://github.com/shotover/shotover-proxy/pull/331 was merged
> Fix docs build

- test-helpers/src/docker_compose.rs
The actual log contents was accidentally removed in https://github.com/shotover/shotover-proxy/pull/331
> Fix docker_compose wait_for panic message

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/protocols/cassandra_protocol2.rs
- shotover-proxy/src/transforms/distributed/consistent_scatter.rs
- shotover-proxy/src/transforms/query_counter.rs
- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/src/transforms/redis/mod.rs
- shotover-proxy/tests/cassandra_int_tests/basic_driver_tests.rs
- shotover-proxy/tests/codec/util/packet_parse.rs
- shotover-proxy/tests/helpers/mod.rs
You can see the warnings yourself by setting `channel = "beta"` in rust-toolchain.toml
I'm not sure why we have such an extensive packet parser just for one single test.
The fields on DnsPacket are giving unused warnings, the test doesnt make use of the dns parser so DnsPacket should just be entirely removed.
Although maybe we do want such powerful parsing in the future and the whole parser should be moved into a separate crate?
I removed the comment in `shotover-proxy/tests/helpers/mod.rs` I was expecting shotover-proxy/tests/helpers/mod.rs to make this code simpler but it didnt end up helping due to a mismatch in the values used by the PROFILE env var and the values accepted by `--profile`.
> Fix warnings that trigger in fridays upcoming rust 1.57 release

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/protocols/cassandra_protocol2.rs
- shotover-proxy/src/protocols/mod.rs
- shotover-proxy/src/transforms/protect/mod.rs
- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/src/transforms/util/mod.rs
- shotover-proxy/src/transforms/util/unordered_cluster_connection_pool.rs
Doesnt yet compile.
Still a lot of upstreaming required.
The current upstream parser API requires an extra allocation.
I think the best path forward is to just accept that extra allocation for now and then we can properly investigate a solution that works for all parties once we are on upstream. This is very similar to the approach we took for redis-proto.
TODO before this can be merged:
Edit:
Now ready for review!
> Use upstream cassandra-protocol

- shotover-proxy/src/config/topology.rs
- shotover-proxy/src/runner.rs
- shotover-proxy/src/server.rs
- shotover-proxy/src/sources/cassandra_source.rs
- shotover-proxy/src/sources/mod.rs
- shotover-proxy/src/sources/mpsc_source.rs
- shotover-proxy/src/sources/redis_source.rs
This PR has two changes:
* Join on the sources task when shotover shutsdown - first commit
+ this is needed to prevent a race condition where shotover ends before the source's task shutsdown. This can be observed by the `redis source shutting down` sometimes not being logged.
* Remove shutdown_complete broadcast channel - second commit
+ now that we are waiting on sources join handle it seems that this is redundant.
+ Having said that I'm a little concerned as to if there is some significance behind mini-redis taking this approach. Maybe shotover has diverged enough from mini-redis that a different approach is warranted?
> Join on source task

- shotover-proxy/src/transforms/redis/sink_single.rs
Every other sink already handles this case as a noop, so we should do the same for RedisSinkSingle.
Note that the other sinks dont explicitly handle the case, its just that the async abstractions they use dont have this problem.
Although this case is currently impossible to hit in shotover usage, handling it is beneficial because:
* This hang was very confusing to debug and by handling it we prevent future shotover developers from hitting this large time sink.
* I would like to make use of this property in https://github.com/shotover/shotover-proxy/pull/389
> Fix hang in RedisSinkSingle when wrapper.messages.is_empty()

- LICENSE
- shotover-proxy/examples/cassandra-passthrough/docker-compose.yml
- shotover-proxy/examples/cassandra-passthrough/docker-entrypoint.sh
- test-helpers/src/docker_compose.rs
This change allows us to use docker compose volume mounting for files the example directory. 
E.g. We can just mount the PWD in `docker-compose.yml`
```YAML
volumes:
- ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
```
I've also included the change to the `cassandra-passthrough` example that I needed this change for. User defined functions need to be enabled in Cassandra to test them but they can't be set from the docker-compose so we need to modify the `docker-entrypoint.sh` to do this.
The `docker-entrypoint.sh` is mostly the same as the [default](https://github.com/docker-library/cassandra/blob/master/3.11/docker-entrypoint.sh) but I added `enable_user_defined_functions` and `enable_scripted_user_defined_functions` to the `for yaml in \` loop.
I considered opening a PR to …
> Allow Cassandra passthrough to be configured in docker-compose.yml 

- shotover-proxy/src/transforms/chain.rs
- shotover-proxy/src/transforms/distributed/consistent_scatter.rs
- shotover-proxy/src/transforms/load_balance.rs
- shotover-proxy/src/transforms/tee.rs
- We never use the client details in `BufferedChain` so I have removed it
- Make an inner method private so it's clear you should use the other 2 only
> Clean up BufferedChain API

- shotover-proxy/src/server.rs
- shotover-proxy/src/sources/cassandra_source.rs
- shotover-proxy/src/sources/mpsc_source.rs
- shotover-proxy/src/sources/redis_source.rs
- shotover-proxy/src/transforms/chain.rs
- shotover-proxy/src/transforms/coalesce.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
This is a step towards https://github.com/shotover/shotover-proxy/issues/385
This PR adds:
* A flush flag in Wrapper which indicates to transforms that they should immediately flush all buffered messages.
+ Support for this flag is added to the Coalesce transform
* coalesce shutdown logic that flushes all buffered messages.
*  Shutdown logic for sources and buffered chains that flushes all messages before dropping all their objects.
I originally planned to have a separate `Transform::shutdown` method that handles this but I had to ditch this approach because it required each transform to reimplement a lot of logic from their `Transform::transform` implementation. If for example the QueryTypeFilter transform was just simply passing on messages without filtering them that would introduce …
> Add Wrapper::flush flag

- docs/src/transforms.md
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/transforms/debug/returner.rs
- shotover-proxy/src/transforms/filter.rs
- shotover-proxy/tests/test-topologies/query_type_filter/simple.yaml
- shotover-proxy/tests/transforms/mod.rs
- shotover-proxy/tests/transforms/query_type_filter.rs
Fix QueryTypeFilter and DebugReturner so that they always return the same number of messages that they receive.
The only reason this hasnt been a problem yet is because in production we only use QueryTypeFilter in an ignore tee branch where breaking this invariant has no consequences.
DebugReturner's Response::Message case could also cause this problem but thats only used internally for unit tests and this PR is large enough already so it should be investigated separately.
> Fix QueryTypeFilter on main chain

- docs/src/transforms.md
- docs/src/user-guide/configuration.md
- shotover-proxy/examples/redis-cluster-dr/topology.yaml
- shotover-proxy/src/config/topology.rs
- shotover-proxy/src/sources/mpsc_source.rs
- shotover-proxy/src/transforms/coalesce.rs
Using enums in configuration to make it impossible to represent invalid states is really powerful.
I think the `tls` field in RedisSink is a good example of where this works really well.
However in the case of the `max_behaviour` field in Coalesce I think the benefit tips the other way and we are better off with separate fields.
Conceptually we have two separate optional values that we want to configure: flush by timeout and flush by message count.
But we are currently combining both into one enum to avoid the invalid state where none of these values are provided.
This gives us a really awkward 3rd variant: CountOrWait that is both difficult to document and difficult to use.
The current CountOrWait implementation could be improved by replacing it with a `CountOrWait { count: usize, wait: …
> Replace CoalesceBehaviour with individual fields in Coalesce.

- docs/src/transforms.md
- shotover-proxy/examples/cassandra-redis-cache/docker-compose.yml
- shotover-proxy/examples/cassandra-redis-cache/docker-entrypoint.sh
- shotover-proxy/examples/cassandra-redis-cache/topology.yaml
- shotover-proxy/tests/cassandra_int_tests/basic_driver_tests.rs
The test currently demonstrates that the RedisCache transform can at least pass on messages to cassandra without issues.
Still need to test that the cache actually caches something.
We can do that by manually modifying the cache and checking we get the modified version back.
But that should go in a follow up PR.
> Implement test_cassandra_redis_cache integration test

- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/transforms/distributed/consistent_scatter.rs
- shotover-proxy/src/transforms/filter.rs
- shotover-proxy/src/transforms/redis/cache.rs
Refactor towards getting RedisCache working.
Simplifies and unifies the implementation of various transforms
> Get the query type for a message by a common get_query_type method

- shotover-proxy/tests/cassandra_int_tests/mod.rs
Include the failed query and ignore the second element in Error.
The docs specifically say that the second element of Error is only relevant for internal use https://docs.rs/cassandra-cpp/0.17.0/cassandra_cpp/struct.Error.html
Error now looks like:
```
thread 'cassandra_int_tests::basic_driver_tests::test_cassandra_redis_cache' panicked at 'The CSQL query: BEGIN BATCH
INSERT INTO test_cache_keyspace.test_table (id, x, name) VALUES (1, 2, 'foo');
INSERT INTO test_cache_keyspace.test_table (id, x, name) VALUES (2, 3, 'bar');
INSERT INTO test_cache_keyspace.test_table (id, x, names) VALUES (3, 4, 'baz');
APPLY BATCH;
Failed with: Cassandra detailed error SERVER_INVALID_QUERY: Undefined column name names', shotover-proxy/tests/cassandra_int_tests/mod.rs:47:31
stack backtrace:
0: …
```
> Improve cassandra int test execute_query error

- shotover-proxy/examples/cassandra-redis-cache/docker-compose.yml
- shotover-proxy/examples/cassandra-redis-cache/topology.yaml
- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/tests/cassandra_int_tests/basic_driver_tests.rs
* Various fixes to the integration test
* Add a cache::test function for testing caching functionality
+ It demonstrates the current working functionality of RedisCache - which is to say it demonstrates that the caching does nothing and no key/values are inserted into redis.
* Various improvements to RedisCache error reporting
+ The changes make it too verbose but that is better than silently ignoring all errors like it used to do
+ We can change the expected failed to cache cases to occur silently once everything is working.
I would like to merge this PR as a base to build upon, and then add the fixes to RedisCache in a follow up PR.
> Improve cassandra redis cache int test + tracing

- shotover-proxy/src/protocols/cassandra_codec.rs
- shotover-proxy/src/transforms/protect/mod.rs
Remove needless lifetimes and replace needless uses of `.borrow()` with `&`
> Cleanup borrows

- shotover-proxy/examples/cassandra-redis-cache/topology.yaml
- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/tests/cassandra_int_tests/basic_driver_tests.rs
The integration test now actually takes the cache path.
This revealed the issue that we actually attempt to directly return the redis messages as cassandra messages, this naturally causes the decoder to error out.
In order to get the integration test passing I made a dummy redis-cache to cassandra message conversion that just ignores the redis message and generates an empty cassandra message.
This logic will be completely replaced later on but it will be really useful to have a test checked in that actually takes the cache path.
There is a separate testcase for queries against the PK and against some other field because they take different codepaths and the 2nd case currently sends an invalid query to redis, as can be seen by the output of `info!("Received reply from redis cache {:?}", …
> Redis cache doesnt blow up when the cache path is taken

- shotover-proxy/src/transforms/redis/timestamp_tagging.rs
Simplifies the implementation, improves performance and improves logging
Why am I fiddling with RedisTimestampTagger?
Its a good example of a transform performing message details manipulation so I wanted to properly understand it.
In the process of doing so I noticed a bunch of minor improvements.
Remember to ignore whitespace in diff.
> RedisTimestampTagger cleanup

- shotover-proxy/examples/cassandra-redis-cache/topology.yaml
- shotover-proxy/tests/cassandra_int_tests/basic_driver_tests.rs
Adds a second RedisCache test case that actually manages to store values in redis.
This sets up for the next step which will be changing the stored redis values to a format that can be deserialized back into cassandra values.
> redis cache new int test case

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/protocols/cassandra_codec.rs
Pulling some changes out of #404 
- Support all native and collection Cassandra types in Value
- Add todos for conversions not yet implemented.
> Value support for Cassandra types

- shotover-proxy/src/transforms/redis/cache.rs
Something I noticed while investigating #448. We can early return from this loop the first time we notice a `QueryType::Write` and not scan through the rest of the messages, and I added a comment to make the logic a little clearer.
> Optimise Redis cache loop

- shotover-proxy/src/protocols/mod.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
A single import was missed from https://github.com/shotover/shotover-proxy/pull/455
Also changed the reexport to take from the types module instead of the prelude, not super important but importing a specific type from a prelude seems weird to me.
> Rename Frame -> RedisFrame

- shotover-proxy/benches/chain_benches.rs
returning a null message causes this logic to be skipped:
https://github.com/shotover/shotover-proxy/blob/1ceb040ce09736ba1cd8a274316c95982ebcdcef/shotover-proxy/src/transforms/redis/timestamp_tagging.rs#L98
> redis_timestamp_tagger bench uses better test data to avoid skipping unwrap_response

- shotover-proxy/src/transforms/filter.rs
Cleanup inspired by the message details rewrite.
Main purpose is to replace this logic:
```rust
let any = result.iter().find(|m| {
if let MessageDetails::Response(qr) = &m.details {
if let Some(qm) = &qr.matching_query {
return qm.query_type == QueryType::Read;
}
}
false
});
assert_eq!(any, None);
```
Which is very confusing to read and not a very robust test.
> Improve QueryTypeFilter unit test

- .github/workflows/create_comment.yml
I thought the benchmark comments were suspiciously quiet so I checked https://github.com/shotover/shotover-proxy/actions/workflows/create_comment.yml and found that its been broken since 3 months ago.
I tracked the problem down to https://github.com/shotover/shotover-proxy/pull/340 - the create_comment workflow wasnt adjusted to the new name of the benchmarks workflow.
This PR fixes that issue.
> Fix CI benchmark alert comments

- shotover-proxy/src/transforms/tee.rs
It is an invariant of transforms that they return the same number of messages as they received.
The previous implementation failed to do that.
> Tee FailOnMismatch returns the correct number of messages

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/benches/chain_benches.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/protocols/redis_codec.rs
- shotover-proxy/src/transforms/debug/returner.rs
- shotover-proxy/src/transforms/redis/cluster_ports_rewrite.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
The only change in 4.0.0 was to replace String with StrMut and Vec<u8> with BytesMut https://github.com/aembke/redis-protocol.rs/pull/17
I think the `Frame` fields should be using `Bytes`/`Str` instead of `BytesMut`/`StrMut`.
I raised an issue https://github.com/aembke/redis-protocol.rs/issues/18 for this.
In the mean time we should upgrade to ensure that when we reason about performance implications we are working from the current state of the library.
> Update to redis-protocol 4.0

- shotover-proxy/src/server.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/src/transforms/chain.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
- shotover-proxy/src/transforms/tee.rs
- Using metrics handles in transforms is pretty simple. 
- Using handles instead of the macros in `TransformChain` and `Wrapper` will require more complex changes. Will see if it's worth re-architecting things to do this.
> Use metrics handles in transforms

- shotover-proxy/benches/chain_benches.rs
- shotover-proxy/src/transforms/chain.rs
- shotover-proxy/src/transforms/distributed/consistent_scatter.rs
- shotover-proxy/src/transforms/parallel_map.rs
- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/src/transforms/sampler.rs
As mentioned on https://github.com/shotover/shotover-proxy/pull/469: 
The `new_no_shared_state` function on `TransformChain` does nothing different to the `new` function so this PR removes it.
> Remove new no state method from TransformChain

- shotover-proxy/tests/scripts/bench_against_master.sh
grep will output a `--` between results which markdown interprets to mean the above lines are headings.
We can stop grep from outputting those by doing: `grep --no-group-separator`
However we are better off just adding ``` around the log output because it also keeps the monospaced spacing in tact.
So that is what this PR does.
> Fix formatting on bench comments

- shotover-proxy/benches/chain_benches.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/protocols/cassandra_codec.rs
- shotover-proxy/src/protocols/mod.rs
- shotover-proxy/src/protocols/redis_codec.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/src/transforms/coalesce.rs
- shotover-proxy/src/transforms/debug/returner.rs
- shotover-proxy/src/transforms/distributed/consistent_scatter.rs
- shotover-proxy/src/transforms/filter.rs
- shotover-proxy/src/transforms/kafka_sink.rs
- shotover-proxy/src/transforms/loopback.rs
- shotover-proxy/src/transforms/null.rs
- shotover-proxy/src/transforms/protect/mod.rs
- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/src/transforms/redis/cluster_ports_rewrite.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
- shotover-proxy/src/transforms/tee.rs
- shotover-proxy/src/transforms/util/unordered_cluster_connection_pool.rs
Frame and RawFrame are semantically a bit different but they end up getting used in pretty much the same places so may as well arrive at Frame by converting RawFrame into it.
> Rename RawFrame -> Frame

- shotover-proxy/benches/chain_benches.rs
Both my local machine and CI usually have a variance of 3% but I have also seen one instance of CI going up to 6%
This sets chain_bench.rs to a noise_threshold of 0.1 (10%) compared to the default of 0.01 (1%)
redis_benches.rs is absurdly noisy so that was already set to 2.0 (200%)
Correctly setting the noise_threshold will prevent the erroneous benchmark warning comments.
I'm not sure if benchmarks are supposed to be more consistent then this, if we are supposed to be able to meet that default 1% variance then I suspect its caused by us using async.
If we figure out a way to reduce the threshold in the future then that would be great, for now being able to detect regressions or improvements of >10% will give enough value.
> Add noise threshold for chain_benches.rs

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/tests/scripts/bench_against_master.sh
closes https://github.com/shotover/shotover-proxy/issues/270
~~Waiting on https://github.com/bheisler/criterion.rs/pull/532 to be merged~~
The problem was caused because criterion expects a baseline to exist for every benchmark.
This PR solves the problem by making use of a new criterion feature (https://github.com/bheisler/criterion.rs/pull/532) that silently ignores missing baselines.
> Fix CI failures when a new benchmark is added

- .github/workflows/test.yml
- shotover-proxy/src/protocols/redis_codec.rs
This change is functionally equivalent but:
* is simpler
* allocates less
* is a step towards the message details rewrite storing the raw redis Bytes in the message to skip encoding in same cases.
> Cleanup RedisCodec

- shotover-proxy/src/transforms/protect/mod.rs
* Panics instead of returning Err to better report failures
* ~~create_aws_key is now create_aws_key_and_alias~~ I realized there are some default keys provided by moto that we can make use of rather than creating our own: https://github.com/spulec/moto/blob/0a1bb6bae165b38cdec5e299a7f859f2cb27de93/moto/kms/utils.py#L41
+ By using a stable alias of a key we will be able to write integration tests for Protect that specify the stable key alias in their topology.yaml
> Initial protect test cleanup

- shotover-proxy/src/transforms/cassandra/connection.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/src/transforms/util/cluster_connection_pool.rs
- shotover-proxy/src/transforms/util/mod.rs
- Moved `Request` struct to be private to `CassandraConnection`. This means that the `Request` used for `ConnectionPool` doesn't need to have an `Option<i16>` field for the message id.
- added a `send` method. Transforms can just give the connection pool their message and return channel instead of having to interact with the implementation of `CassandraConnection`.
- Renamed `messages` in `Request` to `message` because it only holds one message.
- Changed `Response` from a tuple to a struct. This was used lots and it was confusing. Sometimes it was used without the `Response` type and instead another tuple was declared.
> CassandraConnection cleanup

- shotover-proxy/benches/chain_benches.rs
- shotover-proxy/src/codec/cassandra.rs
- shotover-proxy/src/codec/mod.rs
- shotover-proxy/src/codec/redis.rs
- shotover-proxy/src/frame/mod.rs
- shotover-proxy/src/lib.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/server.rs
- shotover-proxy/src/sources/cassandra_source.rs
- shotover-proxy/src/sources/redis_source.rs
- shotover-proxy/src/transforms/cassandra/connection.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/src/transforms/coalesce.rs
- shotover-proxy/src/transforms/debug/returner.rs
- shotover-proxy/src/transforms/distributed/consistent_scatter.rs
- shotover-proxy/src/transforms/filter.rs
- shotover-proxy/src/transforms/kafka_sink.rs
- shotover-proxy/src/transforms/null.rs
- shotover-proxy/src/transforms/protect/mod.rs
- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/src/transforms/redis/cluster_ports_rewrite.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
- shotover-proxy/src/transforms/tee.rs
- shotover-proxy/src/transforms/util/cluster_connection_pool.rs
- shotover-proxy/tests/codec/cassandra.rs
Moves the following:
* protocols::Frame -> frame::Frame
* protocols::RedisFrame -> frame::RedisFrame
* protocols::CassandraFrame -> frame::CassandraFrame
* protocols::redis_codec -> codec::redis
* protocols::cassandra_codec -> codec::cassandra
This will allow us to make a frame::cassandra::CassandraFrame to hold the new CassandraFrame struct introduced by the message details rewrite.
I havent put too much thought into this but it seemed like an obvious improvement, let me know if you have any better ideas.
> Split protocols module into frame + codec modules

- shotover-proxy/src/codec/cassandra.rs
- shotover-proxy/src/transforms/debug/returner.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
All of these changes result in identical functionality as Message::from_frame is currently just:
```rust
pub fn from_frame(raw_frame: Frame) -> Self {
Self::new(MessageDetails::Unknown, false, raw_frame)
}
```
> Replace instances of Message::new with Message::from_frame

- shotover-proxy/src/transforms/coalesce.rs
I'm not sure how it ended up like that, but returning a dummy message like that violates the transform invariant:
```rust
/// * _Message count_ - message_wrapper.messages will contain 0 or more messages.
/// Your transform should return the same number of responses as messages received in message_wrapper.messages. Transforms that
/// don't do this explicitly for each call, should return the same number of responses as messages it receives over the lifetime
/// of the transform chain.
```
Returning a dummy message would result in more messages being returned than are coming in.
> Remove incorrect coalesce dummy message

- .github/workflows/test.yml
- shotover-proxy/Cargo.toml
- shotover-proxy/examples/cassandra-protect-aws/docker-compose.yml
- shotover-proxy/examples/cassandra-protect-aws/docker-entrypoint.sh
- shotover-proxy/examples/cassandra-protect-aws/topology.yaml
- shotover-proxy/examples/cassandra-protect-local/docker-compose.yml
- shotover-proxy/examples/cassandra-protect-local/docker-entrypoint.sh
- shotover-proxy/examples/cassandra-protect-local/topology.yaml
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/protect/mod.rs
- shotover-proxy/tests/cassandra_int_tests/basic_driver_tests.rs
- test-helpers/src/docker_compose.rs
closes https://github.com/shotover/shotover-proxy/issues/462
The motivation here is these integration tests will serve as replacements for the Protect unittests as those unittests are filled with implementation details of the old implementation.
I put the new tests in with the cassandra int tests as that is the only protocol that attempts to support protect at the moment.
When new protocols support it they should get their own int tests for it.
I added a new `protect` feature to allow us to write integration tests for protect while not including it in the public shotover API.
`#[cfg(test)]` does not allow this as it is only enabled during unit tests not integration tests.
I manually verified that the integration test tests the encryption code path as far as the current Protect …
> Implement Protect integration tests

- shotover-proxy/Cargo.toml
- shotover-proxy/benches/cassandra_benches.rs
- shotover-proxy/benches/redis_benches.rs
<s>- Move the init code out of the actual bench-marking code</s>
<s>- Move each of the Redis benchmarks to functions so they can be run individually without having to run other benchmark's init code beforehand.</s>
- add cassandra_benches.rs file so CI on #512 works
> Add empty cassandra_benches file

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/benches/redis_benches.rs
Uses a fork of criterion that allows us to provide an Fn that will generate our state only when the bench is actually run.
This gives us the best of both worlds: improve noise in the redis integration benches while allowing us to continue running benches individually.
In order to land this PR in a reasonable amount of time I suggest that we create a shotover/criterion repo to host this fork until it reaches upstream.
I have created a PR to review the temporary fork https://github.com/shotover/criterion.rs/pull/1
> Fix redis benchmark initialization

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/src/codec/cassandra.rs
This was extremely useful for recent debugging of cassandra messages and im sure we'll need it again.
There is too much noise at debug level tracing for this to be directly useful, the intended use case is to temporarily bump the tracing::debug up to a tracing::warn or something when you need to view this log.
This PR is a bare minimum approach, but i would love to hear ideas on how to better solve this problem.
We could do something like log this to tracing::info when a CLI arg is provided to give easier developer access and user access to these logs.
I dont want to make it tracing::info by default because its:
* too noisy
* a security concern to be logging the contents of all messages.
Example output:
```
2022-02-07T00:35:38.718884Z  WARN request{id=5 source="CassandraSource"}: …
```
> Add debug traces to hex dump cassandra messages

- shotover-proxy/src/codec/cassandra.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/server.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/src/transforms/distributed/consistent_scatter.rs
- shotover-proxy/src/transforms/redis/timestamp_tagging.rs
- shotover-proxy/src/transforms/tee.rs
Mostly changes pulled from #445, modified to compile on `main`. I also:
- Attempted to fix the `get_size` method. It checks the length of the Redis frame. Wanted to confirm that this is the right approach before I modify cdrs-tokio to add a similar method for checking the length of the Cassandra frame.
- Addressed the TODO on `tagged_success` and `exec_block`
> Rewrite TimestampTagger and ConsistentScatter to use message.original

- .github/workflows/bench_run.yml
- .github/workflows/test.yml
I saw a suspicious log in the `actions-rs/toolchain@v1` section of our CI.
After investigating I realized that github actions installs rustup by default so theres really no need to be mucking around with `actions-rs/toolchain` in the first place.
The default rustup installation provided by github actions has no toolchains installed which is perfect for us as we want the correct toolchain to be pulled in as specified by the rust-toolchain.toml.
I thought this would give us a ci runtime improvement but the 11s time to run this step seems to have just been completely moved to the next step as thats when the rust toolchain actually gets pulled in now.
> Remove actions-rs/toolchain

- shotover-proxy/benches/chain_benches.rs
- shotover-proxy/src/server.rs
- shotover-proxy/src/transforms/null.rs
chain_benches change is straightforward, just using simpler message construction because the custom field values arent actually needed.
server changes maintain identical functionality but is now simpler as we no longer construct an entire new message just to check that it has a return_to_sender flag later on.
Unfortunately we hit a clippy false positive here, so we need to add `#[allow(clippy::unnecessary_filter_map)]`.
Whats happening is we need to use filter_map instead of filter so that we have ownership of the message and can send it off but clippy doesnt realize we are actually using the value.
> Misc message details progress

- shotover-proxy/benches/cassandra_benches.rs
- shotover-proxy/tests/scripts/bench_against_master.sh
These extra test cases should be useful for the message details rewrite.
I didnt bother to add the actual cache path for redis-cache as it doesnt work properly yet and the condition for caching is planned to change slightly.
protect-local encrypted case is taken from the integration test
> Add some more cassandra integration benches

- shotover-proxy/src/transforms/query_counter.rs
- shotover-proxy/tests/runner/observability_int_tests.rs
Maintains the same format as the old QueryCounter but also fixes two bugs in the redis implementation:
* redis `query` value is now a nice value like "SET" instead of "BULKSTRING([71, 69, 84])"
* redis query counter actually works now - I didnt investigate too deeply but probably `ASTHolder::Commands(List(commands))` was not the correct way to get message details for redis.
> Rewrite QueryCounter to use message.original

- shotover-proxy/benches/chain_benches.rs
- shotover-proxy/src/transforms/redis/timestamp_tagging.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
Progress towards https://github.com/shotover/shotover-proxy/issues/535
Reenables a bunch of integration test cases, most noteworthy is `test_info` which would have prevented the raised issue.
I replaced the current wrapping decision logic black list with a sort of white list.
It allows any QueryType::Read or QueryType::ReadWrite command that has at least one argument.
This is currently an improvement other the previous implementation.
My reasoning for this approach is that it is not meaningful to attach a timestamp to a non-read command. Is my understanding correct here?
But I suspect its still not accurate enough, we should probably instead have a proper whitelist that specifies every command that can be compatibly wrapped by RedisTimestampTagger.
If we think a proper whitelist is the …
> Improve RedisTimestampTagger logic for deciding whether to wrap or not

- shotover-proxy/tests/scripts/bench_against_master.sh
Case was found where 5 was one line too little: https://github.com/shotover/shotover-proxy/pull/528#issuecomment-1042689135
Rather than fixing it properly lets bump it up one.
> Benchmark logs grep includes 6 previous lines instead of 5

- shotover-proxy/src/sources/cassandra_source.rs
- shotover-proxy/src/sources/mod.rs
- shotover-proxy/src/sources/mpsc_source.rs
- shotover-proxy/src/sources/redis_source.rs
Remove an unneeded trait, similar to the other one for Transforms we removed a couple months ago.
> Remove SourcesFromConfig trait

- Cargo.lock
This fixes an issue where the benchmarks workflow fails due to an out of sync Cargo.lock on the main branch.
We'll have to force merge as the problem is due to the state of the main branch.
> check in cargo lock

- .github/workflows/test.yml
- shotover-proxy/build/install_ubuntu_packages.sh
This will prevent incidents like https://github.com/shotover/shotover-proxy/pull/571 from occurring again.
Will also ensure tests aren't leaving weird files around.
> Add check for untracked/uncommitted files in CI

- Cargo.lock
- shotover-proxy/src/frame/cassandra.rs
Takes the same approach as CassandraOperation::Result, recreate a bunch of structures so that we can replace the string query with the query AST.
batch queries are now parsed by sql_parser (soon to be replaced with claudes parser)
> Parse cassandra batch messages

- shotover-proxy/src/server.rs
- shotover-proxy/src/sources/cassandra_source.rs
- shotover-proxy/src/sources/redis_source.rs
Previously if you run two `cargo run` and then run another `cargo run` at the same time, you would get a success exit code and the error `failed to accept connection cause=Address already in use (os error 98) address=127.0.0.1:6379`
With this PR doing the same will give you a failure exit code and the error: `Address already in use (os error 98) address=127.0.0.1:6379`
The original implementation shutting down shotover only occurs when all sources have their port taken, what happens is shotover detects that there are no longer any sources running and performs its natural shutdown procedure.
With this change it will always fail to startup even if only one of many sources have their port taken.
I was motivated to make this change to make integration tests fail in a clearer way when there is …
> Fail to start shotover when configured port already taken

- shotover-proxy/tests/cassandra_int_tests/basic_driver_tests.rs
Bumping up due to intermittent failures on the CI, as demonstrated on https://github.com/shotover/shotover-proxy/pull/577
> Bump up Cassandra request throttling tests threshold

- shotover-proxy/src/message/mod.rs
Noticed this pattern of splitting up similar method in different `impl` on some other libraries.
> Split up message methods

- shotover-proxy/benches/cassandra_benches.rs
- shotover-proxy/src/transforms/debug/force_parse.rs
- shotover-proxy/src/transforms/debug/mod.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/tests/test-configs/cassandra-passthrough-parse-request/topology.yaml
- shotover-proxy/tests/test-configs/cassandra-passthrough-parse-response/topology.yaml
This will be useful for evaluating the performance of the cassandra parser.
To get realistic evaluation of the performance impact we would want to run cassandra-passthrough-parse-request/topology.yaml etc on the cassandra_bench example.
The benches here could be useful but at the very least they ensure that these yaml's dont bitrot and that DebugForceParse the transform doesnt explode.
> Add DebugForceParse transform

- shotover-proxy/examples/cassandra_bench.rs
- shotover-proxy/tests/runner/runner_int_tests.rs
- test-helpers/src/shotover_process.rs
Changes:
* The initial cargo build was swapped to `run_command` as that will print output on failure.
* `.env("RUST_LOG", "debug,shotover_proxy=debug")` was removed as it did nothing (didnt bother investigating why) and it is incorrect (we should be logging at info level not debug level)
* `wait()` now returns WaitOutput so we dont have to guess what tuple value contains what.
* implemented AssertExitsWith which will trigger the requested assert when ShotoverProcess is dropped.
> Cleanup and improve assertions of ShotoverProcess

- shotover-proxy/src/transforms/chain.rs
- shotover-proxy/src/transforms/coalesce.rs
- shotover-proxy/src/transforms/filter.rs
- shotover-proxy/src/transforms/mod.rs
I noticed this when investigating redis pubsub support.
This change is more semantically accurate and avoids an extra allocation per request.
> Store Wrapper.transforms as an IterMut instead of a cloned Vec

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/tests/codec/util/packet_capture.rs
- shotover-proxy/tests/codec/util/packet_parse.rs
Ended up down this rabbit hole because I went to remove the num_cpus dep as its now built into rust 1.59, however discovered that we didnt need it at all in the first place.
* Removes commented out code + dependencies used by commented out code
* Reduces test runtime by 10s by parallelizing the workload, theres still 10s of runtime left that could be optimized but I dont have high confidence in the approach of this test in the first place so i'll leave as is.
* Simplifies implementation, rayon is much simpler to use than raw Threadpools
> Reenable parallelization of packet parsing in packet tests

- shotover-proxy/tests/redis_int_tests/assert.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
- shotover-proxy/tests/redis_int_tests/mod.rs
Pulls the int test changes out of https://github.com/shotover/shotover-proxy/pull/608 so that we can land this ASAP to avoid merge conflicts.
Naturally I had to disable the assert in assert_ok as this PR doesnt include the bug fix, but that will be enabled when we land the fix.
> Rewrite redis_int_tests to assert on write only responses

- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/tests/redis_int_tests/assert.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
This adds an integration test case `test_client_name` that reproduces the issue explained in #605
This PR also adds asserts on the return value of every write only command.
Doing so discovered that this bug also affects the FLUSHDB command.
In fact it should affect every command listed in here https://github.com/shotover/shotover-proxy/blob/1a0f731ea01423d919f588b8c5bc7d5aefa1f575/shotover-proxy/src/transforms/redis/sink_cluster.rs#L552+#L555
Im not sure if these assert_int/assert_ok helpers are the best approach, maybe I should have used the connection.get/set helpers combined with assert_eq instead.
But oh well we can always swap to that later.
The PR includes a fix that fixes the issue but I have set the PR as draft because I still want to investigate if there is a more appropriate …
> Fix RedisSinkCluster returning an array of responses instead of a single response

- shotover-proxy/src/message/mod.rs
As mentioned in https://github.com/shotover/shotover-proxy/pull/598#issuecomment-1110593846
The fix works because `.frame()` triggers a full message parse but `.metadata()` just manually grabs a few bits from the header.
> Avoid triggering a message parse in the Null transform

- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
* A `ResponseJoin` enum is added to `RoutingInfo::AllMasters`.
+ The ResponseJoin defines how the redis responses should be joined into a single response for returning to the client.
+ Currently it only has `First` and `ArrayJoin` but I have also identified a need for the following to be added later on:
- `ResponseJoin::IntegerSum` - needed for DBSIZE
- `ResponseJoin::EarliestDate` - needed for LASTSAVE
- There is likely more undiscovered cases
+ Other `RoutingInfo` variants dont need to specify a `ResponseJoin`, even `AllNodes` doesnt need it as `AllNodes` should only really be used by commands like SAVE/BGSAVE.
* The KEYS command is now properly handled by the cluster sink.
+ This isn't a high priority feature but it was the easiest way to demonstrate this abstraction will work.
* …
> Implement redis cluster sink ResponseJoin abstraction

- shotover-proxy/example-configs/redis-cluster-auth/topology.yaml
- shotover-proxy/src/transforms/redis/cluster_ports_rewrite.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
closes https://github.com/shotover/shotover-proxy/issues/606
The issue was that we were failing as soon as we received an unexpected message in this transform.
To handle NOAUTH and likely other error cases too we should just ignore messages in an unexpected format.
> Fix RedisClusterPortsRewrite noauth handling

- shotover-proxy/tests/cassandra_int_tests/basic_driver_tests.rs
These extra test cases demonstrate where we do and dont currently rewrite the port.
Landing this PR will assist in demonstrating the changes to CassandraPeersRewrite functionality that is intended by https://github.com/shotover/shotover-proxy/pull/598/files
> Improve CassandraPeersRewrite int tests

- shotover-proxy/src/codec/cassandra.rs
- shotover-proxy/src/codec/redis.rs
The Cassandra protocol is designed to allow multiple inflight messages, Shotover currently doesn't take advantage of this: we read one frame off the socket, process it through the transform chain, send to the upstream and wait for the response. This change allows us to read multiple frames off the socket and process a batch instead.
Bench results with latte:
> Read multiple Cassandra frames

- shotover-proxy/src/codec/redis.rs
- shotover-proxy/src/config/mod.rs
- shotover-proxy/src/config/topology.rs
- shotover-proxy/src/observability/mod.rs
- shotover-proxy/src/server.rs
- shotover-proxy/src/tls.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
closes https://github.com/shotover/shotover-proxy/issues/183
The reason I jumped on this was because I hit an issue in https://github.com/shotover/shotover-proxy/pull/624 due to the incomplete use of context.
What happened was a contextified anyhow was printed with `error!("{}")` instead of `error!("{:?}")`.
This results in a log that lacks the innermost error.
So the core fix here is the changes to server.rs
However I wanted to make the rest of shotover make use of `.context` while I was doing this to make our errors uniform.
That said, I'm not 100% sure that using context is actually the right call.
The `{}`/`{:?}` difference is definitely a footgun.
So maybe we would be better off just entirely removing the use of `.context` instead?
Here is what logged error created via `.context()` …
> Use anyhow .context() instead of manually constructing error messages

- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
closes https://github.com/shotover/shotover-proxy/issues/605
Justification for changes to command mappings:
* DBSIZE
+ Query every master and sum the result. Allows us to pretend to be a single redis instance.
* KEYS
+ Query every master and combine the results.
+ Running `KEYS *` in a large production environment could OoM shotover, but I assume in such an environment the instances would be configured to not allow running KEYS, so each redis instance would return an error and then we would return a single error to the client which would be fine.
* ACL
+ Not sure about this one but it seemed like the majority of the ACL commands should be run uniformly against every instance.
+ Possibly we will need to revisit this in the future.
* SAVE + BGSAVE + BGREWRITEAOF
+ If the user wants to force …
> rework redis cluster command mapping

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/src/codec/cassandra.rs
Use a new method that only checks the frame length and version of incoming Cassandra frames before fully parsing them. 
Latte benchmarks against main:
<s>Waiting on https://github.com/krojew/cdrs-tokio/pull/93 to be merged.</s>
> use check_frame instead of from_buffer

- shotover-proxy/src/message/mod.rs
I am choosing  to use the name Null here as that tends to be what the corresponding value in redis and cassandra is called.
`MessageValue::None` is never created anywhere so I am confident in deleting it.
> Combine MessageValue::None and MessageValue::NULL

- shotover-proxy/src/transforms/redis/sink_cluster.rs
This is a more accurate name for the variable as its only purpose is to provide a better error message if possible, it doesnt actually affect whether an error will occur or not.
This variable might end up deleted in another planned refactor but at least by landing this first it will make the next PR easier to review.
> Rename connection_error -> reason_for_no_nodes

- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
Closes https://github.com/shotover/shotover-proxy/issues/656
The way to enable RESP3 is to send a "HELLO 3" message - https://redis.io/commands/hello/
The lettuce client attempts that by default but fallsback to resp2 if the error message contains "unknown" - an attempt to match against the `-ERR unknown command 'hello'` error message.
I believe the best way for shotover's RedisSinkCluster transform to handle RESP3 is to just tell clients that we dont support it.
Handling RESP3 would be fairly tricky due to the extra state that needs to be taken into account in our connection pool.
RedisSinkSingle on the other hand could much more easily support RESP3 but doesnt yet.
Currently RedisSinkSingle will also break if it receives a "HELLO 3" but I would rather add proper RESP3 support there and …
> RedisSinkCluster handle attempts to use RESP3

- shotover-proxy/src/transforms/cassandra/connection.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/src/transforms/util/cluster_connection_pool.rs
- shotover-proxy/src/transforms/util/mod.rs
Only one message was ever stored and allowing for multiple messages is incorrect when the `original` field only has one Message.
> store response as single Message instead of Vec<Message>

- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
There are two parts to this refactor:
1. ChannelResult is removed - instead of returning a ChannelResult in get_channels that describes how we should use the channel we just directly use the channel.
* its easier to follow what each case is doing in dispatch_message_hiding - just check the inner function call rather than having to backtrack
* its more flexible for uniquely handling a case without having to add a new hyperspecific ChannelResult variant. e.g. we can now directly send a single message which was impossible before.
* the dispatch_message_handling approach used in https://github.com/shotover/shotover-proxy/pull/642/files is more feasible
* we can just directly use the direct_connection channel without having to feed it through ChannelResult somehow.
* returning proper error …
> RedisSinkCluster ChannelResult and short_circuit refactor

- shotover-proxy/src/transforms/protect/aws_kms.rs
- shotover-proxy/src/transforms/protect/crypto.rs
- shotover-proxy/src/transforms/protect/key_management.rs
- shotover-proxy/src/transforms/protect/local_kek.rs
- shotover-proxy/src/transforms/protect/mod.rs
- shotover-proxy/tests/cassandra_int_tests/basic_driver_tests.rs
Refactor pulled out of https://github.com/shotover/shotover-proxy/pull/661
This should have no functional changes.
Technically the serialization format for protected values has changed making it a breaking change, (as can be seen in the changed integration test) but its impossible to use this transform in production yet anyway.
Changes included in this refactor:
* private_cached_fetch key_id an `&str` now to save an allocation as we never needed a String anyway (key_id only ever gets used in a `format!()`)
* KeyMaterial is moved into the key_management module - its pretty closely related to KeyManager, so makes sense to keep it together.
* All the encryption/decryption logic is moved into its own module and is reduced into a simple encrypt/decrypt pair of functions.
+ the logic is now …
> Refactor Protect transform

- shotover-proxy/tests/helpers/mod.rs
Because of the hacky way this file is imported every method needs  `#[allow(unused)]`  which allowed this dead code to go unnoticed.
We could additionally remove the `with_observability_interface` builder style API from `Runner` but I would rather leave that as is because it demonstrates a design I would like to explore with shotover later on.
> remove unused from_topology_file_without_observability

- docs/src/examples/cassandra-cluster-shotover-sidecar.md
- shotover-proxy/example-configs-docker/cassandra-peers-rewrite/docker-compose.yml
- shotover-proxy/tests/test-configs/cassandra-peers-rewrite/docker-compose-3.11-cassandra.yaml
- shotover-proxy/tests/test-configs/cassandra-peers-rewrite/docker-compose-4.0-cassandra.yaml
@rukai noticed we don't need this and it gives us a speedup on test runtime.
> remove depends_on from Cassandra docker clusters

- shotover-proxy/src/transforms/cassandra/peers_rewrite.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
Pulled out of https://github.com/shotover/shotover-proxy/pull/598
A bit frivolous by itself, but is clearly more correct in isolation and 598 will get more benefits from it.
Instead of just rewriting the first instance of native_port in a system.peers query we now rewrite every instance of native_port.
The change in output to the existing integration test demonstrates the change well.
> cassandra peers rewrite - rewrite all native_ports

- Cargo.lock
- shotover-proxy/benches/chain_benches.rs
- shotover-proxy/src/codec/cassandra.rs
- shotover-proxy/src/frame/cassandra.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/transforms/cassandra/peers_rewrite.rs
- shotover-proxy/tests/cassandra_int_tests/collections.rs
Box changes are needed for clippy stack usage lints
Sticking `Version::V4` everywhere doesnt bother me because we were already doing that before.
We can address that properly when we add support for protocol v5
The new Duration type will need to be refined in the future to handle multiple protocols
But for now it lets us roundtrip cassandra Durations which is all we really care about.
> Update deps, lots of cassandra-protocol breaking changes

- shotover-proxy/src/frame/cassandra.rs
- shotover-proxy/tests/cassandra_int_tests/protect.rs
closes https://github.com/shotover/shotover-proxy/issues/563
This PR allows transforms like redis cache and protect transform to work on batch messages.
This however only works for batch messages sent over the BATCH protocol, batch messages sent over QUERY are still broken.
You can verify the integration test tests the new functionality by disabling the new `CassandraOperation::Batch(batch)` handling and observing the test fail.
> CassandraOperation::queries returns batch queries

- shotover-proxy/benches/chain_benches.rs
- shotover-proxy/src/transforms/protect/mod.rs
Adds benches to directly bench the protect transform without going through the full shotover<->cassandra stack
You can confirm that the `cassandra_protect_protected` hits the encryption path by observing that it performs a lot worse than `cassandra_protect_unprotected`
```
transform/cassandra_protect_unprotected
time:   [1.7484 us 1.7582 us 1.7666 us]
Found 2 outliers among 100 measurements (2.00%)
2 (2.00%) high severe
transform/cassandra_protect_protected
time:   [6.0483 us 6.0769 us 6.1084 us]
```
These benches will help with evaluating the impact of https://github.com/shotover/shotover-proxy/pull/685
> Add benches for protect transform

- shotover-proxy/src/runner.rs
- shotover-proxy/src/sources/cassandra_source.rs
- shotover-proxy/src/sources/mod.rs
- shotover-proxy/src/sources/redis_source.rs
* ~~runner.rs changes cause panics in sources to unwind all the way up such that shotover terminates.~~
+ ~~This is desirable for integration tests - any panic in shotover should cause the int test to fail.~~
+ ~~I also believe this is desirable for end users, a panic is an unrecoverable error and so should be handled as such.~~
+ ~~Previously it looked like we were getting that behavior in tests but that was just because:~~
- ~~the test itself was failing due to assertions causing a panic + full unwind~~
- ~~while tokio was catching the source panic at the task boundary, displaying the error and then never unwinding the rest of the way.~~
* `JoinHandle<Result<()>>` -> `JoinHandle<()>` is changed because there is no expected runtime error for a source. They should be handling all of their …
> Remove unneeded Result from source return type

- shotover-proxy/src/transforms/filter.rs
- shotover-proxy/tests/helpers/mod.rs
closes https://github.com/shotover/shotover-proxy/issues/498 - although the design ended up different to what I initially described in that issue
I went through many design and implementation attempts before finally landing on this one.
Some other things I tried that didnt work out:
* always joining + unwrapping every task. Gave up on this because holding the JoinHandle around to do that is very tricky for long running tasks.
* writing a #[cfg(debug_assertions)] wrapper of tokio::spawn that catches panics in the task before it reaches tokio. I never got this working and the design it also relied on the developer to always call the wrapper.
But I'm now quite happy with the design I ended up with.
By using set_hook we can ensure that any panic at all will fail an integration test without …
> Detect panics in integration tests

- shotover-proxy/src/frame/cassandra.rs
- shotover-proxy/src/transforms/redis/cluster_ports_rewrite.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
closes https://github.com/shotover/shotover-proxy/issues/174
Looks like all the actually worrying cases had already been fixed by other work.
That leaves us with the following cases that are worth fixing but are extremely rare:
* length checks - check the length of any array/vec before addressing it or use `.get` to ensure panics cannot be caused maliciously
* String::from_utf8_lossy -> str::from_utf8 - in this case we are processing a server reply, so we should assume the server will provide utf8 data but we should also not panic when its not in case something malicious is going on.
> redis bulkstring handling fixes

- shotover-proxy/src/codec/redis.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/server.rs
The previous warning `warn!("failed to decode message: {}", error)` resulted in the very confusing output: 
```
WARN request{id=8 source="RedisSource"}: shotover_proxy::server: failed to decode message: Connection reset by peer (os error 104)
```
But now the message acknowledges that the error could also be from receiving.
The previous error `error!("Stream ended with error {:?}", err);` was changed to match the format of the receive/decode message
> Minor improvements

- shotover-proxy/src/server.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
Discovered while investigating https://github.com/shotover/shotover-proxy/pull/706 but quite likely unrelated.
I had previously expected that when a transform returns a `Result::Err` the connection would be immediately dropped.
Upon writing an integration test to prove this, I discovered that it is in fact not the case.
Currently a transform returning `Result::Err` will result in no reply sent to the client and the connection remaining open, very likely resulting in the client waiting indefinitely for a response.
So this PR changes shotover to drop the connection immediately when a transform returns a `Result::Err`.
If a transform wishes to avoid dropping the connection when encountering an error they should handle the error internally.
There was also some changes needed to ensure the …
> Close connection on transform error

- shotover-proxy/src/transforms/mod.rs
This way we enforce at compile time that the transforms add_pushed_messages implementation is hit.
> Replace pushed_messages_tx if let with exhaustive match

- shotover-proxy/example-configs/cassandra-cluster/docker-compose.yml
- shotover-proxy/example-configs/cassandra-cluster/topology.yaml
- shotover-proxy/src/transforms/cassandra/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- test-helpers/src/docker_compose.rs
Introduces the CassandraSinkCluster behind the alpha-transforms feature so that we can start collaboratively working on it.
Is currently identical to the implementation of CassandraSinkSingle except for the config which reflects the final config we want to have for CassandraSinkCluster.
Currently has the same integration test cases as CassandraSinkSingle but test cases will be added and removed as needed in future PRs.
> Add CassandraSinkCluster

- shotover-proxy/src/transforms/cassandra/sink_single.rs
I'm pretty sure the TODO was because `Response { result, .. }` used to contain multiple `Message`s but that has since been fixed separately so we can remove the TODO.
The timeout info should really be an `error!` it indicates a failure in communication with the destination node.
The second info can just be removed as it doesnt provide anything we need that isnt already in the first log.
> small cleanup in CassandraSinkSingle

- Cargo.lock
- shotover-proxy/Cargo.toml
Will make the TLS fixes available for https://github.com/shotover/shotover-proxy/issues/708
> Release shotover 0.1.5

- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
Closes https://github.com/shotover/shotover-proxy/issues/491 (We now ensure we read a response for every request we send out, which fixes the hang)
Implements the `transform_subscribe` idea described in https://github.com/shotover/shotover-proxy/issues/541
This only implements support for RedisSinkSingle.
I will investigate RedisSinkCluster later on, not sure what will be involved for that one.
> Redis pubsub support

- shotover-proxy/benches/cassandra_benches.rs
- shotover-proxy/tests/cassandra_int_tests/batch_statements.rs
- shotover-proxy/tests/cassandra_int_tests/cache/assert.rs
- shotover-proxy/tests/cassandra_int_tests/cache/mod.rs
- shotover-proxy/tests/cassandra_int_tests/collections.rs
- shotover-proxy/tests/cassandra_int_tests/functions.rs
- shotover-proxy/tests/cassandra_int_tests/keyspace.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/cassandra_int_tests/native_types.rs
- shotover-proxy/tests/cassandra_int_tests/prepared_statements.rs
- shotover-proxy/tests/cassandra_int_tests/protect.rs
- shotover-proxy/tests/cassandra_int_tests/table.rs
- shotover-proxy/tests/cassandra_int_tests/udt.rs
- shotover-proxy/tests/examples/mod.rs
- shotover-proxy/tests/helpers/cassandra.rs
- shotover-proxy/tests/helpers/mod.rs
This is the first step towards allowing the cassandra integration tests to run against an arbitrary driver.
The CassandraConnection enum will have a variant for every driver that it supports.
Currently CassandraConnection still leaks a lot internals of cassandra_cpp but that will be addressed in future PRs.
> wrap cassandra_cpp::Session in new CassandraConnection type

- docs/src/transforms.md
- shotover-proxy/src/transforms/cassandra/connection.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
Pulled out of https://github.com/shotover/shotover-proxy/pull/723
~~receive logic should remain exactly the same it is just refactored into a different function.~~
Receive logic is now modified to use a configurable read_timeout.
Additionally the timeout logic is now changed to immediately close the connection on a timeout.
Previously it would just drop the timedout message and continue normally which breaks the transform invariants.
> Move cassandra sink receive logic into connection::receive

- shotover-proxy/src/transforms/cassandra/connection.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster.rs
- shotover-proxy/tests/cassandra_int_tests/cluster.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/cassandra_int_tests/native_types.rs
Messages are never routed to the initial contact point as it is not considered a peer.
I consider this a bug but i'm not addressing it in this PR to keep the scope down 
I had previously mentioned implementing round robin for this PR but considering the final goal is "best of two choices", just doing a single random selection seemed like the best step towards that while still being a sound decision for an MVP.
I pulled the receive logic out of the two sink transforms and into connection.rs
> Implement basic cassandra cluster routing

- shotover-proxy/tests/cassandra_int_tests/functions.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/cassandra_int_tests/schema_awaiter.rs
- shotover-proxy/tests/cassandra_int_tests/table.rs
- shotover-proxy/tests/cassandra_int_tests/udt.rs
Fixes https://github.com/shotover/shotover-proxy/runs/7739411831?check_suite_focus=true
This time the problem is in table::test
... and another showed up in udt::test
The problem is because we arent waiting for the cluster to reach schema agreement before running certain commands, so we can fix it by using the SchemaAwaiter like we do in functions::test
Rather than remove another test case from the TLS tests I reintroduced the previously removed functions::test case by adding a new_noop constructor
> Fix another intermittent cluster failure

- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
- shotover-proxy/tests/redis_int_tests/mod.rs
Moves the actual test cases from `redis_int_tests::basic_driver_tests` -> `redis_int_tests`
No changes to test logic occured.
This way it is easier to remember unique test names: `cargo test redis_int_tests::test_passthrough` instead of `cargo test redis_int_tests::basic_driver_tests::test_passthrough` 
It also matches the names already used by cassandra: `cargo test cassandra_int_tests::test_passthrough`
Organization wise it also makes sense, we have split up an 1851 line long file into two smaller files at a nice boundary.
> refactor redis_int_tests

- rust-toolchain.toml
- shotover-proxy/src/lib.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/transforms/protect/crypto.rs
I opted to disable the new derive_partial_eq_without_eq lint, because blanket enforcing full Eq seems like a bad idea when the type might not meet the semantics of Eq
> Update to rust 1.63

- shotover-proxy/tests/cassandra_int_tests/functions.rs
- shotover-proxy/tests/cassandra_int_tests/udt.rs
- shotover-proxy/tests/helpers/cassandra.rs
This one is a lot rarer.
Heres a screenshot of it occuring.
I suspect the difference in error message is caused by the error occurring on a query that the coordinator has routed onto another node rather than just being run locally by the coordinator.
Thats just a guess though and it doesnt really matter the cause, the error can be different sometimes so we just need to change the assert to a contains check rather than an equals check.
> Fix a (different) intermittent failure

- shotover-proxy/src/transforms/cassandra/sink_cluster.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
When we receive a USE statement we need to:
* route it to all open connections
* route it to all future connections
* respond to the client with a single response
We could drastically simplify the USE statement error handling by just terminating all connections when we get a use statement.
I assume its worth keeping the connections alive but its possible that we are better off just terminating them.
> CassandraSinkCluster implement USE routing

- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
No logic changes to the tests, just improves the error messages on test failure.
Motivated by a mysterious test failure conor observed in https://github.com/shotover/shotover-proxy/pull/745#issuecomment-1216059143
> Improve redis int test assert messages

- shotover-proxy/src/transforms/cassandra/sink_cluster.rs
- shotover-proxy/tests/cassandra_int_tests/cluster.rs
The change to the integration test demonstrates the change: we are now representing the entire cluster in the nodes list, previously we only included the 2 peers of the node we are querying but now we include the node itself as well.
Additionally I improved the error handling by:
* system_peers_into_node now returns errors for cases that are unrecoverable instead of silently ignoring the case.
+ A nice improvement this will bring is `CassandraOperation::Error`s are now logged - a possible case that could cause that is an auth error which is a realistic case.
* Retry querying the same peer 3 times and then move onto another handshake provided by another clients connection.
The old QueryParams values were blindly copy pasted in and on closer inspection they are not very good. e.g. page_size …
> CassandraSinkCluster query system.local for local node info

- shotover-proxy/src/transforms/cassandra/sink_cluster.rs
Problems with previous implementation:
* Didnt support cassandra instances configured without auth (handshakes without `CassandraOperation::AuthResponse`)
* Didnt support handshakes that make use of fallback authentication options. (handshakes with multiple `CassandraOperation::AuthResponse`)
* `CassandraOperation::Options` was needlessly included in the handshake, making handshakes more expensive.
> CassandraSinkCluster: make handshake logic robust

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node.rs
Pulled out of https://github.com/shotover/shotover-proxy/pull/750
Should drastically improve the diff of 750 by merging this first.
> Split sink_cluster.rs

- shotover-proxy/tests/cassandra_int_tests/cluster.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
As requested in the review of https://github.com/shotover/shotover-proxy/pull/744
> test test_topology_task in TLS mode

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/benches/chain_benches.rs
- shotover-proxy/example-configs/cassandra-cluster-tls/topology.yaml
- shotover-proxy/example-configs/cassandra-cluster/topology.yaml
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/server.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/chain.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/parallel_map.rs
- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/tests/cassandra_int_tests/cluster.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/cassandra_int_tests/udt.rs
- shotover-proxy/tests/helpers/cassandra.rs
Misc changes:
* The `v4` uuid feature is needed to enable random uuid generation
* The changes to `ResultValue::new` are needed to allow handling null values in cases that I hit where it wasnt. There are still other null value cases that its not handling properly but I dont know where cassandra will and wont return null values so I'm just leaving the rest to be dealt with when we hit them.
* I introduced an `Any` variant to `ResultValue`, the idea here is to allow `assert_query_results` in cases where there are values that are non deterministic. assert_query_results provides an intuitive way to assert on both the length and the contents of the results so I think `Any` is a lot better approach then just manually doing something like `assert_eq!(results[3], ResultValue::Varchar("blah"))`
* …
> CassandraSinkCluster rewrite system.local

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/src/transforms/chain.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
`add` implies adding a value to a list whereas `set` implies setting a value or state.
> Rename add_pushed_messages_tx -> set_pushed_messages_tx

- shotover-proxy/example-configs/cassandra-cluster-multi-rack/docker-compose.yml
- shotover-proxy/example-configs/cassandra-cluster-multi-rack/topology_rack1.yaml
- shotover-proxy/example-configs/cassandra-cluster-multi-rack/topology_rack2.yaml
- shotover-proxy/example-configs/cassandra-cluster-multi-rack/topology_rack3.yaml
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/tests/cassandra_int_tests/cluster.rs
- shotover-proxy/tests/cassandra_int_tests/cluster_multi_rack.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- test-helpers/src/docker_compose.rs
Pulled out of https://github.com/shotover/shotover-proxy/pull/756
Should reduce the scope of 756 a bit and will also let me test and fix a preexisting issue.
Introduced a new integration test `test_cluster_multi_rack` it tests all the same cases as `test_cluster` but each cassandra node is on a different rack and each cassandra node has its own shotover instance in front of it.
The fix to the issue is not complete but a full fix will require deciding between:
1. changing the design of the transform such that providing a node outside of the datacenter/rack in the contact points will cause shotover to return errors to every incoming message as upholding our invariants in that case is too tricky.
2. rewrite system.local rewriting to send an additional system.local
This PR makes enough …
> Add test_cluster_multi_rack

- shotover-proxy/example-configs/cassandra-cluster-multi-rack/topology_rack1.yaml
- shotover-proxy/example-configs/cassandra-cluster-multi-rack/topology_rack2.yaml
- shotover-proxy/example-configs/cassandra-cluster-multi-rack/topology_rack3.yaml
- shotover-proxy/example-configs/cassandra-cluster-tls/topology.yaml
- shotover-proxy/example-configs/cassandra-cluster/topology-dummy-peers.yaml
- shotover-proxy/example-configs/cassandra-cluster/topology.yaml
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/tests/cassandra_int_tests/cluster.rs
- shotover-proxy/tests/cassandra_int_tests/cluster_multi_rack.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
Introduced a new integration test `test_cluster_multi_rack` it tests all the same cases as `test_cluster` but each cassandra node is on a different rack and each cassandra node has its own shotover instance in front of it.
The existing `test_cluster` was renamed to `test_cluster_single_rack` and now runs two shotover test cases against the cassandra cluster.
One to test an empty peers list and one to test a consistent peers list.
The derived fields of system.peers should be non controversial as its the same as system.local.
This PR configures the configurable fields with the following configuration:
```yaml
- CassandraSinkCluster:
first_contact_points: ["172.16.1.2:9042", "172.16.1.3:9042"]
data_center: "dc1"
rack: "rack1"
host_id: "2dd022d6-2937-4754-89d6-02d2933a8f7a"
shotover_peers:
- …
```
> CassandraSinkCluster system.peers rewrite

- test-helpers/src/docker_compose.rs
pulled from #741 
I use the debug level often and these logs get pretty noisy when it's on services that takes a while to start (such as the Cassandra cluster ones).
> Drop docker logs to trace level

- shotover-proxy/src/tls.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/tests/cassandra_int_tests/cluster.rs
A change pulled from the `NodePool` PR. No functional changes, just encapsulates the logic for creating new connections.
> ConnectionFactory

- shotover-proxy/tests/cassandra_int_tests/functions.rs
Main is failing with this error: 
```
2022-08-25T12:24:54.7233573Z thread 'cassandra_int_tests::test_cluster_multi_rack' panicked at 'Expected the error to contain 'Unknown function 'test_function_keyspace.my_function'' but it did not and was instead 'Cassandra detailed error SERVER_INVALID_QUERY: Invalid number of arguments in call to function
```
I can't find any mention of functions in the schema version agreement docs so that leads me to believe that awaiting for schema agreement does not include functions.
Decided to remove this test rather than implement something to wait for changes to functions to propagate throughout the cluster since it's not testing any particular edge case.
> remove drop function test

- Cargo.lock
- shotover-proxy/Cargo.toml
To allow testing to begin on the CassandraSinkCluster MVP
> Release shotover v0.1.6

- shotover-proxy/src/transforms/cassandra/connection.rs
There is no advantage to using generics here as CassandraConnection will only ever be used with a CassandraCodec so we should directly use CassandraCodec to improve code readability.
> CassandraConnection: Replace generic codec with direct usage of CassandraCodec

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
closes https://github.com/shotover/shotover-proxy/issues/767
The problem was caused by `TcpStream::connect` blocking indefinitely when given a meaningless local ip instead of the global ip that we actually meant to give it.
The fix is: when generating the node list we need to query the correct system.local field `broadcast_address` that gives us the global ip that we actually wanted, instead of `listen_address` which gives us the local ip.
> CassandraSinkCluster fix connecting to non-local clusters

- shotover-proxy/src/transforms/filter.rs
This makes the test logs very noisy, we shouldn't show it for every message. Just once per `Wrapper` would be enough.
> Only show filter warning once

- .cargo/config.toml
- .github/workflows/build.yml
- .github/workflows/build_and_test.yml
- .github/workflows/license_check.yml
- .github/workflows/test.yml
- rust-toolchain.toml
- shotover-proxy/build/install_ubuntu_packages.sh
In order to build shotover for aarch64 locally I needed to add:
```toml
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
```
and install the aarch64 gcc
Adding the aarch64 to CI resulted in imo one too many magic CI if statements so I refactored test.yml into 3 separate workflows
> Build aarch64 in CI

- shotover-proxy/src/codec/cassandra.rs
- shotover-proxy/src/codec/redis.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/server.rs
- shotover-proxy/src/transforms/cassandra/connection.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
Improves error reporting and makes the cassandra protocol implementation easier to understand.
Downgrades the warnings caused by cassandra protocol negotiation to `info!` level.
It certainly makes the integration tests quieter, but maybe the slight performance loss of protocol negotiation is worth a warning?
Theres some magic trait type stuff going on here:
In these lines:
```rust
pub trait CodecReadHalf: Decoder<Item = Messages, Error = CodecReadError> + Clone + Send {}
impl<T: Decoder<Item = Messages, Error = CodecReadError> + Clone + Send> CodecReadHalf for T {}
```
We can set any type to be the Error as long as it implements `From<std::io::Error>`.
Internally tokio then uses that implementation to generate errors in our type when it hits an `io::Error` while receiving from the …
> Cleanup cassandra protocol negotiation

- shotover-proxy/src/transforms/cassandra/connection.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
- shotover-proxy/tests/redis_int_tests/mod.rs
> add timeout to new tcp connections

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node.rs
- shotover-proxy/tests/cassandra_int_tests/cluster.rs
- shotover-proxy/tests/cassandra_int_tests/cluster_multi_rack.rs
closes https://github.com/shotover/shotover-proxy/issues/758
The new logic looks like:
1. when we receive our first message populate local_nodes immediately if possible (if not now then we have to wait till handshake is complete)
2. process handshake
3. when we receive confirmation that handshake is complete:
1. send handshake to topology task
2. if local_nodes is empty then 
1. populate local_nodes blocking until topology task has completed once. (on my machine in int tests this takes ~50ms)
2. replace control connection with a new connection guaranteed to be from the dc/rack
5. system.local queries are always routed to a dc/rack node giving us more correctness and allowing us to remove some unneeded logic.
This didnt end up cleaning up as much code as I had originally hoped, the …
> CassandraSinkCluster: Control connection always connects to configured dc/rack

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/tests/cassandra_int_tests/cluster_single_rack_v4.rs
Fixes incorrect rewriting of system.peers_v2 fields.
The native_address/native_port fields were not being handled before, resulting in a default value of Null.
The peer_port field had the wrong value written to it - peer is used for gossip so the default gossip port of 7000 is a more natural choice.
> Fix system.peers v2 rewriting

- shotover-proxy/src/codec/cassandra.rs
- shotover-proxy/src/frame/cassandra.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/transforms/cassandra/peers_rewrite.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/topology.rs
- shotover-proxy/src/transforms/protect/mod.rs
The idea of this variant was to allow for generic manipulation of values returned from any kind of database.
However `MessageValue::Rows` represents the outermost value: the collection of all returned values.
It is semantically incorrect for a `MessageValue` that holds other `MessageValue`s to hold a `MessageValue::Rows`
This causes all kinds of silly cases where we "handle" `MessageValue::Rows` even though it makes no sense to do so.
Therefore I suggest we remove it and just directly store the `Vec<Vec<MessageValue>>` of results.
Possibly we may one day want a wrapper type `struct Results (Vec<Vec<MessageValue>>)` but it can be a wrapper rather than a variant of `MessageValue`
> remove MessageValue::Rows

- shotover-proxy/Cargo.toml
- shotover-proxy/benches/benches/cassandra.rs
- shotover-proxy/benches/benches/chain.rs
- shotover-proxy/benches/benches/codec.rs
- shotover-proxy/benches/benches/main.rs
- shotover-proxy/benches/benches/redis.rs
- shotover-proxy/tests/scripts/bench_against_master.sh
Every bench file in shotover-proxy/benches is individually compiled into its own binary.
This is really expensive because the compiler needs to reapply all the crazy optimizations for each binary.
Locally on my machine it takes ~1m 40s for each of these to compile.
Because I have plenty of cores this is all done in parallel and the fact that each binary takes so long to compile causes no slow down for me.
With this change it still takes the same ~1m 40s to compile all of the binaries.
However in CI we only have 2 cores, so having 4 benchmarks to compile doubles the time to compile from 2m to 4m.
So I expect this PR to cut off about ~2 minutes from our benchmark build time.
This also fixes the codec_benches not running in CI due to not being manually included in bench_against_master.sh. …
> Cut CI bench compile time by a few minutes

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
part of https://github.com/shotover/shotover-proxy/issues/776
Fixes an issue discovered during testing.
Queries against system keyspace tables need to be routed to the same node to remain consistent.
I took the list of system keyspaces from https://docs.datastax.com/en/dse/5.1/cql/cql/cql_using/useQuerySystem.html
> CassandraSinkCluster fix routing for system keyspaces

- shotover-proxy/src/frame/cassandra.rs
Unfortunately this had caused a clippy lint, not sure what the best course of action is:
- Leave the lint turned off
- Put the big variants in a box (alot of code changes because we will have to dereference all the Cassandra frames after parsing instead of just pattern matching)
> Parse Cassandra execute statements

- shotover-proxy/tests/helpers/cassandra.rs
- shotover-proxy/tests/helpers/mod.rs
- test-helpers/src/shotover_process.rs
Turns out #[allow(unused)] isnt equivalent to #[allow(dead_code).
unused actually turns off a whole bunch of important lints not just uncalled functions and unused variables.
I've changed every instance of unused -> dead_code, all the other changes are due to the lints now properly firing.
> unused -> dead_code

- shotover-proxy/example-configs-docker/cassandra-peers-rewrite/docker-compose.yml
- shotover-proxy/example-configs/cassandra-cluster-multi-rack/docker-compose.yml
- shotover-proxy/example-configs/cassandra-cluster-tls/docker-compose.yml
- shotover-proxy/example-configs/cassandra-cluster/docker-compose-cassandra-v3.yml
- shotover-proxy/example-configs/cassandra-cluster/docker-compose-cassandra-v4.yml
on my local machine this improves 3 instance cassandra cluster startup time by 40s
This seems to result in total 3-4mins speedup for cassandra_int_tests workflow in CI
There is no effect on benchmarks workflow because they all use single instance clusters.
> cassandra_int_tests: specify every node in CASSANDRA_SEEDS

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/tests/cassandra_int_tests/cluster_single_rack_v4.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
Implementation is pretty straightforward.
Just filter out the Topology and Status events to hide underlying cluster topology details from the clients.
Schema changes can still pass through as that is not part of the topology.
> CassandraSinkCluster: filter out Topology and Status events

- shotover-proxy/tests/cassandra_int_tests/mod.rs
starting to see a pattern where many tests run a standard test suite against their db/shotover combination so lets pull that standard test suite into a helper method
> cassandra_int_tests: add standard_test_suite helper

- shotover-proxy/tests/cassandra_int_tests/batch_statements.rs
- shotover-proxy/tests/cassandra_int_tests/prepared_statements.rs
The integration tests in this PR demonstrate some unfortunate realities about use statements: both batches and prepared statements take the `use`d keyspace into account.
This will affect how we go about handling keyspaces when identifying a keyspace/table pair.
> Use statement integration tests

- .github/workflows/bench_run.yml
- .github/workflows/build.yml
- .github/workflows/build_and_test.yml
- .github/workflows/license_check.yml
- .github/workflows/release.yml
Motivation: I wanted to make use of a feature in rust-cache@v2 but figured I may as well keep other actions up to date, so we can easily try more recent features without having to update.
Updated checkout and rust-cache to latest versions.
Removed a stray `actions-rs/toolchain@v1`, not needed anymore as github actions images now have rustup installed by default.
The cache key format seems to have changed from v1 to v2, so I'll rerun CI to confirm its caching properly.
> Update GA actions

- shotover-proxy/src/frame/cassandra.rs
- shotover-proxy/src/frame/mod.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/transforms/debug/printer.rs
- shotover-proxy/src/transforms/mod.rs
There are two benefits here:
* users of the DebugPrinter transform are given a much higher level message log.
* developers get access to much more succinct debug logs with `tracing::error!("look at this {}", message.to_high_level_string())`. In particular I was overwhelmed by all the log noise when investigating the failure on https://github.com/shotover/shotover-proxy/pull/812
In order to allow parsing the message I couldnt implement Display for Message due to needing mutable access, so instead I added a `to_high_level_string` method.
While writing the format I wanted to prioritize both terseness and including every underlying field in some way.
To do this I was willing to introduce ambiguity in many places, but that is ok because its a format for humans to read not computers.
Some …
> Improve DebugPrinter

- .github/workflows/bench_run.yml
- shotover-proxy/Cargo.toml
Fixes an issue where bench_run does not use a cache when a PR is first submitted.
PRs do not share caches, instead each PR initially pulls from the cache of the main branch for the first run.
The bench_run workflow does not run on main, so to make use of a cache before this workflow has completed once on a PR, we need to manually recreate the key used by ubuntu-18.04 release builds.
This has the risk of the cache being overwritten by the run_bench workflow, but worst case the cache gets some extra bench logs included, Swatinem/rust-cache will not cache final binary output so we dont have to worry about losing that.
But I added a TODO to make use of a feature that will completely eliminate any risk here.
Criterion's `html_reports` feature is generating ~15mb of html files across all of our …
> Bench CI speedups

- shotover-proxy/src/codec/cassandra.rs
- shotover-proxy/src/frame/cassandra.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/transforms/cassandra/connection.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/tests/cassandra_int_tests/cluster_single_rack_v4.rs
This PR handles use statements in every case except one:
* operates on both batch operations and query operations. 
* messages are modified such that if a keyspace is not specified the `use` keyspace is used, this ensures a single source of truth for transforms.
* messages are modified at the codec level ensuring all layers of shotover observe the same keyspace.
The one case we arent handling is prepared statements.
use statements also affect prepared statements, but currently shotover does not support parsing prepared statements so I have just left that functionality as a TODO.
There is a performance concern: calling metadata is currently more expensive than it needs to be due to internally copying the entire message body and then dropping it.
But that can be addressed later on in a …
> CassandraSinkCluster keyspace based routing - handle use statements

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/topology.rs
- shotover-proxy/tests/cassandra_int_tests/cluster_multi_rack.rs
- shotover-proxy/tests/cassandra_int_tests/cluster_single_rack_v3.rs
- shotover-proxy/tests/cassandra_int_tests/cluster_single_rack_v4.rs
an is_up field is introduced so that nodes that are up/down can be noted as such without completely deleting the node, this will be useful for recovering from scenarios where all nodes go down. (even though there is no such logic for that yet)
Control node selection and regular message routing is changed to use is_up
Currently the topology changes wont take affect until a new connection is made, a future PR will introduce logic to update existing connections. 
Another case that is currently not handled yet is when the topology task's control connection goes down.
Currently that is undetectable because we rely on the control connections events.
I believe the solution to that will be transforms reporting timeouts to the topology task (done in a follow up PR)
Another solution could be having …
> CassandraSinkCluster: topology task now processes events

- test-helpers/src/docker_compose.rs
On my local machine this cuts 10s off the time to complete the test.
There is no need to be polite to these docker containers as we never intend to use them again and we dont care about cleanly closing connections to clients once the test is over.
We still need the call to `docker-compose down` as that will cleanup any left over networks for us.
I'm not sure what `docker-compose rm` was for, from looking at the documentation it seems to do the same thing as our call to `docker compose down`.
I traced it back to: https://github.com/shotover/shotover-proxy/commit/efb50e696313478844d8a1a68f3b73dd2e305f55#diff-6d1e3ec7ab6aaf7a94f9c1e9a423db6de6e4a1bec380dae17cc6e635f1db8854
Probably just a mistake.
> Faster DockerCompose drop

- docs/src/examples/redis-clustering-aware.md
- shotover-proxy/example-configs-docker/redis-cluster-ports-rewrite/docker-compose.yml
- shotover-proxy/example-configs-docker/redis-cluster/docker-compose.yml
- shotover-proxy/example-configs/redis-cluster-dr/docker-compose.yml
- shotover-proxy/example-configs/redis-cluster-handling/docker-compose.yml
- shotover-proxy/example-configs/redis-cluster-hiding/docker-compose.yml
- shotover-proxy/example-configs/redis-cluster-tls/docker-compose-with-key.yml
- shotover-proxy/example-configs/redis-cluster-tls/docker-compose.yml
- shotover-proxy/tests/test-configs/redis-cluster-ports-rewrite/docker-compose.yml
I'm not sure why these were here, but removing them doesnt break anything and it makes the config a lot simpler.
It's also a possibility that volumes being kept around is causing our intermittent redis failures.
I did a bit of research and volumes are known to be faster than relying on the container layer, however removing the volumes has no observable affect on the runtime of our integration tests. And if it did help we would probably be better off just entirely avoiding the fs by disabling redis's persistence.
> Remove manual redis volumes from docker-compose.yml

- shotover-proxy/example-configs/cassandra-passthrough/docker-compose.yml
- shotover-proxy/example-configs/cassandra-protect-aws/docker-compose.yml
- shotover-proxy/example-configs/cassandra-protect-local/docker-compose.yml
- shotover-proxy/example-configs/cassandra-redis-cache/docker-compose.yml
- shotover-proxy/example-configs/cassandra-request-throttling/docker-compose.yml
- shotover-proxy/example-configs/docker-images/cassandra-4.0.6/Dockerfile
- shotover-proxy/example-configs/docker-images/cassandra-4.0.6/cassandra.yaml
- shotover-proxy/tests/test-configs/cassandra-passthrough-parse-request/docker-compose.yml
- shotover-proxy/tests/test-configs/cassandra-passthrough-parse-response/docker-compose.yml
- test-helpers/src/docker_compose.rs
On my machine it now takes 5s to startup the cassandra container instead of 80s.
I have not touched multi-instance integration tests because I dont think the same speedups are possible there.
I discovered the magic speedups here: https://github.com/saidbouras/cassandra-docker-unit/blob/master/scripts/setup-config.sh
Disabling gossiping is fine because its only a single instance.
Disabling virtual nodes is more iffy, but I figure its fine because the multi-instance clusters are still running with a proper virtual node setup.
It might still be worth investigating if there is anything we can do to speedup or skip gossiping on multi-instance clusters as every node starts with a complete list of seeds.
But we would want to be very careful that it doesnt alter post-setup functionality from what …
> Create custom cassandra image for single instance integration tests

- test-helpers/src/docker_compose.rs
I believe this was left over from times when DockerCompose was less robust.
If CI passes lets get rid of it.
> Remove 1s sleep in DockerCompose::drop

- shotover-proxy/example-configs/cassandra-cluster-multi-rack/docker-compose.yml
- shotover-proxy/example-configs/cassandra-cluster-tls/docker-compose.yml
- shotover-proxy/example-configs/cassandra-cluster/docker-compose-cassandra-v3.yml
- shotover-proxy/example-configs/cassandra-cluster/docker-compose-cassandra-v4.yml
- shotover-proxy/example-configs/cassandra-passthrough/docker-compose.yml
- shotover-proxy/example-configs/cassandra-protect-aws/docker-compose.yml
- shotover-proxy/example-configs/cassandra-protect-local/docker-compose.yml
- shotover-proxy/example-configs/cassandra-redis-cache/docker-compose.yml
- shotover-proxy/example-configs/cassandra-request-throttling/docker-compose.yml
- shotover-proxy/example-configs/cassandra-tls/docker-compose.yml
- shotover-proxy/tests/test-configs/cassandra-passthrough-parse-request/docker-compose.yml
- shotover-proxy/tests/test-configs/cassandra-passthrough-parse-response/docker-compose.yml
- shotover-proxy/tests/test-configs/cassandra-peers-rewrite/docker-compose-3.11-cassandra.yaml
- shotover-proxy/tests/test-configs/cassandra-peers-rewrite/docker-compose-4.0-cassandra.yaml
closes: https://github.com/shotover/shotover-proxy/issues/826
I did also investigate redis but from my testing disabling writing to disk didnt observably improve performance so I figured we were better leaving it with the default config.
On my local machine this PR cuts ~10s off each integration test that runs `standard_test_suite`
> docker-compose: Store cassandra db in tmpfs

- shotover-proxy/example-configs/cassandra-passthrough/topology-encode.yaml
- shotover-proxy/src/transforms/debug/force_parse.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
I wanted a way to better test the encoding code path of changes like: https://github.com/shotover/shotover-proxy/pull/802
So I added this integration test which will exercise the encoding code path against all of our cassandra test cases.
> cassandra_int_tests add case that forces cassandra message encoding

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/tests/cassandra_int_tests/cluster_multi_rack.rs
- shotover-proxy/tests/cassandra_int_tests/cluster_single_rack_v3.rs
- shotover-proxy/tests/cassandra_int_tests/cluster_single_rack_v4.rs
rpc_address is a field in system.peers but not system.peers_v2
Driver's often still use system.peers instead of system.peers_v2 for routing.
So this field turned out to actually be important but we were just setting it to null.
As expected I had to change rpc_address fields in the integration tests.
However I also had to change the system.local listen_address in cluster_multi_rack, I assume that this change is now allowing the driver to properly route between multiple shotover instances resulting in different listen_address values.
> CassandraSinkCluster: Fix system.peers rpc_address

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/topology.rs
- shotover-proxy/tests/cassandra_int_tests/cluster.rs
Closes https://github.com/shotover/shotover-proxy/issues/730
This PR ensures that all existing connections receive all changes to the topology tasks node list.
Previously a new connection had to be made to observe the changes to the node list.
It also simplies code in a few places that had to rely on loop+sleep to wait for changes to occur, now we can just await on the recv call.
renames:
* topology_task_nodes -> nodes_rx - we are now using a receiver type so we use the standard rx naming, `nodes_rx` also pairs nicely to the `nodes` field to which it is copied.
* local_nodes -> nodes - the `local` part no longer makes sense now that we are using a Receiver, additionally local could be confused with the `local_shotover_node` field.
I originally attempted to implement this with an enum that …
> CassandraSinkCluster: Keep node list up to date via a tokio::watcher

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/src/transforms/redis/cache.rs
It appears to have been used by mistake instead of tracing
> Remove tracing_log dep

- shotover-proxy/src/transforms/cassandra/connection.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node.rs
I need these to investigate an ambiguous error
> Improve Cassandra new connection errors

- shotover-proxy/benches/benches/cassandra.rs
- shotover-proxy/benches/benches/redis.rs
The fields of a struct are dropped in the order that they are defined: https://stackoverflow.com/questions/41053542/forcing-the-order-in-which-struct-fields-are-dropped
Reordering the BenchResources fields such that we drop the `ShotoverManager` before we drop the `DockerCompose` avoids errors like the following from being logged:
```
2022-10-13T02:14:52.562355Z ERROR connection{id=4 source="CassandraSource"}: shotover_proxy::transforms::cassandra::connection: tx_process task terminated
Caused by:
channel closed
2022-10-13T02:14:52.562396Z ERROR connection{id=4 source="CassandraSource"}: shotover_proxy::server: connection was unexpectedly terminated
Caused by:
0: chain failed to send and/or receive messages
1: channel closed
```
> Fix BenchResources drop order

- shotover-proxy/example-configs/docker-images/cassandra-3.11.13/cassandra.yaml
- shotover-proxy/example-configs/docker-images/cassandra-4.0.6/cassandra.yaml
- shotover-proxy/example-configs/docker-images/cassandra-tls-4.0.6/cassandra.yaml
- shotover-proxy/tests/cassandra_int_tests/cluster_multi_rack.rs
- shotover-proxy/tests/cassandra_int_tests/cluster_single_rack_v3.rs
- shotover-proxy/tests/cassandra_int_tests/cluster_single_rack_v4.rs
Fixes warnings like:
```
1665705034.217 [WARN] (host.cpp:151:void datastax::internal::core::Host::set(const datastax::internal::core::Row*, bool)): Found host with 'bind any' for rpc_address; using listen_address (127.0.0.1) to contact instead. If this is incorrect you should configure a specific interface for rpc_address on the server.
```
that get logged every time a new connection is made with cassandra_cpp.
Looking at the comments above the `rpc_address: localhost` I can see that the default setting is actually invalid.
Setting localhost results in an rpc_address of 0.0.0.0 which the comment explicitly calls out as invalid.
The comment also says that leaving out the setting entirely will make it just do the right thing of setting rpc_address to the nodes ip address, so that is what I …
> Fix cassandra_cpp rpc_address warning

- shotover-proxy/tests/cassandra_int_tests/cluster_single_rack_v4.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/helpers/cassandra.rs
test_events_filtering is renamed to test_node_going_down and extended to test that shotover can continue to process incoming messages after a node goes down.
Currently this only tests connections created after a node goes down as that is all that shotover currently handles.
But I have added TODO's to test connections created before a node goes down for once shotover does handle that.
I also made the event assertions more robust by handling the `StatusChangeType::Up` event that can occur by reordering the test cases.
> cassandra_int_tests: add test_node_going_down

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
By default this field is 0.0.0.0, in that case no mapping is required as 0.0.0.0 is valid no matter what our ip is.
However if a cassandra node does have rpc_address configured properly, then we would be leaking internal cluster ip addresses by not remapping it.
So this PR maps it to shotovers ip address.
Its also worth noting that rpc_address IS the field used to set the address where the client connects to, despite `rpc` making it sound like it has to do with the old thrift stuff.
The old name is just kept for legacy reasons.
> CassandraSinkCluster: rewrite rpc_address

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/benches/benches/chain.rs
- shotover-proxy/benches/benches/codec.rs
- shotover-proxy/src/codec/cassandra.rs
- shotover-proxy/src/frame/cassandra.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/transforms/cassandra/peers_rewrite.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/topology.rs
- shotover-proxy/tests/cassandra_int_tests/cluster.rs
- shotover-proxy/tests/helpers/cassandra.rs
Pre-reqs:
- https://github.com/Metaswitch/cassandra-rs/pull/147 Enables setting the tracing flag in `cassandra-cpp`
- https://github.com/krojew/cdrs-tokio/pull/118 Fixes parsing of flags in `cassandra-protocol`
At the moment Shotover is just stripping flags from messages. This PR implements support for flags. Currently this PR just tests we can send flags without error, but the followup: #854 uses this support to get tracing information from queries sent through Shotover.
> Cassandra flags

- shotover-proxy/tests/helpers/cassandra.rs
Not ready for review until the cassandra_cpp changes are upstreamed: 
Cassandra cpp logs to the log crate which is mapped to tracing via tracing-log.
tracing-log is internally initialized by tracing-subscriber.
The cassandra_cpp logs are now:
* in the standard output format the rest of our logs are in
* more compact
* filterable by tracing filters.
screenshot:
> Route cassandra_cpp logs -> log -> tracing

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node_pool.rs
Previously shotover would give up if the node it tried to use for its control connection was down.
Now it sequentially attempts all other nodes it knows about until it either runs out of nodes reporting an error or makes a successful connection.
An error is returned if no successful connections could be made:
A warning is emitted if any failures occur but a successful connection could still be made in the end.
> control connection creation error handling

- shotover-proxy/src/tls.rs
I originally intended on upstreaming these formatting improvements but my PR was rejected.
With some extra boilerplate we can make use of them here though.
Previously our TLS errors looked like this:
With this PR they look like this:
I've chosen to keep the library and file name in the output because TLS errors can still be quite cryptic and it can at least give us a clue in those scenarios.
> Map upstream tls errors into a better format

- rust-toolchain.toml
- shotover-proxy/src/lib.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/protect/mod.rs
I decided to disable the new `clippy::bool_to_int_with_if` lint as IMO it makes the code less clear, as its not obvious what integer values correspond to true/false.
Happy to enable it if people disagree though.
> Update to rust 1.65

- shotover-proxy/src/config/topology.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
Using {} instead of {:?} was preventing the full error chain from being logged.
Also replaced some custom string formatting with anyhow context method.
> fix redis error reporting

- shotover-proxy/src/lib.rs
- shotover-proxy/src/tcp.rs
- shotover-proxy/src/transforms/cassandra/connection.rs
- shotover-proxy/src/transforms/redis/mod.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
- shotover-proxy/src/transforms/util/cluster_connection_pool.rs
- shotover-proxy/src/transforms/util/mod.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
prereq to https://github.com/shotover/shotover-proxy/pull/899
Every connection needs this same basic error handling so we should move it into a helper to give us consistent error messages and to ensure we never forget to implement the timeout.
It will also allow us to call this logic from within the tls connector in 899.
> Refactor TCP connection logic

- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/helpers/cassandra.rs
Finish implementing the Scylla driver test helpers and add it to the test suite.
> Scylla Driver Tests

- shotover-proxy/example-configs/cassandra-cluster-tls/topology.yaml
- shotover-proxy/example-configs/cassandra-tls/topology-with-key.yaml
- shotover-proxy/example-configs/cassandra-tls/topology.yaml
- shotover-proxy/example-configs/redis-cluster-tls/topology-with-key.yaml
- shotover-proxy/example-configs/redis-cluster-tls/topology.yaml
- shotover-proxy/example-configs/redis-tls/topology.yaml
- shotover-proxy/src/tls.rs
- shotover-proxy/src/transforms/cassandra/connection.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
- shotover-proxy/src/transforms/util/cluster_connection_pool.rs
- shotover-proxy/tests/cassandra_int_tests/cluster/mod.rs
- shotover-proxy/tests/helpers/mod.rs
- shotover-proxy/tests/redis_int_tests/mod.rs
Theres a few things going on here:
* TlsConnector::connect now creates its own TcpStream - this enforces that the hostname is derived from the address.
* All cluster examples have verify_hostname disabled because clusters rely on ip address communication and openssl hostname verification will fail verification on IP addresses (it only allows domain names)
> TLS: Use destination as hostname instead of hardcoded localhost

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/tests/cassandra_int_tests/prepared_statements.rs
- shotover-proxy/tests/helpers/cassandra.rs
prepared_statements now takes a list of values which can be of any cassandra supported type. This will allow for better test coverage.
I will follow this up with a PR that adds a test case which tests every cassandra type in prepared statements.
> refactor prepared_statements helper

- shotover-proxy/src/transforms/cassandra/sink_cluster/topology.rs
We already have a log like this in the per connection control connection.
An example use case of this log is identifying when issues are caused due to the topology task control connection destination going down undetected.
> topology task info! on init complete

- shotover-proxy/example-configs/cassandra-cluster-v4/docker-compose.yaml
- shotover-proxy/example-configs/docker-images/cassandra-3.11.13/cassandra.yaml
- shotover-proxy/example-configs/docker-images/cassandra-4.0.6/cassandra.yaml
- shotover-proxy/example-configs/docker-images/cassandra-tls-4.0.6/cassandra.yaml
- shotover-proxy/src/transforms/cassandra/sink_cluster/node_pool.rs
- shotover-proxy/tests/cassandra_int_tests/cluster/single_rack_v4.rs
- test-helpers/src/docker_compose.rs
Prereq: https://github.com/shotover/shotover-proxy/pull/917
Instead of changing tmpfs to volume, we could make a separate cassandra-cluster-v4/docker-compose.yaml for persistent tests but it doesn't seem worth it yet.
The `cassandra.yaml` changes are needed to make the cassandra nodes persistent on restart, not sure why they fix the problem but I have verified that they do not cause any regressions in test runtime.
The new integration test discovered a bug in `node_pool.rs` where we were accidentally copying over dead connections, so this PR fixes that as well.
> cassandra_int_tests test node up

- shotover-proxy/src/server.rs
- shotover-proxy/src/sources/cassandra_source.rs
- shotover-proxy/src/sources/redis_source.rs
- shotover-proxy/src/transforms/coalesce.rs
- shotover-proxy/src/transforms/load_balance.rs
Bunch of things that were bothering me while working on other PRs.
* server.rs comments are left over from when it was copied from a tokio example.
* tests should unwrap rather than returning errors.
* `tokio::spawn` is internally just `Handle::current().spawn`
> misc cleanup

- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/cassandra_int_tests/timestamp.rs
- shotover-proxy/tests/helpers/cassandra.rs
Timestamps in Cassandra can be included in the query parameters or inside the CQL. We test that they are supported in Shotover by sending a query with a timestamp included and test that this matches the last written timestamp on the row's column.
> Timestamp tests

- shotover-proxy/example-configs/cassandra-cluster-v4/topology.yaml
- shotover-proxy/src/frame/cassandra.rs
- shotover-proxy/tests/cassandra_int_tests/prepared_statements_simple.rs
closes https://github.com/shotover/shotover-proxy/issues/905
I originally thought this would be more involved because I thought the encode logic needed to special case NO_METADATA just like we do for decoding.
But it turns out that the standard implementation for encoding null and bytes data types works just fine with the null and bytes types that we generate for NO_METADATA decoding.
To prove this I added `DebugForceEncode` to cassandra-cluster-v4.
I think its fine to add this to an existing test because we have the very similar cassandra-cluster-multi-rack test case which will test CassandraSinkCluster without the DebugForceEncode.
> Implement proper NO_METADATA support for cassandra protocol

- shotover-proxy/examples/cassandra_bench.rs
- shotover-proxy/tests/runner/runner_int_tests.rs
- test-helpers/src/shotover_process.rs
The constructor name now matches and adding `--quiet` hides the fact that the cargo is used to run the executable.
i.e. The test logs are no longer spammed with:
```
Finished dev [unoptimized + debuginfo] target(s) in 0.13s
Running `/home/rukai2/Projects/Crates/shotover/shotover-proxy/target/debug/shotover-proxy -t example-configs/cassandra-passthrough/topology.yaml`
```
> Make ShotoverProcess API a bit more similar to ShotoverManager

- shotover-proxy/src/server.rs
- shotover-proxy/tests/runner/observability_int_tests.rs
Previously we were shutting down the base chain from which all real chains are cloned from.
That was pretty pointless because messages are never sent down that chain.
This PR has two fixes:
* We keep track of active connections and wait for them to shutdown before killing the tokio runtime. (the join_all in shutdown())
* We send the flush message in every connection when the connection is terminated.
> Fix connection shutdown logic

- shotover-proxy/src/transforms/cassandra/connection.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node_pool.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/topology.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/tests/cassandra_int_tests/cluster/single_rack_v4.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
Changes:
* prereq PR - https://github.com/shotover/shotover-proxy/pull/943
* cassandra errors that are generated in response to internal shotover errors are now `Overloaded` errors instead of `Server` errors. This is needed because the cassandra_cpp drivers will terminate the connection on `Server` errors but will allow the user to retry a failed message when `Overloaded` occurs.
* The cassandra connection abstraction is refactored to allow for error handling:
+ Internal errors are now returned as a ResponseError instead of silently being converted to a cassandra error message.
+ The ResponseError contains the connections destination allowing the transform to recreated dead connections
+ The stream_id is only required in the case of errors allowing us to replace the Response struct with a …
> Fix connections with no messages sent during node outage

- shotover-proxy/src/transforms/chain.rs
- shotover-proxy/src/transforms/mod.rs
The dangerous line is `let mut chain: Vec<_> = self.chain.iter().cloned().rev().collect();` in `transforms/chain.rs`.
This causes pushed messages to be run against a clone of the transforms so any state set when processing pushed messages is lost.
Currently I'm not aware of any bugs this has caused but its clearly dangerous.
This PR should also be a nice speedup for pushed messages as we no longer need to clone every transform for every message.
Performance for regular messages will not be affected in any meaningful way, just an extra branch per transform.
> Do not clone transforms when running chain in reverse

- shotover-proxy/benches/benches/chain.rs
- shotover-proxy/src/transforms/chain.rs
- shotover-proxy/src/transforms/load_balance.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/parallel_map.rs
- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/src/transforms/sampler.rs
~~prereq: https://github.com/shotover/shotover-proxy/pull/960~~
Many transforms have kept their Clone implementation as they need it to act as their `build()` implementation for now.
This PR just removes Clone from the Transforms enum and then fixes any compiler issues brought about from that.
> Remove Clone from Transforms enum

- Cargo.lock
- shotover-proxy/tests/cassandra_int_tests/cluster/single_rack_v4.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/helpers/cassandra.rs
closes https://github.com/shotover/shotover-proxy/issues/958
The issue was caused by a bug in cdrs-tokio which I have submitted upstream here:  https://github.com/krojew/cdrs-tokio/pull/136
As a bonus we were able to remove some sleeps we previously needed, taking about ~40s (4*10s) off our total test runtime.
> Fix intermittent failure when using cdrs driver

- Cargo.lock
- Cargo.toml
- shotover-proxy/examples/cassandra_bench.rs
- shotover-proxy/src/runner.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/runner/runner_int_tests.rs
- test-helpers/src/lib.rs
- test-helpers/src/shotover_process.rs
- tokio-bin-process/Cargo.toml
- tokio-bin-process/build.rs
- tokio-bin-process/src/event.rs
- tokio-bin-process/src/event_matcher.rs
- tokio-bin-process/src/lib.rs
- tokio-bin-process/src/process.rs
The goal of this PR is to allow making assertions on what tracing events occur during integration tests.
At first I wanted to do this with ShotoverManager by routing tracing events directly into a Vec.
However after thinking about it I realized there were a lot of advantages to instead using ShotoverProcess for this.
* events are isolated within each shotover instance so we can e.g. assert that each shotover instance logs the same error once.
* more accurate shotover usage:
* Shotover is gauranteed to shutdown when ShotoverProcess is dropped. Currently ShotoverManager still leaves tasks and resources alive after it is dropped.
* No risk of cross contamination of state (e.g. global values) between running shotover instances and test logic
* No API hacks, particularly at startup time, we …
> Give ShotoverProcess powerful event assertions by parsing JSON events

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
prereq: https://github.com/shotover/rust-cql3-parser/pull/36
Makes use of the soon to be added `IdentifierRef` and `FQNameRef` types to avoid allocating when creating a value just for comparison purposes.
I also changed every `Unquoted` to a `Quoted` because that will avoid an allocation within the `partial_eq` implementation.
> Avoid allocating for table name comparisons

- .github/workflows/build_and_test.yaml
- .gitignore
- shotover-proxy/examples/cassandra_bench.rs
- shotover-proxy/examples/cassandra_cluster_bench.rs
- shotover-proxy/examples/cassandra_cluster_flamegraph.rs
- test-helpers/src/bench.rs
- test-helpers/src/latte.rs
- test-helpers/src/lib.rs
The original idea behind the `cassandra_bench` example was to be able to run any existing docker-compose.yaml/topology.yaml pair from an example or test as a benchmark.
However that didnt end up working out because tests often have unique topologies, addresses and ports.
Its also a pain to use because you have to figure out how to specify the path to config that it wants.
So im moving our latte based benchmarks to use an example per bench.
To achieve this I've moved our latte wrapper into test-helpers so it can be shared amongst each example.
There are 2 new benches:
* cassandra_cluster_flamegraph
- I created the shotover instance only after the db init has finished, this ensures we arent profiling shotover while its idle.
- I also set the rate to 10,000,000, in order to max out the load. …
> Add cassandra cluster bench

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
We currently have two methods of sending extra messages needed by the CassandraSinkCluster transform:
1. the TableToRewrite system - messages are inserted into the main list and kept track of via a list of `TableToRewrite`s
2. sending to a unique FuturesOrdered - a unique FuturesOrdered is created for every set of messages that need to be send and then processed seperately from the main list
Currently the 2nd approach is never implemented correctly, we only have a single FuturesOrdered for each type of message that needs one, so for example all prepared messages end up in the same FuturesOrdered despite needing to be processed seperately.
The 1st system is more powerful in that it allows the original message that spawned the extra messages to be modified.
Currently this is used to …
> CassandraSinkCluster: make prepared results handling robust

- shotover-proxy/benches/benches/chain.rs
- shotover-proxy/src/codec/cassandra.rs
- shotover-proxy/src/frame/cassandra.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/transforms/redis/cache.rs
Brings the 7% time spent on decode down to 4% in the flamegraph.
The cassandra-protocol implementation of frame encoding allocates and copies all over the place: https://github.com/krojew/cdrs-tokio/blob/08814fec99190d0d79b72d1c472cb05044191946/cassandra-protocol/src/frame.rs#L237
It would be nice to upstream these improvements some time, but the cassandra-protocol implementation has a lot of complexity that we dont need, so reimplementing isnt so bad.
the TODO is a further improvement left undone on purpose to keep scope down, it causes no regression in performance or functionality.
> Optimize cassandra encoding

- shotover-proxy/tests/redis_int_tests/mod.rs
We now get all the advantages of ShotoverProcess for our redis integration tests.
> redis_int_tests: replace ShotoverManager with ShotoverProcess

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node_pool.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/test_router.rs
PreparedMetadata contains a bunch of allocating fields we dont actually use like `col_specs` and `global_table_spec.table_name`.
So I created a cut down version of PreparedMetadata to save 2 clones of these unused allocations.
This saves ~0.5% in the flamegraph but this would have an even larger affect when the col_specs field has more complicated values in it.
> Avoid cloning prepared metadata fields

- Cargo.lock
- shotover-proxy/example-configs/cassandra-cluster-v4/topology-encode.yaml
- shotover-proxy/examples/cassandra_cluster_flamegraph.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- test-helpers/Cargo.toml
- test-helpers/src/flamegraph.rs
- test-helpers/src/lib.rs
run `cargo run --release --example cassandra_cluster_flamegraph` to generate a flamegraph of CassandraSinkCluster under load.
It also leaves the generated perf.data around so the user can inspect it however they choose.
To get more accurate results for the flamegraph I moved the DebugForceEncode out of the default cluster topology and into a seperate topology.
> Add flamegraph generation to flamegraph example

- shotover-proxy/src/frame/cassandra.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
`RawCassandraFrame` copies the entire body into a newly allocated vec.
We dont use that at all in metadata so we can get a nice win by just reading the bytes we need directly off the buffer.
Before this change, metadata shows up as taking 0.8% on the flamegraph afterwards its just 0.1%
Previously we included tracing in our metadata however:
* All the use cases of it were actually incorrect, if a client requests tracing and we return an error then the best we can do is just return no tracing.
* tracing is part of the body which can be compressed, so implementing reading of tracing robustly would be very costly.
So I removed it
> Optimize cassandra metadata

- shotover-proxy/src/server.rs
- shotover-proxy/src/transforms/chain.rs
- shotover-proxy/tests/runner/observability_int_tests.rs
Because the registered shotover_chain_latency metric cant specify the client ip it ends up as a separate metric that is always `0` which is quite confusing.
e.g.
```
shotover_chain_latency{chain="example_chain",quantile="0"} 0
shotover_chain_latency{chain="example_chain",quantile="0.5"} 0
shotover_chain_latency{chain="example_chain",quantile="0.9"} 0
shotover_chain_latency{chain="example_chain",quantile="0.95"} 0
shotover_chain_latency{chain="example_chain",quantile="0.99"} 0
shotover_chain_latency{chain="example_chain",quantile="0.999"} 0
shotover_chain_latency{chain="example_chain",quantile="1"} 0
shotover_chain_latency_sum{chain="example_chain"} 0
shotover_chain_latency_count{chain="example_chain"} 0
shotover_chain_latency{chain="example_chain",client_details="127.0.0.1",quantile="0"} …
```
> Fix empty shotover_chain_latency metric

- shotover-proxy/benches/benches/cassandra.rs
- shotover-proxy/benches/benches/main.rs
- shotover-proxy/benches/benches/redis.rs
- test-helpers/src/shotover_process.rs
requires a bit of fiddling with tokio runtimes as criterion does not have great support for tokio.
> benches: replace ShotoverManager with ShotoverProcess

- shotover-proxy/tests/cassandra_int_tests/cluster/mod.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- test-helpers/src/shotover_process.rs
- tokio-bin-process/src/process.rs
BinProcess was adjusted to take a log_name that gets included in the log output, replacing the previously hardcoded BINPROCESS log prefix.
This means when we run:
`cargo test cluster_multi_rack --all-features -- --nocapture`
we get output like:
```
Rack3      02:13:31.963028Z  INFO connection{id=4 source="CassandraSource"}: shotover_proxy::transforms::cassandra::sink_cluster: Control connection finalized against node at: 172.16.1.4:9042
Rack1      02:13:32.053064Z  INFO connection{id=14 source="CassandraSource"}: shotover_proxy::transforms::cassandra::sink_cluster: Control connection finalized against node at: 172.16.1.2:9042
Rack2      02:13:32.097153Z  INFO connection{id=5 source="CassandraSource"}: shotover_proxy::transforms::cassandra::sink_cluster: Control connection finalized …
```
> ShotoverManager -> ShotoverProcess in cassandra_int_tests::cluster_multi_rack

- shotover-proxy/benches/benches/chain.rs
- shotover-proxy/src/transforms/cassandra/peers_rewrite.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/src/transforms/coalesce.rs
- shotover-proxy/src/transforms/debug/force_parse.rs
- shotover-proxy/src/transforms/debug/returner.rs
- shotover-proxy/src/transforms/distributed/consistent_scatter.rs
- shotover-proxy/src/transforms/filter.rs
- shotover-proxy/src/transforms/load_balance.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/parallel_map.rs
- shotover-proxy/src/transforms/protect/mod.rs
- shotover-proxy/src/transforms/query_counter.rs
- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/src/transforms/redis/cluster_ports_rewrite.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
- shotover-proxy/src/transforms/tee.rs
- shotover-proxy/src/transforms/throttling.rs
It now returns a builder rather than the transform itself so a rename is in order.
Also cleaned up some outdated comments.
> rename TransformConfig::get_transform -> TransformConfig::get_builder

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/chain.rs
- shotover-proxy/src/transforms/load_balance.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/parallel_map.rs
- shotover-proxy/src/transforms/redis/cache.rs
I think that semantically it makes a bit more sense to have a single build method that generates a transform, rather than cloning the builder and then building a transform by destroying the builder.
There should also be some performance improvements:
* Avoids having the two step process of clone -> build, this results in a bunch of extra copying on the stack which I doubt the compiler can optimize away because the structures are so deeply nested. (copies on the heap are unchanged because they only get copied during the clone)
* There are cases where we call `TransformChainBuilder::build(&self)` in a transform builder which results in needless internal clones due to taking an `&self`
> TransformBuilder::build takes &self intead of self

- shotover-proxy/src/transforms/mod.rs
We talked about removing this 2 years ago but still to this day no transforms use it and the chain never calls it.
So I think its time to remove it.
If the transform needs this functionality they can very easily implement it themselves by storing their state in an Option or using a boolean flag, which is IMO easier to reason about for transform authors than yet another function to implement.
> remove Transform::_prep_transform_chain

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node_pool.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/test_router.rs
NodePoolBuilder matches the abstractions and naming used by CassandraSinkClusterBuilder. We no longer have a custom clone impl responsible for deciding which values are shared between transform instances.
unit tests no longer rely on a unit test specific code path (`NodePath::new` with a prepopulated vec), they now follow the same path to set the node list as the real code does (`NodePath::update_nodes`)
> Move NodePool custom clone into a NodePoolBuilder

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node_pool.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/test_router.rs
- shotover-proxy/tests/cassandra_int_tests/cluster/multi_rack.rs
My understanding of our routing model is:
Cassandra tokens are unique per cassandra instance, replicas are determined by proceeding to the next token along the token ring.
Shotover instances report their token list as the list of all tokens in their rack.
The client should then see this and always route to a shotover instance that contains the destination replica node in its rack by just performing token aware routing.
From there shotover just needs to find the correct destination node in its rack via token aware routing and it will have routed directly to a replica node that exists within its rack.
Following this model, the warning I have added should only occur according to the reasons listed in the warning.
I think its reasonable to report for the first reason, shotover is now routing …
> Add counter for when CassandraSinkCluster routes execute message outside of rack

- shotover-proxy/benches/benches/chain.rs
- shotover-proxy/src/frame/mod.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/transforms/coalesce.rs
- shotover-proxy/src/transforms/query_counter.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
I think this was originally intended to mean "null" of redis frame but it's prevalence has gone beyond the scope of that. We can just use `RedisFrame::Null`.
> remove Frame::None

- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/transforms/distributed/consistent_scatter.rs
- shotover-proxy/src/transforms/filter.rs
- shotover-proxy/src/transforms/null.rs
- shotover-proxy/src/transforms/tee.rs
- shotover-proxy/tests/transforms/tee.rs
clears out 2 TODO's from message/mod.rs
to_error_response now properly sets the redis `Error Prefix` to ERR as documented here: https://redis.io/docs/reference/protocol-spec/
We could also just not do that, but we were previously doing that only sometimes (to_filtered_reply), now we always do it. 
I think that changing the method to return a new Message instead of modifying the original Message gives us a more flexible API, with no performance loss.
> Message::set_error -> Message::to_error_response

- shotover-proxy/benches/benches/codec.rs
- shotover-proxy/src/codec/cassandra.rs
- shotover-proxy/src/codec/kafka.rs
- shotover-proxy/src/codec/mod.rs
- shotover-proxy/src/codec/redis.rs
- shotover-proxy/src/server.rs
- shotover-proxy/src/sources/cassandra_source.rs
- shotover-proxy/src/transforms/cassandra/connection.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/src/transforms/util/cluster_connection_pool.rs
The Codec trait is replaced with a CodecBuilder trait.
This is used in all the server.rs level usage where codecs were passed around in order to clone more codecs off it.
Now we use the `.build()` method which will generate a encoder and decoder halves.
We could just have these encoder/decoder codecs as separate generic types in server.rs etc, but we instead use a builder as that reduces the generic soup and allows for sharing state between the decoder/encoder codec pairs like we want to do in https://github.com/shotover/shotover-proxy/pull/1021
RedisCodec is left pretty much as is, demonstrating that if we have a simple codec we can just use a single struct as the builder, decoder and encoder.
To demonstrate the actual functionality I have gone ahead and split up CassandraCodec into its …
> split codecs into builders, encoders and decoders

- shotover-proxy/src/codec/redis.rs
- shotover-proxy/src/frame/mod.rs
- shotover-proxy/src/frame/redis.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/sources/redis_source.rs
- shotover-proxy/src/transforms/redis/cluster_ports_rewrite.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
- shotover-proxy/src/transforms/redis/timestamp_tagging.rs
- shotover-proxy/src/transforms/util/cluster_connection_pool.rs
* the redis codec is now split into builder, encoder and decoder
* shotover-proxy/src/transforms/redis/sink_single.rs took a bit of fiddling with types as we now need to apply the codecs to the streams after splitting instead of before.
* `fn redis_query_type` is moved into a new frame/redis.rs module, as it is not related to the codec at all.
> Split redis codec

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/src/codec/cassandra.rs
- shotover-proxy/src/codec/kafka.rs
- shotover-proxy/src/codec/mod.rs
- shotover-proxy/src/frame/kafka.rs
- shotover-proxy/src/frame/mod.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/sources/kafka.rs
- shotover-proxy/src/transforms/kafka/sink_single.rs
- shotover-proxy/src/transforms/query_counter.rs
- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/test-configs/kafka/passthrough/topology-encode.yaml
as per my [writeup](https://github.com/shotover/shotover-proxy/issues/1006#issuecomment-1437669604), this PR gives an initial protocol implementation that we can start with.
I have no idea what the performance is like internally in the `kafka-protocol` crate but the code in the PR itself tries to be performant.
The spec does not give a good overview, so I'll give a quick one.
Every kafka message consists of: `size header` -> `message header` -> `message body`
* size header: every message starts with this simple header https://kafka.apache.org/protocol.html#protocol_common
* message header: A different header is used depending on if its a request or response - https://kafka.apache.org/protocol.html#protocol_messages
* message body: A different format is used depending on if its a request …
> Initial kafka protocol

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
Extend kafka integration test to also consume messages instead of just produce them.
> kafka_int_tests test consuming

- shotover-proxy/benches/benches/cassandra.rs
- shotover-proxy/tests/cassandra_int_tests/cluster/single_rack_v4.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/cassandra_int_tests/routing.rs
- shotover-proxy/tests/examples/mod.rs
- test-helpers/src/connection/cassandra.rs
Now that we have a bunch of different config options for the `CassandraConnection` helper it makes sense to use the builder pattern. This will make testing different combinations of protocol versions, compression and TLS easier.
> CassandraConnectionBuilder

- shotover-proxy/src/frame/kafka.rs
- shotover-proxy/src/transforms/kafka/sink_single.rs
KafkaSinkSingle works by having a shotover instance sit on the same address as every kafka instance.
The kafka instances all use one consistent port for communication to the client and shotover uses another consistent port for communication to the client.
It is up to shotover to rewrite any messages that refer to the kafka port to instead refer to the shotover port.
FindCoordinator is one such message, it contains ip address + ports of other kafka brokers that are acting as a coordinator
So this PR introduces parsing and rewriting of these messages which fixes our issue of the client connecting directly to kafka.
You can observe more messages are now flowing through shotover by setting the `tracing::debug`s to `tracing::info` in `codec/kafka.rs`
The hardcoded header versions were too high …
> Implement FindCoordinator rewriting (fixes clients connecting directly to kafka)

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/benches/benches/chain.rs
- shotover-proxy/src/config/topology.rs
- shotover-proxy/src/transforms/cassandra/peers_rewrite.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/src/transforms/chain.rs
- shotover-proxy/src/transforms/coalesce.rs
- shotover-proxy/src/transforms/debug/force_parse.rs
- shotover-proxy/src/transforms/debug/printer.rs
- shotover-proxy/src/transforms/debug/returner.rs
- shotover-proxy/src/transforms/distributed/consistent_scatter.rs
- shotover-proxy/src/transforms/filter.rs
- shotover-proxy/src/transforms/kafka/sink_single.rs
- shotover-proxy/src/transforms/load_balance.rs
- shotover-proxy/src/transforms/loopback.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/null.rs
- shotover-proxy/src/transforms/parallel_map.rs
- shotover-proxy/src/transforms/protect/mod.rs
- shotover-proxy/src/transforms/query_counter.rs
- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/src/transforms/redis/cluster_ports_rewrite.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
- shotover-proxy/src/transforms/redis/timestamp_tagging.rs
- shotover-proxy/src/transforms/tee.rs
- shotover-proxy/src/transforms/throttling.rs
closes: https://github.com/shotover/shotover-proxy/issues/951
There are 3 stages to a transform: config, builder and transform
Currently we use seperate enums to represent all 3, I am experimenting with changing all of these enums into traits so that we can provide shotover as a library for purposes of users implementing their own transforms.
In this PR I have changed just TransformBuilder into a trait.
I skipped the other enums for now because:
* The transforms themselves are performance sensitive so I wanted to be careful changing them to dynamic dispatch.
* The configs are complicated to make into a trait due to needing to be deserialized via serde.
So this left TransformBuilder as a good, non-controversial, first step because:
It lacks the previously mentioned downsides and making …
> Make TransformBuilder a trait

- shotover-proxy/src/transforms/tee.rs
This PR:
* avoids invalid states by storing the chain in the ConsistencyBehavior enum itself
* avoids cloning the mismatch chain config into every built tee
To achieve this a unique ConsistencyBehavior enum was created for every stage of the transform
> Avoid storing ConsistencyBehaviour::SubchainOnMismatch config in the final tee transform

- shotover-proxy/src/config/mod.rs
- shotover-proxy/src/config/topology.rs
- shotover-proxy/src/main.rs
- shotover-proxy/src/runner.rs
- shotover-proxy/tests/runner/runner_int_tests.rs
- shotover-proxy/tests/test-configs/invalid_non_terminating_last.yaml
- shotover-proxy/tests/test-configs/invalid_terminating_not_last.yaml
closes https://github.com/shotover/shotover-proxy/issues/993
In order to get tracing at this point we just spin up our own runtime and tracing logger.
Technically these functions are fallible but they shouldnt ever fail and if they do somehow fail we still output the issue to stdout in some form which isnt any worse than before.
This resolves the problem described in the issue and gives consistency of error messages to `--log-format human` users and gives parseable output to `--log-format json` users.
`std::process::exit(1);` may seem dodgy but:
* clap already does it internally when the user gives invalid cli args
* and there is no other way to return a nonzero exit code without also outputting to stdout
> emit startup failures through tracing

- shotover-proxy/src/config/topology.rs
- shotover-proxy/src/transforms/cassandra/peers_rewrite.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/src/transforms/coalesce.rs
- shotover-proxy/src/transforms/debug/force_parse.rs
- shotover-proxy/src/transforms/debug/returner.rs
- shotover-proxy/src/transforms/distributed/consistent_scatter.rs
- shotover-proxy/src/transforms/filter.rs
- shotover-proxy/src/transforms/kafka/sink_single.rs
- shotover-proxy/src/transforms/load_balance.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/parallel_map.rs
- shotover-proxy/src/transforms/protect/mod.rs
- shotover-proxy/src/transforms/query_counter.rs
- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/src/transforms/redis/cluster_ports_rewrite.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
- shotover-proxy/src/transforms/tee.rs
- shotover-proxy/src/transforms/throttling.rs
After various refactors this is no longer needed
> Remove clone from TransformsConfig

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/src/frame/kafka.rs
closes https://github.com/shotover/shotover-proxy/issues/1056
I managed to upstream the logic for converting an api version to a header version.
Refer to https://github.com/tychedelia/kafka-protocol-rs/pull/21 and https://github.com/tychedelia/kafka-protocol-rs/pull/22 for more info.
In order to avoid manually parsing the api_key and api_version we should one day upstream some wrappers to kafka-protocol-rs that does this for us.
For now we can land this PR as it fixes our header version issue.
> Kafka: fix flexible version handling

- shotover-proxy/benches/benches/codec.rs
- shotover-proxy/src/codec/cassandra.rs
- shotover-proxy/src/codec/kafka.rs
- shotover-proxy/src/codec/mod.rs
- shotover-proxy/src/codec/redis.rs
- shotover-proxy/src/sources/cassandra_source.rs
- shotover-proxy/src/sources/kafka.rs
- shotover-proxy/src/sources/redis_source.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/src/transforms/kafka/sink_single.rs
- shotover-proxy/src/transforms/redis/cluster_ports_rewrite.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
- shotover-proxy/src/transforms/util/cluster_connection_pool.rs
Pulled this out of #1065. Found it pretty difficult to read the debugging logs with all the concurrent connections and figure out what messages paired up without this change.
> codec direction logging

- shotover-proxy/src/config/topology.rs
- shotover-proxy/src/runner.rs
* `from_yaml` was used by a test but it could just as easily use the standard `from_file` so I just replaced it
* TopologyConfig and Topology have the exact same fields so there is no point in keeping the separation anymore (they used to have different fields a long time ago)
> Topology building cleanup

- Cargo.lock
- rust-toolchain.toml
- shotover-proxy/Cargo.toml
- shotover-proxy/src/transforms/throttling.rs
1.68 adds `pin!` from pin-project-lite into the std lib.
I went to remove `pin-project-lite` and found that we werent actually making use of it anyway! :rofl: 
throttling.rs change is due to new clippy lint
Also note that you will want to configure the sparse protocol locally - https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html#cargos-sparse-protocol
We could check it into our repo level `.cargo/config` but it will be the default in a few releases anyway so lets just let developers set it themselves.
> Update to rust 1.68 🦀🦀🦀

- shotover-proxy/tests/cassandra_int_tests/mod.rs
- test-helpers/src/shotover_process.rs
Allows us to correctly configure shotover in integration tests with multiple shotover instances.
Previously we had to tell BinProcess to ignore the resulting error.
Generating config for this is not ideal, but we currently dont expose this as a CLI flag, and I dont want to block this improvement on figuring out what our CLI/config.yaml split should look like.
> Add ShotoverProcessBuilder::with_observability_address

- shotover-proxy/src/frame/kafka.rs
Drastically improves usefulness of error.
Previously:
```
shotover   00:08:06.689555Z ERROR connection{id=3 source="KafkaSource"}: shotover_proxy::server: failed to send or encode message: EncodeError
```
Now:
```
shotover   00:21:14.715015Z ERROR connection{id=2 source="KafkaSource"}: shotover_proxy::server: failed to send or encode message: Failed to encode kafka_protocol::messages::find_coordinator_response::FindCoordinatorResponse v4 body
Caused by:
EncodeError
```
Matches the format of error given for a decode error.
> Improve kafka encode error

- shotover-proxy/src/codec/kafka.rs
Ooopsies we had the `>=` flipped.
It was working most of the time because most of the time `size == `src.len()`
But when we actually had an incomplete message on the buffer it panicked trying to read past the end of the buffer instead of waiting for the rest of the message to come through.
> Another kafka fix

- shotover-proxy/src/transforms/kafka/sink_single.rs
The problem was that the encoder expects protocols >= 4 to have all the removed fields set to 0 (or equivalent default value)
We were just setting all the port fields regardless of version causing the encoder to return an error when a modern protocol was used.
Now we only set the port fields that are actually available in the specific version of the message.
You can verify this fixes the issue by simultaneously running these scripts that come with kafka against `test-configs/kafka/passthrough/topology.yaml`:
```
kafka-console-producer.sh  --topic foo --bootstrap-server 127.0.0.1:9192
```
and 
```
kafka-console-consumer.sh --topic foo --bootstrap-server 127.0.0.1:9192
```
Then sending a message through the producer and observing it appear in the consumer.
Before this fix, we would hit the …
> Fix invalid modifications to FindCoordinator responses

- docs/src/transforms.md
- shotover-proxy/example-configs/redis-multi/topology.yaml
- shotover-proxy/src/config/topology.rs
- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/transforms/distributed/mod.rs
- shotover-proxy/src/transforms/distributed/tuneable_consistency_scatter.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/redis/timestamp_tagging.rs
- shotover-proxy/tests/runner/runner_int_tests.rs
- shotover-proxy/tests/test-configs/invalid_subchains.yaml
Through looking at some [history](https://github.com/shotover/shotover-proxy/blob/a15ae9fbd67ef8df89bafdaa3b7344da811c95d1/src/transforms/distributed/tunable_consistency_scatter.rs) it seems it used to be sometimes referred to as TuneableConsistencyScatter or TunableConsistency but in an attempted cleanup it was all changed to ConsistentScatter which is misleading because the scatter is not neccessarily consistent but is instead configured with varying levels of consistency.
This PR sets all instances of the name to TuneableConsistencyScatter
> rename ConsistentScatter -> TuneableConsistencyScatter

- shotover-proxy/src/message/mod.rs
- shotover-proxy/src/server.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
- shotover-proxy/tests/redis_int_tests/mod.rs
I think this is useful for the reasons I wrote about in the code comment.
However it does come at a performance cost - there is now one extra allocation per incoming message batch. (just for the vec, the `Message`s themselves do not allocate)
I still think its worth it though.
An easy way to test this new handling is to run a shotover config without a database running at the destination address.
> Return error message to client when chain fails to send/receive

- shotover-proxy/src/transforms/distributed/tuneable_consistency_scatter.rs
Now that I better understand TuneableConsistencyScatter this fix was pretty easy to put together, if I hit many more problems I will abandon it.
This PR is an attempt to fix this test failure I saw on CI:
```
shotover   04:43:36.664124Z  INFO shotover_proxy::runner: Starting Shotover 0.1.9
shotover   04:43:36.664157Z  INFO shotover_proxy::runner: configuration=Config { main_log_level: "info,shotover_proxy=info", observability_interface: "0.0.0.0:9001" }
shotover   04:43:36.664164Z  INFO shotover_proxy::runner: topology=Topology { sources: {"redis_prod": Redis(RedisConfig { listen_addr: "127.0.0.1:6379", connection_limit: None, hard_connection_limit: None, tls: None, timeout: None })}, chain_config: {"redis_chain": [TuneableConsistencyScatter(TuneableConsistencyScatterConfig { route_map: …
```
> TuneableConsistencyScatter: filter out errors

- test-helpers/src/docker_compose.rs
Fixes a small regression introduced by https://github.com/shotover/shotover-proxy/pull/1070
Before 1070 we were running docker-compose against the docker-compose.yaml before we ran `DockerCompose::get_service_to_image`.
This ensured that we ran all of docker-compose's validation against the docker-compose.yaml, ensuring that we had a valid docker-compose.yaml for when our parser with poor error handling attempts to read it .
This PR restores a similar logic by moving `clean_up` before `get_service_to_image`.
You can verify the effect of this PR by breaking a docker-compose.yaml file and then running its test.
> Improve docker-compose.yaml validation with this one small trick

- shotover-proxy/examples/kafka_bench.rs
- shotover-proxy/examples/kafka_flamegraph.rs
- test-helpers/src/kafka_producer_perf_test.rs
- test-helpers/src/latte.rs
- test-helpers/src/lib.rs
Adds benchmarks for kafka using the `kafka-producer-perf-test.sh` script that comes with kafka.
The results of `kafka_bench.rs` is that shotover has the same throughput as a direct connection:
```
shotover-proxy〉cargo run --release --example kafka_bench
Compiling test-helpers v0.1.0 (/home/rukai2/Projects/Crates/shotover/shotover-proxy/test-helpers)
Compiling shotover-proxy v0.1.9 (/home/rukai2/Projects/Crates/shotover/shotover-proxy/shotover-proxy)
Finished release [optimized] target(s) in 22.04s
Running `target/release/examples/kafka_bench`
shotover   01:21:27.856420Z  INFO shotover_proxy::runner: Starting Shotover 0.1.9
shotover   01:21:27.856442Z  INFO shotover_proxy::runner: configuration=Config { main_log_level: "info,shotover_proxy=info", observability_interface: "0.0.0.0:9001" } …
```
> Add benchmarks for kafka

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/benches/benches/cassandra.rs
- test-helpers/Cargo.toml
- test-helpers/src/connection/cassandra.rs
changelog: https://github.com/Metaswitch/cassandra-rs#new-session-api-version-20
We only use this library for integration tests so as long as the tests still pass we should be good.
The main things for us are the removal of `stmt!` and removal of legacy non-async APIs.
This ended up needing fairly invasive changes for our cassandra benches as they were storing `Statement`s for reuse which is no longer possible.
This should have minimal affect on benchmark results as recreating the statements each round of the bench only introduces one extra allocation per round. (which is nothing compared to the entirety of shotover+cassandra on the other side)
> Update to cassandra-cpp 2.0.0

- shotover-proxy/src/transforms/cassandra/connection.rs
We now generate the message from `self` instead of `self.cause`, using `self.cause` was skipping the error formatting specified by `#[error("Connection to destination cassandra node {destination} was closed: {cause:?}")]`
Additionally:
* we just use `{}` instead of `{:#}` because thiserror includes everything on the default formatter.
* we use `{cause:?}` instead of `{cause}` because anyhow needs the Debug formatter to include everything.
> Fix cassandra ResponseError formatting

- shotover-proxy/Cargo.toml
- shotover-proxy/benches/benches/cassandra.rs
- shotover-proxy/benches/benches/main.rs
* The rand `small_rng` feature is needed by shotover itself so we move that from dev-dependencies into a regular dependency
+ Previously this was working because the features are supposed to be additive so the dev-dep enabling the feature meant that cargo could just use the same feature set for shotover itself as well.
* Previously we entirely disabled benchmarks if cassandra-cpp was disabled, this has been changed to now only disable cassandra benchmarks if cassandra-cpp is disabled.
> a few dep fixes

- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node_pool.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/test_router.rs
It is easier to understand the error type if we add an extra error variant instead of nesting an extra Option in there.
> CassandraSinkCluster improve get_replica_node_in_dc error type

- shotover-proxy/src/transforms/cassandra/connection.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/node.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/topology.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/tests/cassandra_int_tests/cluster/single_rack_v4.rs
By making the `CassandraConnection::send` return the rx rather than take the tx, the API becomes much more ergonomic to work with.
There is value in having abstractions that take the tx or rx for more flexibility.
But in practice we always create a new tx/rx pair just before sending, so we dont get any value from that flexibility.
> CassandraConnection::send returns rx channel

- shotover-proxy/tests/cassandra_int_tests/mod.rs
Add tests for protocol v4 and v5, which will be enabled once v5 PR is merged.
There is a bug in our v3 handling, which the failing test demonstrates. I'll comment out that test and open an issue for it before merging.
> Protocol tests

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/benches/benches/chain.rs
- shotover-proxy/src/config/chain.rs
- shotover-proxy/src/config/mod.rs
- shotover-proxy/src/config/topology.rs
- shotover-proxy/src/lib.rs
- shotover-proxy/src/transforms/cassandra/peers_rewrite.rs
- shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs
- shotover-proxy/src/transforms/cassandra/sink_single.rs
- shotover-proxy/src/transforms/coalesce.rs
- shotover-proxy/src/transforms/debug/force_parse.rs
- shotover-proxy/src/transforms/debug/printer.rs
- shotover-proxy/src/transforms/debug/returner.rs
- shotover-proxy/src/transforms/distributed/tuneable_consistency_scatter.rs
- shotover-proxy/src/transforms/filter.rs
- shotover-proxy/src/transforms/kafka/sink_single.rs
- shotover-proxy/src/transforms/load_balance.rs
- shotover-proxy/src/transforms/mod.rs
- shotover-proxy/src/transforms/null.rs
- shotover-proxy/src/transforms/parallel_map.rs
- shotover-proxy/src/transforms/protect/mod.rs
- shotover-proxy/src/transforms/query_counter.rs
- shotover-proxy/src/transforms/redis/cache.rs
- shotover-proxy/src/transforms/redis/cluster_ports_rewrite.rs
- shotover-proxy/src/transforms/redis/sink_cluster.rs
- shotover-proxy/src/transforms/redis/sink_single.rs
- shotover-proxy/src/transforms/redis/timestamp_tagging.rs
- shotover-proxy/src/transforms/tee.rs
- shotover-proxy/src/transforms/throttling.rs
To achieve this, we sprinkle in some dtolnay magic crates: 
* typetag - we will always need this to magically hook up our traits to serde
* async_trait - the rust team seem pretty intent on landing some form of async traits one day so we should eventually be able to remove this
And finally we need a custom deserialize implementation for our chain config.
The problem was that typetagged structs with no fields would not deserialize from a yaml string.
e.g.
this would fail to deserialize:
```
chain_config:
redis_chain:
- NullSink
```
but this would work fine:
```
chain_config:
redis_chain:
- NullSink: {}
```
I do not really understand what the `vec_transform_config` custom deserializer is doing, but it clearly does fix the issue, allowing us to write our config as `NullSink` instead of …
> Make TransformConfig into a trait

- shotover-proxy/src/main.rs
- shotover-proxy/tests/runner/runner_int_tests.rs
- shotover/src/runner.rs
To give custom transform users a nicer setup process.
List of changes:
* User no longer has to provide ConfigOpts
* The user no longer has to manually set `with_observability_interface`, this method was originally added as a hack for specific integration tests but that hack is no longer needed so the function can just be removed and the observability interface always enabled.
* `Runner::new()` now internally performs the backup tracing reporter logic that was previously in `shotover-proxy/src/main.rs`
* run_block now returns `!`
* `Runner` renamed to `Shotover` as from the users perspective that type is shotover.
We could have just done a single `run_shotover()` method but `Shotover::new().run_block()` adds barely any more complication and gives us room to expand without breaking changes …
> Cleanup shotover::Runner api

- test-helpers/src/cert.rs
The "127.0.0.1" was previously being treated as a DNS SAN, with this PR it is properly being treated as an ip address SAN.
> Fix SAN ip address in cert generation

- docs/src/source-types.md
- shotover-proxy/example-configs/cassandra-cluster-tls/topology.yaml
- shotover-proxy/example-configs/cassandra-tls/topology-with-key.yaml
- shotover-proxy/example-configs/cassandra-tls/topology.yaml
- shotover-proxy/example-configs/redis-tls/topology.yaml
- shotover/src/tls.rs
Turns out we never needed the CA when creating a TLS acceptor, the CA would only be used by an acceptor when we have enabled client auth (Usually just the client verifies who the server is, but with "client auth" the server also verifies who the client is)
I only noticed this because rustls API does not accept a CA for its TLS acceptor unless you explicitly enable client auth. (yay type safety :tada: )
I havent enabled client auth in this PR because I couldnt easily figure out how to do that in openssl but that will arrive in https://github.com/shotover/shotover-proxy/pull/1108
> make certificate_authority_path field optional in source TLS config

- Cargo.lock
- Cargo.toml
- custom-transforms-example/Cargo.toml
- custom-transforms-example/config/config.yaml
- custom-transforms-example/config/docker-compose.yaml
- custom-transforms-example/config/redis.conf
- custom-transforms-example/config/topology.yaml
- custom-transforms-example/src/main.rs
- custom-transforms-example/src/redis_get_rewrite.rs
- custom-transforms-example/tests/test.rs
- shotover/Cargo.toml
- shotover/src/transforms/mod.rs
- test-helpers/src/shotover_process.rs
- tokio-bin-process/src/process.rs
Implements custom transforms in the least invasive way possible: we simply add a single `Custom` variant to the `Transforms` enum, sidestepping any discussion about dynamic dispatch for internal transforms.
An example/integration test is provided at `custom-transforms-example`.
We could split redis_get_rewrite into its own crate like we did in the [demo](https://github.com/shotover/shotover-proxy/pull/1069) but I didnt do that in order to avoid adding extra noise to the root of the workspace for an example.
I would however like to create a demo that points at the crates.io version, in its own git repo, to act as a template. In that demo it would be good to demonstrate the crate split.
> Allow for custom transforms via using shotover as a crate

- custom-transforms-example/src/main.rs
- shotover/src/lib.rs
The custom-transform-example works fine because the custom transform is in the same crate as the shotover binary. (directly included via `mod redis_get_rewrite`)
However it is expected for users to want to have their transforms in a separate crate, this results in needing "magic" `use`s like this: https://github.com/shotover/shotover-examples/blob/01d9a877ee563d15dee0deed0831192d754fd0b4/custom-transforms/shotover-bin/src/main.rs#L4
So I've added this macro to make things a little less magic.
Ultimately this is all a bit hacky and I would like to replace it with a solution where we actually register types to be used by typetag, but will be very complicated and likely involve forking typetag so this is a good immediate solution.
Here is what the error looks like when the imported type is …
> add import_transform macro

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover/Cargo.toml
waiting on:
https://github.com/shotover/shotover-proxy/pull/1125
https://github.com/shotover/shotover-proxy/pull/1124
https://github.com/shotover/shotover-proxy/pull/1130
> Release shotover 0.1.10

- shotover-proxy/tests/test-configs/kafka/passthrough/docker-compose.yaml
- test-helpers/src/docker_compose.rs
This PR fixes a CI failure on main:
kraft is now enabled by default on the kafka images and I think the breakage was related to that, so I updated to latest and simplified our config and now it works again.
It was still working locally for me at first because the container was cached, but when I cleared the image docker pulled in a new one that reproduced the issue.
I've made our kafka image name more specific to avoid this issue in the future.
> Fix CI (bitnami/kafka had a breaking change)

- shotover/src/codec/cassandra.rs
- shotover/src/codec/kafka.rs
- shotover/src/codec/mod.rs
- shotover/src/codec/redis.rs
- shotover/src/server.rs
- shotover/src/transforms/redis/sink_single.rs
- shotover/src/transforms/util/cluster_connection_pool.rs
This fixes the kafka_int_test intermittent failure that has been plaguing us recently.
```
shotover   06:37:30.298481Z  INFO shotover::runner: Starting Shotover 0.1.10
shotover   06:37:30.298541Z  INFO shotover::runner: configuration=Config { main_log_level: "info,shotover_proxy=info", observability_interface: "0.0.0.0:9001" }
shotover   06:37:30.298574Z  INFO shotover::runner: topology=Topology { sources: {"kafka_source": Kafka(KafkaConfig { listen_addr: "127.0.0.1:9192", connection_limit: None, hard_connection_limit: None, tls: None, timeout: None })}, chain_config: {"main_chain": TransformChainConfig([DebugForceEncodeConfig { encode_requests: true, encode_responses: true }, KafkaSinkSingleConfig { address: "127.0.0.1:9092", connect_timeout_ms: 3000, read_timeout: None }])}, …
```
> Fix kafka intermittent failure

- shotover/src/codec/cassandra.rs
Lz4 compression replaces repeated occurrences of data with references to a single copy of that data existing earlier in the input - https://en.wikipedia.org/wiki/LZ77_and_LZ78#LZ77. The compressed size can be larger than the uncompressed in cases where there is random text without any repeating sequences. We should fallback to no compression when this occurs. This is how the java driver behaves: https://github.com/datastax/native-protocol/blob/78e62fd7c93afb2500c7db103f4bf7c9dfd6662d/src/main/java/com/datastax/oss/protocol/internal/SegmentCodec.java#L54
> fallback to no compression if compressed len is longer

- Cargo.lock
- shotover-proxy/tests/cassandra_int_tests/routing.rs
- test-helpers/Cargo.toml
- test-helpers/src/connection/cassandra.rs
scylla now sets the default consistency via an "execution profile" instead of directly on the "session builder".
The extra `match compression { .. }` seems like some kind of merge error so I just removed it
> Update scylla dep

- shotover-proxy/tests/test-configs/invalid_subchains.yaml
- shotover/src/config/topology.rs
- shotover/src/server.rs
- shotover/src/sources/cassandra.rs
- shotover/src/sources/kafka.rs
- shotover/src/sources/mod.rs
- shotover/src/sources/redis.rs
Cloning from a base TransformBuilder means that we duplicate any resources held behind TransformBuilder.
Currently this doesnt cause any issues for internal transforms, but custom transform users have reported issues due to using the builder as a point to introduce external resource construction/destruction.
So instead this PR changes it to construct a new builder for each source instead of cloning.
I had to change `shotover-proxy/tests/test-configs/invalid_subchains.yaml` to actually make use of each chain so that the validation is triggered.
This isnt ideal but there isnt a way around that.
The variables named chain were always ChainBuilder's I've just properly named them now.
> Avoid creating extra TransformBuilder instance

- shotover/src/message/mod.rs
- shotover/src/server.rs
- shotover/src/transforms/cassandra/sink_cluster/rewrite.rs
- shotover/src/transforms/distributed/tuneable_consistency_scatter.rs
- shotover/src/transforms/filter.rs
- shotover/src/transforms/null.rs
- shotover/src/transforms/tee.rs
There were two error cases in to_error_response that previously caused panics.
* Failing to parse metadata - this only affects cassandra but meant that an invalid cassandra message could cause shotover to panic, better to handle this as an Error.
* attempting to produce an error from a kafka message - previously this was just unimplemented, but in attempting to implement it I found it to be incredibly complex, and even when overcoming the complexity, the kafka driver we use didnt get any benefit from knowing about the error. So I just wrote up my findings in a comment and consider kafka error generation unsupported.
Both these cases now return an Error.
This was either causing noise or hiding actual errors when an internal error was returned from a kafka transform.
> Implement error handling for to_error_response

- Cargo.lock
- shotover-proxy/benches/benches/chain.rs
- shotover/Cargo.toml
- shotover/src/transforms/chain.rs
- shotover/src/transforms/distributed/tuneable_consistency_scatter.rs
- shotover/src/transforms/load_balance.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/parallel_map.rs
- shotover/src/transforms/redis/cache.rs
- shotover/src/transforms/sampler.rs
- shotover/src/transforms/tee.rs
When implementing a TransformBuilder its not clear what the semantics of your clone implementation should be.
This is even more problematic now since TransformBuilder is part of our custom transforms API.
The few remaining locations that rely on TransformBuilder having Clone can be quite easily adjusted to either separately create the builders from the config or share one builder via an Arc.
So lets just remove the clone requirement.
> Remove clone from TransformBuilder

- .github/workflows/build_and_test.yaml
- Cargo.lock
- windsock/Cargo.toml
- windsock/src/bench.rs
- windsock/src/cli.rs
- windsock/src/filter.rs
- windsock/src/lib.rs
- windsock/src/report.rs
- windsock/src/tables.rs
closes https://github.com/shotover/shotover-proxy/issues/1153
This PR implements tag filtering for running benches (`[FILTER]`) and for displaying results (`--results-by-tag` and `--compare-by-tag`).
This PR provides the most common filter we need (a simple key/value match) and hooks it up to various locations that need a filter.
We can improve on the exact features we provide in our filtering later on but I do intend to keep it lean, maybe just a key level match that ignores the value?
This PR also improves some general error handling that was left in a poor state from the initial windsock PR.
The cli flags should be properly documented in `cargo run --release --example windsock -- --help`
```shell
cargo run --release --example windsock # run all benches
cargo run --release --example …
```
> windsock: Implement tag filtering

- windsock/src/bench.rs
- windsock/src/cli.rs
- windsock/src/lib.rs
- windsock/src/report.rs
- windsock/src/tables.rs
This provides an escape hatch for running windsock in debug mode.
An additional warning is provided in red text that a bench result came from a binary compiled in a non-release profile.
The motivation is faster compile times and better stacktraces while developing the benches and windsock itself
example output:
> windsock: add `--disable-release-safety-check`

- shotover-proxy/examples/windsock/cassandra.rs
- test-helpers/src/mock_cassandra.rs
Now that we are running cassandra mock within windsock we need to be more careful about cleanly shutting it down.
Currently we work around this in windsock by running cassandra mock benches last but that is hardly ideal.
It is impossible to kill a thread, instead we need to instruct the thread to finish processing by sending a shutdown message. (or in this case just setting a bool to true)
> Shutdown cassandra mock on handle drop

- windsock/src/report.rs
Turns out time units of measure dont go up by 1024 :joy:
> windsock: fix OPS calculation

- shotover-proxy/examples/windsock/cassandra.rs
- shotover-proxy/examples/windsock/kafka.rs
- windsock/examples/cassandra.rs
- windsock/readme.md
- windsock/src/bench.rs
- windsock/src/cli.rs
- windsock/src/lib.rs
- windsock/src/report.rs
- windsock/src/tables.rs
first step towards: https://github.com/shotover/shotover-proxy/issues/1166
No matter what complete solution we end up with there, the user will still want to be able to manually set the OPS somehow.
This PR introduces the first helper to be used within a windsock bench implementation: `BenchTask`
Previously it was purely up to the user to implement required bench logic.
I think this is a good starting point but we can pull logic in and out of BenchTask as we start using it.
I think that it is important that everything in BenchTask can also be done manually because some people will have specific needs that it cant meet.
Ignore the "Ops per sec" results in the screenshots, it is broken and will be fixed by: https://github.com/shotover/shotover-proxy/pull/1174
Instead refer to the "Ops each …
> windsock: add --operations-per-second flag

- shotover/src/server.rs
There are a few things going on here but no logic changes should have occurred in this PR.
1. our connection limiting logic was overly complicated because it was working around the lack of owned permits. Since then tokio has implemented [owned permits](https://docs.rs/tokio/latest/tokio/sync/struct.Semaphore.html#method.acquire_owned) so we should just use those instead. The now deleted comments did a pretty good job of explaining the workaround so you should refer to them.
2. I moved as much logic as possible out of the socket acceptor loop and into the Handle task. We want to be able to accept many connections quickly so the string generation and nodelay setting is better off occurring in the async task.
3. I combined the `conn_details` and `client_details` strings into a single string, …
> server.rs refactor

- .cargo/config.toml
- windsock/src/tables.rs
Previously the table row value format had no way to specify that no comparison should be made between two values.
This PR stores the value tuple in an Option (`Option<(f64, String, Goal)>`) allowing the comparison to be skipped for empty values.
Currently this only occurs on a rare edge case, when a bench reports less seconds than other benches.
But my true motivation is to support this functionality for the special pubsub table formatting that kafka will require.
I also threw in a cargo alias for windsock because its so handy.
Now we can just `cargo windsock; cargo windsock --results-by-tag "" ` to run every bench and display all the results in a table.
> windsock: allow empty rows

- shotover/src/server.rs
When the read/write tasks close while the chain is running the out_tx ends up closed at this point.
We should just cleanly shutdown the handler instead of returning an error.
This now matches the handling when in_rx is closed, which also cleanly shutsdown the Handler
> server.rs close Handler when out_tx is closed

- windsock/src/report.rs
- windsock/src/tables.rs
* The Ops abbreviation was ambiguous between OPS (operations per second) and Ops (Operations), so I've changed it to Opns
* The percentile strings dont need the left padding as they are right aligned
* The column name generation changes `.map(|x| x.tags.0.get(&key).cloned().unwrap_or("".to_owned()))` fixes a panic when a bench is missing a tag of the same key that another bench has.
+ This allows us to do, `cargo run --release --example windsock; cargo run --release --example windsock -- --results-by-tags ""` to run all benches and put them all in a table. Previously this would panic.
+ In the screenshot below those cases can be seen as the empty tag value cells.
> windsock: misc report/table improvements

- shotover/src/transforms/cassandra/sink_cluster/mod.rs
- shotover/src/transforms/cassandra/sink_cluster/node_pool.rs
The result to a prepare query in Cassandra has no `pk_indexes`: https://github.com/apache/cassandra/blob/2ff1ad4788a1e29b99f81f75b2966b7951ba8250/doc/native_protocol_v3.spec#L638
This was added in v4: https://github.com/apache/cassandra/blob/2ff1ad4788a1e29b99f81f75b2966b7951ba8250/doc/native_protocol_v4.spec#L1204
This means we aren't routing v3 execute requests properly and actually never had the ability to do so which is unfortunate but we should at least not be blowing up when it happens.
> routing bug fix

- shotover-proxy/examples/windsock/cassandra.rs
- windsock/src/bench.rs
- windsock/src/lib.rs
its a little unfinished, some things to do later on are:
* control cassandra instance thread count - docker provides a way to do this but will need to pass arbitrary values into the docker-compose.yaml
* scale thread usage according to hardware core count.
But I want to land this now so we can start setting kafka and cassandra thread usage separately.
This PR should not change any performance numbers as I am setting all the thread counts to the same values that were previously used by default.
> windsock: basic thread count control

- .github/workflows/build_and_test.yaml
- .github/workflows/windsock_benches.yaml
This doesnt actually bring down our total CI runtime on a clean build as it was not in the slowest workflow.
However splitting it up does mean that:
* Intermittent failures can be more quickly rerun
* We more quickly get feedback about a failure that occurred on a PR.
> Split windsock into its own GA workflow

- shotover/src/frame/kafka.rs
- shotover/src/frame/mod.rs
This PR improves the KafkaFrame Display implementation so that DebugPrinter gives cleaner output:
The only change is to cleanup the header which was previously really noisy, the body remains unchanged.
> Improve kafka support for DebugPrinter

- shotover/src/transforms/mod.rs
Allows quickly debugging including high level message representations in debug logs when debugging transforms.
For example now we can just write:
```rust
tracing::error!("messages: {}", message_wrapper.messages_to_high_level_string());
```
Instead of:
```rust
tracing::error!(
"messages: {}",
message_wrapper.
.messages
.iter_mut()
.map(|x| x.to_high_level_string())
.collect::<Vec<_>>()
);
```
Starting the method name with `messages_` means that the method will be suggested when the user writes: 
`tracing::error!("messages: {}", message_wrapper.messages`
> add message_to_high_level_string debug helper

- shotover-proxy/tests/test-configs/log-to-file/docker-compose.yaml
- shotover-proxy/tests/test-configs/log-to-file/topology.yaml
- shotover-proxy/tests/transforms/log_to_file.rs
- shotover-proxy/tests/transforms/mod.rs
- shotover/src/codec/cassandra.rs
- shotover/src/codec/kafka.rs
- shotover/src/codec/redis.rs
- shotover/src/message/mod.rs
- shotover/src/transforms/debug/log_to_file.rs
- shotover/src/transforms/debug/mod.rs
- shotover/src/transforms/mod.rs
A usecase I have in mind is extracting messages for the purposes of benchmarking parsing/encoding.
I think it could also be useful for debugging.
Each incoming connection to shotover results in a new numbered directory created in `message-log`.
Within those directories is a `request` and `response` directory in which messages are logged to disk under a `messageN.bin` name.
The easiest way to see what the log looks like is to comment out `std::fs::remove_dir_all("message-log").unwrap();` in `log_to_file` integration test and run it.
The comment:
```rust
// TODO: Considering we already have the expected message type here maybe we should perform any required conversions and return a Result<Bytes> here.
// I've left it as is to keep the PR simpler and there could be a need for codecs to …
```
> Add DebugLogToFile transform

- shotover-proxy/benches/benches/redis.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
- shotover-proxy/tests/redis_int_tests/mod.rs
- shotover-proxy/tests/runner/observability_int_tests.rs
- shotover-proxy/tests/test-configs/redis-tls/topology.yaml
- shotover-proxy/tests/transforms/log_to_file.rs
- test-helpers/src/connection/cassandra.rs
- test-helpers/src/connection/redis_connection.rs
- test-helpers/src/lib.rs
I believe that this has been unneeded since moving to tokio-bin-process as that has logic that will wait until shotover is ready to accept connections.
It is causing issues with TLS tests because it forces us to provide a non TLS connection which in turn gets accidentally used by other parts of the test.
I've resolved the issues with the TLS tests by using a connection_creator to ensure TLS tests always create their connections in TLS.
I believe the change to the metrics test occurred because the connection close was triggering a chain flush which runs the chain and triggers the new shotover_chain_latency metrics.
Now those same metrics appear delayed because the chain is not run until the first message is received.
I removed the TLS redis benches because they were completely broken and …
> Remove wait_for_socket_to_open test helper

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/examples/windsock/common.rs
- shotover-proxy/examples/windsock/main.rs
- shotover-proxy/examples/windsock/redis.rs
- shotover-proxy/tests/redis_int_tests/mod.rs
- shotover-proxy/tests/test-configs/redis-cluster-hiding/topology-encode.yaml
- shotover-proxy/tests/test-configs/redis-cluster-tls/topology-encode.yaml
- shotover-proxy/tests/test-configs/redis-cluster-tls/topology-no-source-encryption.yaml
- shotover-proxy/tests/test-configs/redis-passthrough/topology-encode.yaml
- shotover-proxy/tests/test-configs/redis-tls/topology-encode.yaml
- test-helpers/src/cert.rs
The redis benches largely follows the same structure as the cassandra benches.
I introduced a new redis driver (fred) because the `redis` crate is harder to drive from a benchmark due to requiring `&mut T` access to the driver to send a message. Fred however only requires `&T` to send messages making it easy to send messages from many tasks.
We might be able to wrap the redis crate in an MPSC receiving tokio task but it smelt like trouble so I just went with fred for now.
Might be worth doing a full comparison of the two crates one day but for now lets just land with fred.
Because there are so many bench combinations for redis I opted to use `itertools::iproduct` which conor discovered would be useful for generating all possible combinations of benches.
The results seem quite consistent, …
> windsock: add redis benches

- custom-transforms-example/tests/test.rs
- shotover/src/config/topology.rs
- shotover/src/server.rs
- test-helpers/src/docker_compose.rs
- test-helpers/src/shotover_process.rs
closes https://github.com/shotover/shotover-proxy/issues/1201
This PR should fix the intermittent failure described in the issue.
I removed the `shotover   00:07:04.851460Z  INFO shotover::config::topology: Loaded sources [["redis_prod"]] and linked to chains` log because it wasnt conveying any information that wasnt already conveyed.
We already know which sources we are loading due to previous logs and now the "Shotover is now accepting inbound connections" log tells us that the sources are finished loading.
I've removed the with_target from the wait event matcher to make it more robust to changing modules which is an implementation detail.
The wait event matcher is internal to our testing but I also expect it to get copied around when users test custom transforms.
> Fix accepting inbound connections log

- shotover/src/config/topology.rs
- shotover/src/sources/cassandra.rs
- shotover/src/sources/kafka.rs
- shotover/src/sources/mod.rs
- shotover/src/sources/redis.rs
The correct naming scheme for an enum is to not use plurals as it represents a single instance.
plurals *would* be used to, for example, name a vector of that enum.
> Rename Sources -> Source

- windsock/src/filter.rs
Demonstration of usage:
Redis benches support `shotover=none`, `shotover=standard` and `shotover=message-parsed`.
By specifying `shotover=standard|none` we include `shotover=none` and `shotover=standard` benches but exclude `shotover=message-parsed` benches.
The `|` syntax makes sense to me, its often as an "or" in the form of `||` and it also feels like its separating multiple possible values.
An alternate approach would be allowing `shotover=none shotover=standard`.
That would involve less special syntax but I think the `|` syntax is better as this approach would mess up the semantics of each key=value pair making the filter more specific.
Under this approach some key=value pairs would make the filter less specific.
> windsock: filter: match any of multiple values

- shotover/src/transforms/cassandra/sink_cluster/mod.rs
- shotover/src/transforms/cassandra/sink_cluster/node.rs
A few simplifications where we call `context` directly instead of going through map_err.
Also fixed up an old comment that was talking about things that no longer exist.
But the actual point of this PR is to include in the control connection error whether we were using the node pool or the initial contact points.
> CassandraSinkCluster: minor error reporting improvement

- shotover/Cargo.toml
- test-helpers/Cargo.toml
As evidenced by https://github.com/shotover/tokio-bin-process/pull/15 this field can prevent clippy lints from triggering and there is no point in keeping it because we do not commit to any kind of MSRV guarantee.
The rust version specified in rust-toolchain.toml is of course untouched.
> remove rust-version field

- Cargo.lock
- deny.toml
- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover-proxy/tests/test-configs/kafka/cluster-fake/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-fake/topology.yaml
- shotover-proxy/tests/test-configs/kafka/cluster/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster/topology-single.yaml
- shotover-proxy/tests/test-configs/kafka/cluster/topology1.yaml
- shotover-proxy/tests/test-configs/kafka/cluster/topology2.yaml
- shotover-proxy/tests/test-configs/kafka/cluster/topology3.yaml
- shotover/Cargo.toml
- shotover/src/frame/kafka.rs
- shotover/src/transforms/kafka/common.rs
- shotover/src/transforms/kafka/mod.rs
- shotover/src/transforms/kafka/sink_cluster.rs
- shotover/src/transforms/mod.rs
Completes the first chunk of work listed in https://github.com/shotover/shotover-proxy/issues/1214
Because the transform lacks routing it can only be used with a 1 node kafka cluster.
This still brings some value as we can host shotover on a different IP which KafkaSinkSingle does not allow.
The logic in the new `send_requests` method has been pulled out of the two sinks.
Introduces the xxhash-rust crate under the BSL license which should pose no issue as its just a more lenient version of the MIT license.
> Initial KafkaSinkCluster

- .github/workflows/windsock_benches.yaml
- .gitignore
- Cargo.toml
- shotover-proxy/examples/windsock/cassandra.rs
- shotover-proxy/examples/windsock/kafka.rs
- shotover-proxy/examples/windsock/main.rs
- shotover-proxy/examples/windsock/profilers.rs
- shotover-proxy/examples/windsock/redis.rs
- test-helpers/src/flamegraph.rs
- test-helpers/src/shotover_process.rs
- windsock/examples/cassandra.rs
- windsock/src/bench.rs
- windsock/src/cli.rs
- windsock/src/data.rs
- windsock/src/lib.rs
- windsock/src/report.rs
Makes progress on https://github.com/shotover/shotover-proxy/issues/1177
This PR introduces:
* Allow benches to support many kinds of profilers not just generating a flamegraph
* Benches run shotover in the `profiling` cargo profile when doing a flamegraph, this is necessary to get a useful flamegraph result, but the pre-windsock benches just instructed the user to temporarily modify the release profile.
* Store profiler results in a unique directory per bench, allowing multiple flamegraphs to be collected in the same windsock run.
* Filter out benches that do not support the user requested profiler. Previously windsock would just panic when attempting to run every bench with flamegraph because some benches did not support it.
* Moved tokio-bin-process to a git dep, the next release is …
> windsock: rework profiler support

- shotover-proxy/examples/windsock/kafka.rs
- shotover-proxy/examples/windsock/main.rs
Going to use `iproduct` for the Cassandra ones too, so made sense to switch the Kafka ones over in a pre-req PR.
> use iproduct for kafka benches aswell

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover-proxy/tests/test-configs/kafka/cluster/docker-compose.yaml
- shotover/src/transforms/kafka/common.rs
- shotover/src/transforms/kafka/sink_cluster.rs
- shotover/src/transforms/kafka/sink_single.rs
progress towards: https://github.com/shotover/shotover-proxy/issues/1214
With this PR we are now able to send produce messages to the kafka cluster.
Previously, due to incorrect routing, produce messages would likely end up at the wrong instance and be rejected.
I added a temporary `produce_only` test case to test the part of the test suite that we can pass so far.
I had to rewrite `common::send_requests` into `common::produce_channel` because the KafkaSinkCluster ended up needing more control over this logic then I expected.
The KafkaSinkCluster routing works by reading metadata messages that the client sends and using them to build up an internal topology structure (The `nodes` and `topics` fields) which are later used for routing messages. This is pretty similar to what we do for …
> KafkaSinkCluster: implement produce routing

- shotover-proxy/examples/windsock/cassandra.rs
- shotover-proxy/examples/windsock/kafka.rs
- shotover-proxy/examples/windsock/redis.rs
- windsock/examples/cassandra.rs
- windsock/src/bench.rs
- windsock/src/cli.rs
- windsock/src/lib.rs
Just checking CI for now
Pulled out of https://github.com/shotover/shotover-proxy/pull/1232, refer to it for more context.
In order to allow running the bencher in CI we need to split up the orchestration logic (setup+teardown) and the bencher logic.
This pr achieves this by having the orchestration logic execute a second instance of the windsock executable that performs the actual benching.
In order to keep the local benchmarks as close as possible to the cloud benchmarks (to make local benchmarks a good way to debug cloud benchmarks), running a local benchmark executes a new windsock instance just like in the cloud.
The shotover bench implementations are largely the same, the previous `Bench::run` implementations split pretty cleanly into the new `Bench::run_bencher` and …
> windsock: windsock calls itself to run bencher

- shotover-proxy/examples/windsock/main.rs
- windsock/examples/cassandra.rs
- windsock/src/cli.rs
- windsock/src/cloud.rs
- windsock/src/lib.rs
Introduces the `--cleanup-cloud-resources` flag and routes it to the Cloud trait so the user can define how to cleanup their cloud resources.
refer to https://github.com/shotover/shotover-proxy/pull/1232 for more context
> windsock: add --cleanup-cloud-resources flag

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/build.rs
- shotover-proxy/examples/windsock/aws/cloud.rs
- shotover-proxy/examples/windsock/aws/mod.rs
- shotover-proxy/examples/windsock/common.rs
- shotover-proxy/examples/windsock/kafka.rs
- shotover-proxy/examples/windsock/main.rs
- shotover-proxy/examples/windsock/readme.md
- shotover-proxy/tests/test-configs/kafka/bench/topology-cloud.yaml
- shotover-proxy/tests/test-configs/kafka/bench/topology-encode-cloud.yaml
- test-helpers/src/docker_compose.rs
- windsock/src/bench.rs
- windsock/src/cli.rs
- windsock/src/lib.rs
- windsock/src/report.rs
Refer to the readme for how to setup credentials.
This PR enables the benches in `cargo windsock --cloud name=kafka size=1B` to run successfully in AWS.
Results from this command:
This PR contains the following changes:
* Completes cloud support in windsock
* Introduces aws abstractions
* Makes use of them to allow a subset of kafka benches to run in AWS.
If its preferred I could further split this PR into those 3 components, but I've kept them together since we wouldn't be able to individually test the 3 components.
AWS support for more benches will come in follow up PRs.
> windsock: add support for running some Kafka benches on AWS

- aws-throwaway/examples/aws-throwaway-test.rs
- aws-throwaway/examples/create-instance.rs
- aws-throwaway/src/lib.rs
- shotover-proxy/examples/windsock/aws/mod.rs
Allow setting the root volume size.
By default it is 8GB which is not large enough for our heavier kafka benchmarks.
The volume size is made configurable, all other fields use the default configuration.
> aws-throwaway: configurable volume size

- aws-throwaway/src/lib.rs
- aws-throwaway/src/ssh.rs
- shotover-proxy/examples/windsock/aws/mod.rs
- shotover-proxy/examples/windsock/cassandra.rs
- shotover-proxy/examples/windsock/kafka.rs
- shotover-proxy/tests/test-configs/cassandra/bench/topology-cloud.yaml
- shotover-proxy/tests/test-configs/cassandra/bench/topology-cluster-cloud.yaml
- shotover-proxy/tests/test-configs/cassandra/bench/topology-cluster-encode-cloud.yaml
- shotover-proxy/tests/test-configs/cassandra/bench/topology-encode-cloud.yaml
I started working on this because I wanted it to help review https://github.com/shotover/shotover-proxy/pull/1230
The command `cargo windsock --cloud "name=cassandra driver=scylla"` now succeeds.
The cdrs-tokio driver benches hangs for some reason, I will leave fixing that out of this PR.
I ran the benches, set as a baseline, and then ran again comparing against the first run:
Some of these results are quite noisy, I would like to investigate why in the future.
I upgraded the EC2 instance types from T2Micro to M6aLarge because I needed more ram for cassandra and I realized that M type instances are a lot better than T type for benchmarking since M has an entire cpu core to itself and wont have "bursting" messing with the results.
I added a timeout to docker container creation since it was …
> windsock: add support for cassandra benches on AWS

- docs/src/examples/redis-clustering-aware.md
- shotover-proxy/tests/test-configs/redis-cluster-auth/docker-compose.yaml
- shotover-proxy/tests/test-configs/redis-cluster-dr/docker-compose.yaml
- shotover-proxy/tests/test-configs/redis-cluster-handling/docker-compose.yaml
- shotover-proxy/tests/test-configs/redis-cluster-hiding/docker-compose.yaml
- shotover-proxy/tests/test-configs/redis-cluster-ports-rewrite/docker-compose.yaml
- shotover-proxy/tests/test-configs/redis-cluster-tls/docker-compose.yaml
- test-helpers/src/docker_compose.rs
This is a prereq to https://github.com/shotover/shotover-proxy/pull/1239
The current redis image we are on does not support arm64 which is preventing running tests on arm.
You can see what archs are supported here: https://hub.docker.com/r/bitnami/redis-cluster/tags
I remained on redis 6 instead of going to 7 to ensure we maintain compatibility with older versions.
> Update redis-cluster images from redis 6 to 7

- Cargo.lock
- aws-throwaway/Cargo.toml
- aws-throwaway/examples/create-instance.rs
- aws-throwaway/examples/ec2-cargo.rs
- aws-throwaway/src/ec2_instance.rs
This gives us an immediate win of being able to run shotover tests on arm.
But I also think this tool would be a good way to allow contributors without a local linux machine to run tests.
Currently it does the following:
1. Spins up an instance of the specified instance type
2. Installs everything needed for a shotover development environment on that instance.
3. Opens a custom shell for the user. Currently the shell just allows the following but we could add more later:
* test $args - runs cargo test $args on the repo
* ssh-instructions - print a bash snippet to directly ssh into the machine
* quit - terminates the application and cleans up all AWS resources
Currently it just does `git clone https://github.com/shotover/shotover-proxy`
But in a follow up PR it should be expanded to …
> Tool for running shotover tests in EC2 arm/x86

- Cargo.lock
- rust-toolchain.toml
- shotover-proxy/examples/windsock/redis.rs
- shotover/src/tls.rs
`with_single_cert` -> `with_client_auth_cert` change is because the former was deprecated.
> update rust version and deps

- .gitignore
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/test-configs/cassandra-cluster-tls/docker-compose.yaml
- shotover-proxy/tests/test-configs/cassandra-cluster-tls/topology.yaml
- shotover-proxy/tests/test-configs/cassandra-passthrough-websocket-tls/docker-compose.yaml
- shotover-proxy/tests/test-configs/cassandra-passthrough-websocket-tls/topology.yaml
- shotover-proxy/tests/test-configs/cassandra-tls/docker-compose.yaml
- shotover-proxy/tests/test-configs/cassandra-tls/topology-with-key.yaml
- shotover-proxy/tests/test-configs/cassandra-tls/topology.yaml
- shotover-proxy/tests/test-configs/docker-images/cassandra-tls-4.0.6/Dockerfile
- test-helpers/src/cert.rs
- test-helpers/src/docker_compose.rs
progress towards: https://github.com/shotover/shotover-proxy/issues/1246
as an end goal I want to either:
* stop building custom images and just specify everything we need directly within docker-compose (currently leaning towards this)
* build our custom images in a seperate repo and publish them to the docker registry
This PR is a prereq to both of those possibilities, and also just feels a bit more sane.
`std::fs::remove_file(path.join("keystore.p12")).ok();` is now needed because of some container weirdness:
It seems that the only way to include a file into a container instance is with a bind volume. (which is what we used here for the keystore)
However when a container modifies a file included via a bind volume, the actual file on the local host is modified.
In this case cassandra …
> shotover-int-tests/cassandra-tls: no longer embeds cert directly in image

- shotover-proxy/examples/windsock/cassandra.rs
- shotover-proxy/examples/windsock/kafka.rs
- shotover-proxy/examples/windsock/redis.rs
- windsock/examples/cassandra.rs
- windsock/readme.md
- windsock/src/bench.rs
- windsock/src/report.rs
- windsock/src/tables.rs
This PR implements:
* a method for benches to report the errors they encounter
* storage of error data in records
* display of error messages and error rates in result tables
For example `/aws-windsock.sh "name=kafka size=100KB" --cloud` can now successfully complete since the errors are handled instead of panicking windsock entirely:
To avoid error spam, recorded messages are capped to the first 5 unique error messages.
Once 6 unique errors occur a message is shown to indicate the list of messages is not complete.
> windsock: record and format error count and message

- docs/src/contributing.md
- ec2-cargo/src/main.rs
closes https://github.com/shotover/shotover-proxy/issues/1258
All of our clustered integration tests access containers directly by its IP in order to properly test clustering behavior across distinct addresses.
However this would fail on ec2-cargo instances because they were setup with rootless docker.
The problem is that rootless docker does not expose user created networks to the host so we cant access containers by IP.
This PR fixes that by replacing rootless docker with the root approach to docker.
Usually to allow the user access to docker, you would then add the user to the `docker` group.
But that would require restarting the ssh session which takes about 5 seconds.
So instead I setup docker as a script that runs actual docker with sudo.
This should be effectively the same.
> ec2-cargo: fix broken tests by using docker as root

- windsock/src/cli.rs
About time this got some cleanup.
This PR:
* improves the formatting
* adds two paragraphs beforehand to explain bench names and tag filters
* Improves wording/explanations in various cases.
Before:
After:
Without verbatim_doc_comment clap will strip all the custom formatting (newlines+whitespace)
> windsock: cleanup/improve --help output

- changelog.md
After spending a lot of time back and forth internally on an issue that was caused by us changing an API without documenting that change in an easily accessible place I have decided to introduce a changelog that we and users can refer to for information on such changes.
We already have the changelogs generated on releases such as https://github.com/shotover/shotover-proxy/releases/tag/v0.1.10 but they have so much noise from all the unrelated PRs and the PR descriptions are not directly useful when trying to upgrade to a new version or diagnose issues from an upgrade.
I think both systems can coexist, the automated changelogs are a complete list of every PR that went into the release while this changelog will be a hand curated reference to refer to when upgrading to new releases.
> Add user facing changelog

- shotover-proxy/examples/windsock/common.rs
- shotover-proxy/examples/windsock/redis.rs
- shotover/src/config/mod.rs
- shotover/src/config/topology.rs
- shotover/src/frame/kafka.rs
- shotover/src/observability/mod.rs
- shotover/src/tcp.rs
- shotover/src/tls.rs
- shotover/src/transforms/cassandra/sink_cluster/node_pool.rs
- shotover/src/transforms/debug/log_to_file.rs
- test-helpers/src/connection/redis_connection.rs
- windsock/src/tables.rs
Refactor all instances of
```rust
result.map_err(|e| e.context(format!("message {object:?}")))
```
into
```rust
result.with_context(|| format!("message {object:?}")))
```
This is just simpler to read/write.
And also refactor all instances of
```rust
result.context(format!("message {object:?"))
```
into
```rust
result.with_context(|| format!("message {object:?"))
```
This actually fixes a performance issue.
Sometimes its just in initialization code and doesnt really matter.
But there are other times where its in really hot code.
e.g. Our kafka codec should should get a nice performance improvement from this.
> with_context refactor

- shotover/src/transforms/kafka/sink_cluster.rs
Its been a while since I wrote this code and I can see now that its quite hard to understand.
This PR is an attempt to fix that by:
* rename `coordinator_broker_id` to `group_to_coordinator_broker`
+ it is a map so its important to convey what values maps to what.
* Swap to kafka-protocols newtype wrappers e.g. `StrBytes` -> `GroupId`, `StrBytes` -> `TopicName`, `i32` -> `BrokerId`
+ This improves type safety by ensuring that we cant mixup a group id with a topic name.
+ Also documents the purpose of the type making the code easier to understand.
+ Doesnt end up complicating things much at all since we were often extracting the inner StrBytes from the newtype only to reconstruct the newtype again later on when we passed the value back to `kafka-protocol`
* Pull large chunks of logic into …
> KafkaSinkCluster: refactor

- README.md
Now that shotover crate is published we can add badges to easily navigate to its documentation and crates.io page.
I removed the github actions badge because it points to a workflow that no longer exists and there is also not much need for a github actions badge as github already displays github actions directly in its UI.
> Add shotover crate badges to readme

- Cargo.lock
- shotover-proxy/examples/windsock/profilers/sar.rs
- windsock/Cargo.toml
- windsock/src/lib.rs
- windsock/src/report.rs
- windsock/src/tables.rs
Something I've been missing for a while now in windsock is the ability to record system usage metrics.
I can ssh into the instances and run htop but:
* That is a lot of manual setup for each benchmark run, making it infeasible when performing many bench runs which teardown and recreate ec2 instances for each run.
* I need to be able to view a log of system usage, its hard to analyze anything while it flys by on htop
* I need to be able to correlate system usage to particular benchmarks
* I need to be able to correlate system usage to per second benchmark results.
Being able to do those things will allow us to:
* Use changes in system usage metrics as another data point when evaluating shotover changes
* Evaluate how well our benchmarks are designed.
+ Allow us to track down the cause of …
> windsock: add sys monitor profiler - archive support

- .github/workflows/bench_run.yaml
- .github/workflows/build_and_test.yaml
- .github/workflows/windsock_benches.yaml
This PR:
* Improves cache utilization by:
+ fixing a bug in bench_run.yaml's cache key
+ changing windsock_benches.yaml and build_and_test.yaml to only allow main branch to write to cache
+ prevents main branch caches from being evicted in favor of a PR cache
+ saves about 1min per workflow by skipping the actual cache write (our caches are about 1GB atm, so it takes a while to zip all of that)
* bumps build_and_test concurrency from 8 jobs to 30 jobs.
+ I believe we are on the pro plan which gives us 40 concurrent jobs, so this leaves 10 jobs for all our other miscellaneous workflows. 
+ brings runtime of this workflow down from 35min to 30min
+ The overall CI runtime is still bottlenecked by windsock benches which takes 45mins but once …
> Improve GA config

- .github/workflows/build_and_test.yaml
- .github/workflows/windsock_benches.yaml
- windsock/src/cli.rs
- windsock/src/lib.rs
- windsock/src/list.rs
Move windsock CI testing into nextest to take advantage of its test sharding for huge CI runtime wins.
libtest is the default test harness used by cargo.
Custom test and benchmark frameworks can reimplement the libtest CLI API in order to be called by `cargo test`.
Both tests and benchmarks follow this same libtest API.
This allows benchmarks to be run as tests, when run as a test a benchmark usually only performs one iteration to complete the test run as quickly as possible.
nextest follows this same libtest API in order to call the default libtest api and any other test framework compatible with libtest.
But in order to support being run by nextest you only need to implement a small subset of libtest's API.
Since we dont use `cargo test` anymore, we can instead just target nextests's …
> windsock: nextest compatibility

- Cargo.lock
- Cargo.toml
- shotover-proxy/benches/windsock/cassandra.rs
- test-helpers/src/connection/cassandra.rs
- windsock/Cargo.toml
- windsock/examples/cassandra.rs
progress towards: https://github.com/shotover/shotover-proxy/issues/1274
We cant disable topology refresh but setting an absurdly long refresh interval is close enough.
This resolves the dip in OPS that can be observed in cassandra benches between 42-45s into the bench:
> scylla driver: disable topology refresh

- Cargo.toml
- rust-toolchain.toml
- shotover-proxy/benches/windsock/profilers/sar.rs
- shotover/src/transforms/redis/cache.rs
* into_iter removal was from new clippy lint
* `resolver = "2"` was needed to resolve a new cargo warning
* `sar.rs` formatting changes were needed because the new cargo fmt has now started formatting `let else` statements.
> Update to rust 1.72 🦀🦀🦀

- Cargo.lock
- shotover/Cargo.toml
- shotover/src/transforms/protect/aws_kms.rs
- shotover/src/transforms/protect/key_management.rs
- shotover/src/transforms/protect/mod.rs
Rusoto is unmaintained so we will need to upgrade to official SDK eventually.
Additionally we are already using the official sdk in windsock, so this will reduce our total dependencies.
I've avoided any cleanups or fixes in this PR, its entirely just swapping to aws-sdk-kms.
The official SDK is notoriously slow to compile so I did an investigation to see if our compile times would blow up making this switch. (e.g. aws-sdk-ec2 takes 2 minutes to compile on my machine)
The aws-sdk-kms is slower to compile than rusoto-kms by about 5s
However aws-sdk depends on rustls while rusoto depends on openssl.
Rustls compiles much faster than openssl so on a machine with plenty of cores we can start compiling shotover much earlier, more than making up for the lost time.
However on machines with few …
> Replace rusoto with official AWS SDK

- .github/workflows/build_and_test.yaml
This adds 2-5s to our CI runtime but in return we get visibility into disk usage when we need it.
Checking this in rather than just manually adding it when debugging failures is useful because we can go back over previous PRs to see how disk usage changed over time (for as long as github holds onto the CI logs)
> CI: give visibility into disk usage

- .github/workflows/build_and_test.yaml
`cargo install` uses a temp directory as its target folder and then deletes it when its finished, so there is no pollution due to intermediary build output.
However `cargo install` will download the source code to all the crates needed for the compilation into `.cargo/registry`, these are not deleted as they remain as a cache but many of those deps are unused by shotover so end up just wasting space.
So I've swapped `cargo-hack` to be installed via `install-action` which directly downloads a binary instead of compiling from source like `cargo install` does.
This should help reduce our disk usage and cache usage.
Not to mention this is also faster when CI is running uncached.
I've also taken the opportunity to add exact versions for these dependencies so that updates cannot break our CI. …
> Tweak CI disk usage

- shotover/src/runner.rs
pulled out of and continuing discussion from https://github.com/shotover/shotover-proxy/pull/1315#discussion_r1311109557
After enabling "show custom thread names" in htop (its [disabled by default](https://askubuntu.com/questions/987957/how-to-see-thread-name-in-htop)) we get output like this:
It looks truncated because linux does not support thread names that long.
This PR fixes the issue by using a shorter thread name.
It now looks like this:
While there could theoretically be some obscure case out there, at our current scale I dont believe this will cause any issues due to the change of name.
Scripts that invoke things like `killall shotover-proxy` will be unaffected because the main thread is still called `shotover-proxy`.
> fix tokio thread_name

- .github/workflows/windsock_benches.yaml
- shotover-proxy/benches/windsock/cassandra.rs
- shotover-proxy/benches/windsock/kafka.rs
- shotover-proxy/benches/windsock/profilers.rs
- shotover-proxy/benches/windsock/profilers/samply.rs
- shotover-proxy/benches/windsock/redis.rs
- shotover/src/runner.rs
Samply uses a custom rust sampling profiler and then displays the results in the firefox profiler UI.
The firefox profiler UI can display the results in a flamegraph and a few other formats.
I renamed the tokio thread names to `shotover-worker` as the previous name was so long it gets truncated on linux.
`cargo windsock --profilers samply --name kafka,shotover=message-parsed,size=100KB,topology=single`
Interactive: https://share.firefox.dev/47Vvy10
`cargo windsock --profilers flamegraph --name kafka,shotover=message-parsed,size=100KB,topology=single`
For some reason perf places TcpCodecListener in an `[unknown]` function apart from the rest of the tasks running in tokio.
However samply correctly places this in `tokio::runtime::scheduler::multi_thread::worker::Context::run` along with the …
> Add samply as a windsock profiler

- Cargo.lock
- shotover-proxy/Cargo.toml
- test-helpers/Cargo.toml
By setting cassandra-cpp to `default-features = false` and then manually adding back features we need, we can remove slog from our dep tree.
> Remove slog dep

- .github/workflows/windsock_benches.yaml
- Cargo.lock
- Cargo.toml
- test-helpers/src/shotover_process.rs
blocked on: https://github.com/shotover/tokio-bin-process/pull/22
`with_profile` should overwrite `with_bin`.
`with_bin` is a hint to `ShotoverProcessBuilder` that there is a precompiled binary available.
`with_profile` is demanding that we use a specific profile which has priority over `with_bin`.
This bug was causing windsock to profile shotover binaries not suitable for profiling.
> ShotoverProcessBuilder: fix with_profile

- Cargo.lock
- ec2-cargo/src/main.rs
- windsock-cloud-docker/Cargo.toml
- windsock-cloud-docker/src/main.rs
The core problem driving this PR is I observed that build files for windsock-cloud-docker was taking up 200MB in debug.
This is absurd for a small tool like this so I investigated how to fix it.
The problem was that test_helpers is huge and pulling in all sorts of stuff when all we wanted was a helper to run commands.
Once I moved `run_command` into its own minimal crate and windsock-cloud-docker was reduced to 8MB in debug.
So this PR:
* pulls run_command into its own crate.
+ This helper crate doesnt see as much use as it could because we often want to run commands asynchronously and I wanted to avoid including the tokio dependency here.
+ Alternatively we could just copy run_command into windsock-cloud-docker to avoid creating an entire new crate, I couldnt really decide either way so …
> run_command refactor

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
This change reduces the number of steps needed to access rdkafka debug logs.
After this PR to access the logs the developer just needs to set `with_env_filter("warn,rdkafka=trace,librdkafka=trace")`.
These logs were invaluable for figuring out what was going wrong with https://github.com/shotover/shotover-proxy/pull/1310
> Enable rdkafka debug logs

- docs/src/SUMMARY.md
The writing-custom-transforms.md page exists but we were previously not linking to it anywhere.
You can test locally by running `docs/mdbook.sh`
> Fix mdbook link to custom transforms

- shotover/src/transforms/kafka/common.rs
- shotover/src/transforms/redis/sink_cluster.rs
- shotover/src/transforms/util/cluster_connection_pool.rs
- shotover/src/transforms/util/mod.rs
cluster_connection_pool.rs provides some helpers for sending/receiving messages to a destination that gets reused across multiple protocols: redis, kafka and opensearch.
Only RedisSinkCluster makes use of the `original` field in `Response` struct so by just implementing this logic within RedisSinkCluster itself we will improve performance of other sinks by avoiding cloning messages which can be expensive.
Maybe RedisSinkCluster could be refactored to avoid needing the original messages entirely, but that is out of scope of this PR, this PR introduces 1 extra allocation but should otherwise be just as fast.
> remove Response.original field

- deny.toml
The CI on #1298 is failing due to https://github.com/shotover/shotover-proxy/actions/runs/6180379036/job/16776751233?pr=1298#step:4:11
A dependency uses the zlib license which we have not allowed in our `deny.toml`.
Zlib is described as a permissive free software license and has been approved by the Free Software Foundation as a free software license and by the Open Source Initiative as an open source license. It is compatible with the GNU General Public License. [refs](https://en.wikipedia.org/wiki/Zlib_License)
I also removed `pktparse` from our exceptions as we no longer use it as a dependency.
> add zlib to allowed licenses

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/benches/windsock/aws/mod.rs
- windsock-cloud-docker/Cargo.toml
- windsock-cloud-docker/src/main.rs
Fixes a TODO and a previously unknown case where shell escaping was missing.
This fix allows the running of `cargo run --package windsock-cloud-docker --cloud "name=redis encryption=none"` which previously failed due to `"name=redis encryption=none"` losing its quotes.
> windsock: apply shell escaping where needed

- shotover-proxy/Cargo.toml
Previously it was possible to run windsock such that the built shotover was missing some of the transforms windsock expects to exist.
As a bonus this PR enables writing custom sources (but not custom protocols)
> windsock: required-features = alpha-transforms

- shotover/src/transforms/redis/sink_cluster.rs
Currently RedisSinkCluster will cause shotover to fail to startup if the destination redis cluster is inaccessible.
This goes against the design of every other sink where shotover will successfully startup regardless of the destination DB's state. It is only once an actual message is sent to shotover that a connection is made to the destination.
I believe the approach of the other sinks is the better approach as it is more flexible:
* we can initialize shotover and redis concurrently and then start sending messages once both have started up.
* if a shotover instance is added to a cluster while the cluster happens to be inaccessible the shotover node is not dead.
* We can actually update our topology at runtime, with the current approach non-authenticated setups are stuck with the same …
> RedisSinkCluster: remove dependency on redis during startup

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/lib.rs
Small helper library that removes duplications from our rstest setup for the Cassandra integration tests.
> add rstest_reuse

- windsock-cloud-docker/src/main.rs
* The escape function will add quotes if needed. e.g. `foo bar` becomes `'foo bar'`. However `""` becomes ` ` which fails to parse when running something like `--results-by-tags ""` as that just becomes `--results-by-tags` and --results-by-tags needs to have a single argument.
* The windsock_data directory wont exist if its the first time running, so we have to ignore failures.
> windsock-cloud-runner: misc fixes

- .github/workflows/build_and_test.yaml
- .github/workflows/lint.yaml
This will have a few benefits:
* Make CI "out of disk space" issues less frequent - linting and testing both produce a lot of shared artifacts but they also produce a lot of large unshared artifacts, by splitting them up across separate instances we can give each more disk space to work with. This benefit was my main motivation as I hit this issue again today.
* Make CI cached runs complete 3 mins faster - linting has become slow recently, taking ~3mins on a cached run due to having to test every combination of compile time feature. - A very nice incidental win.
* A linting failure does not prevent seeing test results.
Downsides are some more duplication in our CI configuration.
> CI: split lints + tests into seperate workflows

- shotover-proxy/tests/test-configs/redis/tls-no-client-auth/docker-compose.yaml
- shotover-proxy/tests/test-configs/redis/tls-no-client-auth/redis.conf
- shotover-proxy/tests/test-configs/redis/tls-no-verify-hostname/docker-compose.yaml
- shotover-proxy/tests/test-configs/redis/tls-no-verify-hostname/redis.conf
- shotover-proxy/tests/test-configs/redis/tls/docker-compose.yaml
- shotover-proxy/tests/test-configs/redis/tls/redis.conf
- test-helpers/src/docker_compose.rs
Swap to the bitnami redis image for our redis TLS tests.
The advantage of this is we can specify our redis config entirely through environment variables instead of needing a seperate redis.conf
This will be a useful reference when implementing windsock aws redis benches as having less files to push the remote server will make our lives easier.
> redis tls tests use bitnami image

- Cargo.lock
- shotover-proxy/benches/windsock/aws/mod.rs
- windsock-cloud-docker/Cargo.toml
- windsock-cloud-docker/src/container.rs
- windsock-cloud-docker/src/main.rs
Refactor windsock-cloud-docker so that it cleans up the in progress cargo command.
Its very common to want to kill cargo while its building if I change my mind.
Currently when I do that to windsock-cloud-docker it leaves a stray cargo process running in the background which will:
* block new cargo compilations until the original cargo finishes compiling
* eventually proceed to spin up AWS resources, without me being aware
This is quite problematic.
To fix this I:
1. refactored windsock-cloud-docker to be async
2. split all the logic between a Container::new() and Container::run_windsock methods
3. then used tokio::select to allow sigint (ctrl-c) to terminate an in progress run + run cleanup code.
Doing this without async is quite difficult as we would need to refactor commands to be …
> windsock-cloud-docker: cleanup running processes when killed

- Cargo.lock
- Cargo.toml
- ec2-cargo/src/main.rs
- shotover-proxy/benches/windsock/aws/mod.rs
- shotover-proxy/benches/windsock/profilers.rs
- shotover-proxy/benches/windsock/profilers/sar.rs
- shotover/Cargo.toml
I'd like to be able to make use of the placement group changes in aws-throwaway.
The code changes needed here all stem from: https://github.com/shotover/aws-throwaway/pull/14
> Update aws-throwaway + aws-sdk-kms

- Cargo.lock
- Cargo.toml
- docs/src/transforms.md
- shotover-proxy/Cargo.toml
- shotover-proxy/config/config.yaml
- shotover-proxy/tests/test-configs/tee/switch_chain.yaml
- shotover-proxy/tests/transforms/tee.rs
- shotover/Cargo.toml
- shotover/src/transforms/tee.rs
This change allows the user to switch which chain to "read" responses from within Tee. The purpose in mind for this is switching from the source cluster to the target cluster during OpenSearch dual writing. More details can be found in `transforms.md`.
> tee switch main chain

- Dockerfile
- takes the recommendations from https://github.com/shotover/shotover-proxy/issues/1363
- update from `debian:bullseye-slim` to `stable-slim`
> dockerfile changes

- .github/workflows/docker.yaml
Blocked on https://github.com/shotover/shotover-proxy/pull/1364
> Add CI workflow to ensure docker image continues to build and run

- windsock/src/lib.rs
- windsock/src/report.rs
For an internal project we needed to integrate an external benchmarking tool with windsock.
So this PR introduces a way to do this.
Usually we generate a ReportArchive by processing all the reports sent by the benchmark.
But with this alternate API the user is able to provide a complete fully formed ReportArchive in a single report message, this allows the user to easily convert the output of an external tool into a format usable by windsock.
Its unfortunate that we are exposing all of this internal state, but I think its justified because integration with existing benchmarking tools is an important use case.
> windsock: better support external benchers

- shotover/src/transforms/protect/key_management.rs
This todo has become irrelevant since the introduction of the TransformBuilder, a new client is not created with each new connection.
> remove todo

- shotover-proxy/benches/windsock/aws/mod.rs
- shotover-proxy/benches/windsock/kafka.rs
Before this PR our shotover benches were actually benching directly with kafka completely bypassing shotover!
The KafkaSinkSingle transform is designed to run only on the same machine as the kafka broker.
However the bench currently sets up kafka and shotover on different instances.
One would expect this to result in an error somewhere and the bench to fail.
But what actually happens is that shotover fails to rewrite the metadata query containing the kafka nodes in the cluster and as a result once the bencher receives the metadata query back from shotover it proceeds to send all the benchmark queries directly to kafka.
In more detail:
Shotover will overwrite the port of any brokers returned by the metadata requests.
When shotover and kafka are on different instances they both have ports …
> Fix kafka benches to actually bench shotover

- shotover-proxy/benches/windsock/kafka.rs
- shotover-proxy/tests/test-configs/kafka/bench/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/passthrough/topology-encode.yaml
- shotover-proxy/tests/test-configs/kafka/passthrough/topology.yaml
- shotover/src/transforms/kafka/sink_single.rs
As per the comment I added:
KafkaSinkSingle is designed solely for the use case of running a shotover instance on the same machine as each kafka instance.
I cannot think of a valid configuration where the destination host is set to a value other than the private ip of the machine.
It could technically be set to `localhost` but AFAIK that doesnt offer any advantages over just using the private ip.
Is there a case i'm missing?
So given this, allowing the user to set the full address is just a footgun so we should remove this config instead only allowing the user to set the port.
> KafkaSinkSingle: remove dest host config, rely solely on dest port

- shotover-proxy/tests/cassandra_int_tests/cluster/multi_rack.rs
- shotover-proxy/tests/runner/observability_int_tests.rs
- shotover-proxy/tests/runner/runner_int_tests.rs
- shotover/src/config/topology.rs
- shotover/src/server.rs
- shotover/src/transforms/chain.rs
- shotover/src/transforms/distributed/tuneable_consistency_scatter.rs
- shotover/src/transforms/parallel_map.rs
- shotover/src/transforms/redis/cache.rs
- shotover/src/transforms/tee.rs
- shotover/src/transforms/throttling.rs
This PR tweaks chain naming so that it does not include "chain" in the name by default, allowing us to avoid including "chain" when it would be redundant.
There are two use cases of chain names:
* metrics - chain was redundant here, so this is now improved.
* topology validation - this PR alters the output of chain validation to make it clear that the chain name is referring to a chain.
> Tweak chain naming

- shotover-proxy/benches/windsock/cassandra.rs
- shotover-proxy/benches/windsock/common.rs
- shotover-proxy/benches/windsock/kafka.rs
- shotover-proxy/benches/windsock/main.rs
Previously for kafka we only had topology=single but this PR expands that to:
* topology=single - KafkaSinkSingle connecting to a single kafka instance
* topology=cluster1 - KafkaSinkCluster connecting to a single kafka instance
* topology=cluster3 - KafkaSinkCluster connecting a 3 node kafka cluster
> KafkaSinkCluster benches

- .github/workflows/windsock_benches.yaml
- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/benches/windsock/cassandra.rs
- shotover-proxy/benches/windsock/kafka.rs
- shotover-proxy/benches/windsock/profilers.rs
- shotover-proxy/benches/windsock/profilers/shotover_metrics.rs
- shotover-proxy/benches/windsock/redis.rs
- windsock/src/lib.rs
- windsock/src/report.rs
- windsock/src/tables.rs
Add a new windsock profiler (`--profilers shotover_metrics`) that fetches metrics from shotovers prometheus web interface.
When I implemented sar based system metrics, I set it up to extract specific hardcoded metrics from the full pool of metrics collected by sar. This made sense there as:
* sar collects a lot of metrics and only some of them are relevant
* sar's naming was quite poor and we can give better names for each item
* we can define an appropriate Goal value for each metric.
However for prometheus metrics I opted to include all metrics as long as we know how to handle that type of metric.
My reasoning is:
* Metrics are very dyanamic, new metrics are added or removed just by adding or removing transforms, so we need to dyanamically adapt to that.
* All metrics are relevant - no …
> Add shotover metrics profiler

- changelog.md
- docs/src/user-guide/observability.md
- shotover-proxy/benches/windsock/profilers/shotover_metrics.rs
- shotover-proxy/tests/cassandra_int_tests/cache/assert.rs
- shotover-proxy/tests/cassandra_int_tests/cluster/multi_rack.rs
- shotover-proxy/tests/runner/observability_int_tests.rs
- shotover/src/codec/cassandra.rs
- shotover/src/server.rs
- shotover/src/transforms/cassandra/sink_cluster/mod.rs
- shotover/src/transforms/cassandra/sink_cluster/node_pool.rs
- shotover/src/transforms/cassandra/sink_single.rs
- shotover/src/transforms/chain.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/query_counter.rs
- shotover/src/transforms/redis/cache.rs
- shotover/src/transforms/redis/sink_cluster.rs
- shotover/src/transforms/redis/sink_single.rs
- shotover/src/transforms/tee.rs
This PR introduces a new metric batch_size that records a histogram of the batch sizes used for each chain.
However in adding this I found that shotover_metrics windsock profiler cannot properly format this new metric as it assumes that all histograms are measured in milliseconds.
This is not good so I sought a way to fix this.
As per https://prometheus.io/docs/practices/naming/ our metrics should be named such that the unit is postfixed to the metric name.
Once we do that we have a way to correctly identify the unit used by the metrics.
So I renamed all our metrics to follow this and then changed shotover_metrics profiler to make use of these to determine how to format the metrics.
> Add batch size metric + rename existing metrics

- shotover/src/server.rs
- shotover/src/sources/cassandra.rs
- shotover/src/sources/kafka.rs
- shotover/src/sources/opensearch.rs
- shotover/src/sources/redis.rs
This code has always been weird.
There have been previous PRs to clean it up:
* https://github.com/shotover/shotover-proxy/pull/140
* https://github.com/shotover/shotover-proxy/pull/644
But they both avoided touching the actual logic to keep the PR scope down.
This PR completely replaces the timeout logic:
* fixes the timeout to actually timeout after specified seconds
+ Currently the logic will timeout after around `log2(seconds)`, I dont think there is any good reason for this old behavior.
* Should improve performance a little:
+ This function showed up in the profiler, which is why I started working on this in the first place.
+ Avoiding using the timeout when we dont need it should help a bit
+ Avoiding breaking out of the await every second should also help a bit.
* I think the …
> Fix client timeout

- shotover/benches/benches/chain.rs
- shotover/src/server.rs
- shotover/src/transforms/chain.rs
- shotover/src/transforms/load_balance.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/parallel_map.rs
- shotover/src/transforms/redis/cache.rs
- shotover/src/transforms/sampler.rs
Previously we were duplicating client_details state and often setting it to invalid values.
This PR fixes that by avoiding passing as a separate parameter and instead always using the value from Wrapper.
> Cleanup client_details

- shotover-proxy/tests/runner/observability_int_tests.rs
- shotover/src/transforms/chain.rs
- shotover/src/transforms/coalesce.rs
- shotover/src/transforms/filter.rs
- shotover/src/transforms/load_balance.rs
- shotover/src/transforms/mod.rs
Currently the chain registers metrics for all its transforms but then throws away the handles, requiring the transforms to access the metrics without the handles.
This currently works fine however there are two issues with this:
* its a lot slower to access metrics without the handle, it was showing up in a profiler.
* Its easy to forget to register the metric in the first place when working without handles. In fact thats exactly what had happened to the `transform_pushed_*` metrics.
This PR fixes those two issues by holding onto the handles and then using them later on for recording metrics.
After the change I can now see:
* that we are spending less time in metrics code in the windsock samply profiler
* A roughly 25% improvement in our `transform/loopback` micro benchmark introduced by …
> Transform metrics use handles

- .github/workflows/lint.yaml
Only just noticed this issue with all the concurrent PRs.
All the other workflows include `_${{ github.head_ref }}` to ensure that we dont cancel workflows from other PRs, but that was missing for the link workflow.
> Fix running multiple lint GA workflows

- shotover-proxy/tests/cassandra_int_tests/cluster/multi_rack.rs
- shotover-proxy/tests/runner/observability_int_tests.rs
- shotover-proxy/tests/runner/runner_int_tests.rs
- shotover/src/config/topology.rs
- shotover/src/server.rs
Progress towards the second design in https://github.com/shotover/shotover-proxy/issues/337
But immediately rollsback a breaking change to our public facing API.
> Remove "source" suffix from source chain names

- shotover/src/transforms/cassandra/sink_cluster/node_pool.rs
Looking at profiling taken before and after this change, previously we spent 5% of our time in this function within the PreparedMetadata Clone+Drop, now we spend only 0.2% of our time in the Clone+Drop.
> Use Arc to avoid cloning PreparedMetadata

- shotover/src/transforms/chain.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/redis/sink_cluster.rs
There is no need to pass in the chain name in this way.
We already give access to the chain name via passing it to the transform builders: https://github.com/shotover/shotover-proxy/blob/df6e283ebf9accb2756252872a6634b77e1de789/shotover/src/transforms/mod.rs#L247 So passing it to the transforms via `CONTEXT_CHAIN_NAME` is just redundant.
Removing the `CONTEXT_CHAIN_NAME.scope(..)` gives us a 7% win to the loopback bench on top of the changes in https://github.com/shotover/shotover-proxy/pull/1405
> Remove chain name from wrapper

- docs/src/user-guide/observability.md
- shotover-proxy/benches/windsock/shotover.rs
- shotover-proxy/config/config.yaml
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/lib.rs
- shotover-proxy/tests/test-configs/shotover-config/config1.yaml
- shotover-proxy/tests/test-configs/shotover-config/config2.yaml
- shotover-proxy/tests/test-configs/shotover-config/config3.yaml
- shotover/src/connection_span.rs
- shotover/src/lib.rs
- shotover/src/server.rs
- test-helpers/src/shotover_process.rs
closes https://github.com/shotover/shotover-proxy/issues/1421
As written up in https://github.com/shotover/shotover-proxy/issues/1421 I've observed performance issues caused due to entering/exiting spans.
So this PR disables by default the only span created by shotover, the "connection" span, by setting the span level from error to debug.
This means the span will only be enabled when tracing level is set to debug.
This span is very useful for debugging so I:
* Made a module specifically for the span to allow enabling just the span without any other events getting enabled with it.
* Documented how to reenable it.
* Enabled it by default for integration tests (but not for benchmarks)
For reference, when the span is enabled logs look like:
```
04:26:06.269278Z  WARN connection{id=11 …
```
> make connection span debug only (optimization)

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover-proxy/tests/test-configs/kafka/cluster/docker-compose.yaml
- shotover/src/frame/kafka.rs
- shotover/src/transforms/kafka/sink_cluster.rs
Some requests need to be routed to a specific kafka broker known as the "controller broker".
However currently we never perform that routing.
This results in messages like CreateTopic having 2/3 chance of failing when sent to a 3 node kafka cluster.
This PR fixes that failure by:
* Retrieving the controller broker from a metadata request when we receive our first request from the client.
+ The controller broker id is then stored to the KafkaSinkCluster shared state.
* Using the controller broker to correctly route the CreateTopic message.
To ensure all the admin requests work, I have added an integration test which exercises most of it.
I've left a few bits of the integration test as TODOs, they can be addressed later.
Surprisingly CreateTopic is the only request I've seen so far that …
> Implement kafka controller routing

- shotover/src/transforms/cassandra/sink_cluster/mod.rs
- shotover/src/transforms/cassandra/sink_cluster/node_pool.rs
- shotover/src/transforms/cassandra/sink_cluster/token_ring.rs
I came up with an implementation that is faster than iterating over a BTreeMap.
It wasnt as fast as I hoped it would be but its still a 0.4% win when profiling `cassandra,compression=none,connection_count=100,driver=scylla,operation=read_i64,protocol=v4,shotover=standard,topology=cluster3` so I think its still worth it, so lets land it unless there are objections due to extra complexity.
BTreeMap and binary search are both average and worse case `O(log(n))` so they should be no issue when cassandra is configured with more tokens. I believe our benchmarks use 255 tokens.
Originally based on the scylla implementation from https://github.com/scylladb/scylla-rust-driver/blob/main/scylla/src/transport/locator/token_ring.rs
Using exactly their implementation gave the same or very slightly worse …
> Cassandra optimize ring walking

- Cargo.lock
- ec2-cargo/Cargo.toml
- ec2-cargo/src/main.rs
Previously commands like `windsock "foo=1 bar=2"` would have the `"` lost along the way which result in a invalid windsock cli arguments.
This PR fixes the issue by escaping the arguments.
> Escape ec2-cargo args

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/benches/windsock/cassandra.rs
- shotover-proxy/benches/windsock/cloud/aws.rs
- shotover-proxy/benches/windsock/cloud/mod.rs
- shotover-proxy/benches/windsock/kafka.rs
- shotover-proxy/benches/windsock/main.rs
- shotover-proxy/benches/windsock/redis.rs
- windsock/src/cloud.rs
Resolves some TODO's left from the recent rework.
This PR flips the modules so now the cloud module holds the aws module which better reflects the actual dependency between AwsCloud and AwsInstances (formerly AwsWindsock).
Methods on the cloud trait were changed to use `&mut self` in order to provide more flexibility to the implementer.
> refactor shotover windsock cloud

- Cargo.lock
- Cargo.toml
- ec2-cargo/src/main.rs
- shotover-proxy/benches/windsock/cloud/mod.rs
- shotover-proxy/benches/windsock/readme.md
- windsock-cloud-docker/src/container.rs
Makes use of https://github.com/shotover/aws-throwaway/pull/41 to get all the build time wins of shelling out to the AWS CLI.
Dont merge until https://github.com/shotover/aws-throwaway/pull/42 lands so I can set it to the actual crates.io release, but I would still appreciate reviews simultaneous to https://github.com/shotover/aws-throwaway/pull/42
> Update aws-throwaway (improve build times)

- shotover/src/frame/cassandra.rs
- shotover/src/message/mod.rs
This is in preparation for https://github.com/shotover/shotover-proxy/pull/1441 where this refactor will slightly reduce complexity due to added `cfg(feature = "..")`s
> move into protocol specific modules for message module

- .cargo/config.toml
- .github/workflows/build.yaml
- .github/workflows/lint.yaml
- Cargo.toml
- custom-transforms-example/Cargo.toml
- custom-transforms-example/src/main.rs
- shotover-proxy/Cargo.toml
- shotover-proxy/benches/windsock/cloud/aws.rs
- shotover-proxy/benches/windsock/main.rs
- shotover-proxy/tests/lib.rs
- shotover/Cargo.toml
- shotover/src/codec/mod.rs
- shotover/src/config/topology.rs
- shotover/src/frame/mod.rs
- shotover/src/frame/value.rs
- shotover/src/lib.rs
- shotover/src/message/mod.rs
- shotover/src/sources/mod.rs
- shotover/src/transforms/coalesce.rs
- shotover/src/transforms/debug/returner.rs
- shotover/src/transforms/filter.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/query_counter.rs
- shotover/src/transforms/redis/mod.rs
- shotover/src/transforms/util/cluster_connection_pool.rs
- windsock-cloud-docker/src/container.rs
This improves compile times of windsock without compromising on performance like https://github.com/shotover/shotover-proxy/pull/1438 ended up doing.
Previously `cargo windsock` took 2m 45s to compile after a change to our windsock benches.
Now it takes:
* `cargo windsock-redis` - 1 min 32s
* `cargo windsock-kafka` - 1 min 21s
* `cargo windsock-cassandra` - 2 min 23s
* `cargo windsock` - 2m 45s
We would be getting similar improvements to our integration tests but we rarely need to run them in release so I didnt bother adding cargo aliases for them or measuring them.
Additionally, this PR improves compile times of shotover when developing custom transforms that only need to support a single protocol by allowing developers to disable unneeded dependencies within shotover, this will be quite …
> Add feature flags for each protocol in shotover

- windsock/src/bench.rs
We intentionally provide a default implementation here so that users not using cloud functionality dont need to worry about it.
But we can and should provide a better error message for cloud users that hit this panic.
> Add useful panic message when required_cloud_resources is unimplemented

- Cargo.lock
- shotover-proxy/benches/windsock/cassandra/bench.rs
- shotover-proxy/benches/windsock/cloud/aws.rs
- shotover-proxy/benches/windsock/profilers.rs
- shotover-proxy/benches/windsock/profilers/shotover_metrics.rs
I needed to fix two things to get shotover_metrics working on cloud benches:
* Use the connect_ip to fetch the metrics from instead of the private ip. connect_ip will automatically select the private or public ip depending on how aws-throwaway was configured. Public is used when the bencher is on your local machine private is used when the bencher is within EC2.
* expose port 9001 to the internet via `expose_ports_to_internet` builder method.
> Fix cloud shotover metrics

- shotover-proxy/benches/windsock/cassandra/bench.rs
I can tell it works because throughput increases x3 for connection_count=10 and connection_count=100
Not sure what the difference is between with_local_size and with_remote_size so I just set both.
> windsock: fix cdrs connection count

- windsock-cloud-docker/src/container.rs
Allows us to enable tracing logs for windsock.
> windsock-cloud-docker: pass RUST_LOG env var through to windsock

- Cargo.lock
- shotover-proxy/benches/windsock/cloud/aws.rs
- shotover-proxy/benches/windsock/cloud/mod.rs
- windsock/src/cli.rs
- windsock/src/cloud.rs
- windsock/src/data.rs
- windsock/src/lib.rs
- windsock/src/tables.rs
progress towards https://github.com/shotover/shotover-proxy/issues/1274
```shell
> # Create the resources required to run the benches specified in FILTER and then store the information required to access those instances to disk
> cargo windsock --store-cloud-resources-to-disk "name=kafka shotover=standard size=100KB topology=cluster3"
Creating AWS resources: CloudResourcesRequired {
shotover_instance_count: 1,
docker_instance_count: 3,
include_shotover_in_docker_instance: false,
}
> # Run the benches once, using the instances created in the previous command.
> cargo windsock --load-cloud-resources-file "name=kafka shotover=standard size=100KB topology=cluster3"
Running "kafka,shotover=standard,size=100KB,topology=cluster3"
...
> # Run the benches a second time reusing the same instances
> …
```
> windsock: add --load-cloud-resources-from-disk and --store-cloud-resources-to-disk

- shotover-proxy/tests/cassandra_int_tests/batch_statements.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/test-configs/cassandra/cassandra-5/docker-compose.yaml
- shotover-proxy/tests/test-configs/cassandra/cassandra-5/topology.yaml
- test-helpers/src/docker_compose.rs
> cassandra 5 single tests

- shotover/benches/benches/codec/kafka.rs
Dropping types is actually quite expensive and affects benchmark results.
In this PR:
* To avoid measuring the drops of types we dont care about, we return them back to the criterion bencher as the return value.
* To measure the drops of types we do care about we create a separate benchmark just for measuring the time to drop.
+ We could keep them in the same benchmark which would reduce the number of benchmarks we have but splitting them like this makes it easier to tell the costs of different operations.
decode_all bench is deleted since we no longer perform batching from within decode so it no longer makes sense as a benchmark.
> Split drop out of kafka codec benchmarks

- shotover/src/server.rs
limit buffered incoming messages to 10,000 per connection.
A particular scenario we are concerned about is if it takes longer to send to the server than for the client to send to us, the buffer will grow indefinitely, increasing latency until the buffer triggers an OoM.
To avoid that we have currently hardcoded a limit of 10,000 but if we start hitting that in production we should make this user configurable.
> Limit max size of main chain batch to 10,000

- Cargo.lock
- Cargo.toml
- shotover/Cargo.toml
- shotover/benches/benches/main.rs
- shotover/src/codec/cassandra.rs
- shotover/src/codec/mod.rs
- shotover/src/runner.rs
- shotover/src/server.rs
- shotover/src/transforms/cassandra/sink_cluster/mod.rs
- shotover/src/transforms/cassandra/sink_cluster/node_pool.rs
- shotover/src/transforms/cassandra/sink_single.rs
- shotover/src/transforms/chain.rs
- shotover/src/transforms/query_counter.rs
- shotover/src/transforms/redis/cache.rs
- shotover/src/transforms/redis/sink_cluster.rs
- shotover/src/transforms/redis/sink_single.rs
- shotover/src/transforms/tee.rs
The shortcut macros like `counter!` have been removed and the register macros like `register_counter!` have been renamed like `counter!`.
The register macros can be used in place of the shortcut macros since the shortcut macros were just registering and dropping a metric internally anyway.
> Update metrics crate

- Cargo.lock
- shotover/Cargo.toml
We should get the important performance improvements from https://github.com/shotover/shotover-proxy/pull/1459 out the door.
We can make a patch release since we havent had any breaking changes to shotover since 0.3.0
> Release shotover 0.3.1

- Cargo.lock
- shotover-proxy/Cargo.toml
We failed to properly release both 0.3.0 and 0.3.1 and completely failed to notice.
This is definitely pushing forward a move to https://github.com/axodotdev/cargo-dist for me.
This PR fixes the release.
I'll retag this commit as the true 0.3.1.
> Release shotover 0.3.1 (fix)

- Cargo.toml
The bench profile is a default profile that already exists that gets used when running benches.
It inherits from release and all the config that we set for it is already set by release.
So I just deleted it.
The profiling profile is a profile derived from release that windsock uses to recompile shotover to ensure that it has debuginfo enabled so that profiling it will give useful results.
The magic line that enables this is `debug = true` but previously I also thought that we needed to disable LTO.
However it turns out that it works just fine with LTO enabled.
So this PR enables lto by removing the `lto = false` line and letting it fall back to the release profiles `lto = fat`
This is very useful as it ensures that we are profiling a binary that is a lot closer to what we release.
I also …
> Enable LTO when profiling

- shotover-proxy/benches/windsock/profilers.rs
- shotover-proxy/benches/windsock/profilers/samply.rs
- windsock/src/report.rs
- windsock/src/tables.rs
closes https://github.com/shotover/shotover-proxy/issues/1177
Adds infrastructure to windsock for benches to make info level notes to the user and then makes use of it to have the  samply profiler output a copy/pasteable command to open the profiler results.
I also updated the pinned samply commit since theres been a few bugfixes since we last updated.
> Direct user where to find samply output

- shotover/src/frame/kafka.rs
We were loading the api key twice.
The first time we panicked if it was an unknown key.
And then the second time we gracefully returned an error.
This is a bit silly since we never hit the graceful error and always panic.
This PR fixes this so that we only load the api_key once and we perform graceful error handling that one time.
> Return useful error when encountering unknown kafka API key

- shotover/src/codec/kafka.rs
- shotover/src/codec/opensearch.rs
- shotover/src/codec/redis.rs
- shotover/src/message/mod.rs
- shotover/src/transforms/cassandra/connection.rs
- shotover/src/transforms/cassandra/sink_cluster/mod.rs
- shotover/src/transforms/cassandra/sink_cluster/rewrite.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/protect/mod.rs
- shotover/src/transforms/redis/cluster_ports_rewrite.rs
- shotover/src/transforms/redis/sink_cluster.rs
This PR introduces a `MessageId` type and assigns a unique `MessageId` to every message that goes through shotover.
Additionally responses now hold the MessageId of their corresponding request.
The API for this is exposed as methods on the `Message` type:
```rust
impl Message {
/// Return the shotover assigned MessageId
pub fn id(&self) -> MessageId {
self.id
}
/// Return the MessageId of the request that resulted in this message
/// Returns None when:
/// * The message is a request
/// * The message is a response but was not created in response to a request. e.g. Cassandra events and redis pubsub
pub fn request_id(&self) -> Option<MessageId> {
self.request_id
}
}
```
This will eventually replace the "requests are in the same order as responses" invariant but for now it is just in …
> Add MessageId (progress towards cleaning up transform invariants)

- .github/workflows/windsock_benches.yaml
- windsock/readme.md
- windsock/src/bench.rs
- windsock/src/cli.rs
- windsock/src/lib.rs
- windsock/src/list.rs
- windsock/src/tables.rs
closes https://github.com/shotover/shotover-proxy/issues/1480
This PR cleans up the windsock CLI.
We have accrued a large number of flags at this point and its time we turned them all into proper subcommands to simplify usage of the CLI.
Consider the new `cargo windsock help`:
compared to the old:
The relevant commands for a task are now a lot clearer, no longer lost among the sea of flags.
To achieve this reduction of the number of flags/subcommand the following was done:
* many flags turned into subcommands
* previously we split flags up as `name`/`by-tags`. But I've now altered names such that they are valid tags, so we no longer need the distinction.
* previously we had a separate flag for comparing against baselines. Now we compare against baselines automatically when they are …
> Redesign windsock cli

- shotover/src/transforms/redis/cluster_ports_rewrite.rs
Makes use of the new invariants introduced in https://github.com/shotover/shotover-proxy/pull/1476
> RedisClusterPortsRewrite port to MessageId

- Cargo.lock
- custom-transforms-example/src/redis_get_rewrite.rs
- shotover/Cargo.toml
- shotover/src/message/mod.rs
- shotover/src/transforms/cassandra/sink_cluster/mod.rs
- shotover/src/transforms/cassandra/sink_cluster/rewrite.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/protect/mod.rs
- shotover/src/transforms/redis/cluster_ports_rewrite.rs
- windsock/readme.md
Allows us to easily swap out our hashmap/hash implementation for the common idiom of `HashMap<MessageId, V>`.
Given how common this will be I think having finer control over our hashmap/hash will be quite valuable.
For now uses the fnv hasher as it is known to perform much better for integer keys than the default siphasher https://crates.io/crates/fnv
> Add type alias for common MessageIdMap

- shotover-proxy/benches/windsock/kafka/bench.rs
- shotover/src/transforms/kafka/sink_cluster.rs
Blocked on https://github.com/shotover/shotover-proxy/pull/1419
Need to use unique keys to ensure spread across topology3 cluster, otherwise it all gets routed to a single node
Strangely the bug that I was previously also able to reproduce in https://github.com/shotover/shotover-proxy/pull/1427 is now only reproducible in the topology=3 benches with this PR.
However I've now tracked down the cause of the issue and fixed it here.
I was indexing into a vector that wasnt actually sorted.
Sorting the vector at time of creation allows us to continue indexing into as we were before but its actually guaranteed to work now. The sort only occurs when processing metadata messages so it should be fine performance wise.
The windsock results clearly show an improvement for benches with and without …
> Windsock kafka fix routing

- .gitignore
- shotover-proxy/benches/windsock/kafka/bench.rs
- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/test-configs/kafka/passthrough-tls/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/passthrough-tls/topology.yaml
- shotover/src/transforms/kafka/sink_single.rs
- test-helpers/src/cert.rs
- test-helpers/src/docker_compose.rs
Implements TLS for KafkaSinkSingle.
KafkaSinkCluster and KafkaSource should be done in follow up PRs.
> Add TLS support for KafkaSinkSingle

- shotover/src/codec/cassandra.rs
- shotover/src/codec/kafka.rs
- shotover/src/codec/mod.rs
- shotover/src/codec/opensearch.rs
- shotover/src/codec/redis.rs
- shotover/src/frame/mod.rs
- shotover/src/server.rs
Pulled out of https://github.com/shotover/shotover-proxy/pull/1490 but adjusted a bit to use `MessageType` instead of `ProtocolType` which will be deleted.
This better abstracts our ability to retrieve the protocol type from a codec builder.
Previously we could only get a string used for websockets.
But now we get an enum that we can convert into the websockets string or use for other purposes.
> CodecBuilder::protocol

- shotover/benches/benches/chain.rs
- shotover/benches/benches/codec/kafka.rs
- shotover/src/codec/cassandra.rs
- shotover/src/codec/kafka.rs
- shotover/src/frame/mod.rs
- shotover/src/message/mod.rs
This PR swaps all usages of `ProtocolType` to `CodecState`, since they are completely identical.
It then removes `ProtocolType` entirely.
For all the usecases I think the name `CodecState` makes the most sense so that is the name I am keeping.
> Remove ProtocolType

- .github/workflows/bench_run.yaml
- .github/workflows/build.yaml
- .github/workflows/build_and_test.yaml
- .github/workflows/create_comment.yaml
- .github/workflows/docker.yaml
- .github/workflows/license_check.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- .github/workflows/windsock_benches.yaml
A bunch of the GA actions we use are now deprecated and will be removed soon:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20
Its hard to verify that the change to create_comment.yaml will still work since its not run until checked in, but I've examined the node APIs used and they should be unchanged from node 16 to node 20. Worst case I just have to fix it in a follow up PR.
As a bonus upload-artifact@v4 claims to have much faster upload speeds.
edit: Oh wow, they werent kidding.
Before:
After:
> Update GA deps

- shotover-proxy/benches/windsock/kafka/bench.rs
- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- test-helpers/src/connection/kafka.rs
- test-helpers/src/connection/mod.rs
- test-helpers/src/lib.rs
The driving factor for this was the ability to abstract over connections created with TLS, TLS+SASL,plaintext+SASL or just plaintext.
In the future I expect this to also be useful for abstracting over different kafka drivers.
The consumer and producer APIs are completely abstracted and the tests no longer directly interact with rdkafka.
However the rdkafka admin API is still directly exposed since that has a lot more surface area.
We can wrap that up if and when we need to abstract over multiple kafka drivers.
> Refactor kafka_int_tests to use connection creator helper

- custom-transforms-example/src/redis_get_rewrite.rs
- shotover/benches/benches/chain.rs
- shotover/src/config/chain.rs
- shotover/src/server.rs
- shotover/src/transforms/cassandra/peers_rewrite.rs
- shotover/src/transforms/cassandra/sink_cluster/mod.rs
- shotover/src/transforms/cassandra/sink_single.rs
- shotover/src/transforms/coalesce.rs
- shotover/src/transforms/debug/force_parse.rs
- shotover/src/transforms/debug/log_to_file.rs
- shotover/src/transforms/debug/printer.rs
- shotover/src/transforms/debug/returner.rs
- shotover/src/transforms/distributed/tuneable_consistency_scatter.rs
- shotover/src/transforms/filter.rs
- shotover/src/transforms/kafka/sink_cluster.rs
- shotover/src/transforms/kafka/sink_single.rs
- shotover/src/transforms/load_balance.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/null.rs
- shotover/src/transforms/opensearch/mod.rs
- shotover/src/transforms/parallel_map.rs
- shotover/src/transforms/protect/mod.rs
- shotover/src/transforms/query_counter.rs
- shotover/src/transforms/redis/cache.rs
- shotover/src/transforms/redis/cluster_ports_rewrite.rs
- shotover/src/transforms/redis/sink_cluster.rs
- shotover/src/transforms/redis/sink_single.rs
- shotover/src/transforms/redis/timestamp_tagging.rs
- shotover/src/transforms/tee.rs
- shotover/src/transforms/throttling.rs
This PR introduces the `TransformContextConfig` struct which is passed to each transform at the point where the `TransformConfig` is converted to a `TransformBuilder`. i.e. during shotover initialization
This enables a whole bunch of potential optimizations where we pass in some extra information about the context the transform is in. i.e. the chain its in and what other transforms are in its chain.
A potential future optimization would be detecting if the next transform is going to discard any responses passed to it.
This would allow for a nice optimization to the Filter transform where we skip error generation if its in a Tee subchain configured to discard responses.
However right now, `TransformContextConfig` just contains:
* the name of the chain which we currently use in various …
> Introduce TransformContextConfig

- docs/src/sources.md
- docs/src/transforms.md
- shotover-proxy/benches/windsock/kafka/bench.rs
- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/test-configs/kafka/cluster-tls/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-tls/topology.yaml
- shotover-proxy/tests/test-configs/kafka/passthrough-tls/docker-compose.yaml
- shotover/src/transforms/kafka/sink_cluster.rs
- shotover/src/transforms/kafka/sink_single.rs
Adds TLS support for KafkaSinkCluster.
Additionally documents the TLS support KafkaSinkCluster, KafkaSinkSingle and KafkaSource.
The other 2 were already implemented but not documented.
The documentation is copied from redis/cassandra which have identical configuration options for TLS.
> KafkaSinkCluster TLS support

- shotover-proxy/tests/kafka_int_tests/mod.rs
Issue introduced by https://github.com/shotover/shotover-proxy/pull/1509
All tests that setup shotover to use an alpha-transform should have `#[cfg(feature = "alpha-transforms")]` so that they dont show up as test failures when running without alpha-transforms enabled.
> Fix running integration tests without --features alpha-transforms

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- test-helpers/src/connection/kafka/cpp.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
This PR adds finer grained abstractions over the java/cpp kafka driver admin API in order to give control of test setup to the test itself.
This PR contains no changes to the functionality of the tests, the setup logic is just moved around.
> kafka_int_tests: abstract admin API

- shotover/src/message/mod.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/redis/cache.rs
This one was a bit tricky since the transform sends requests down a redis chain and waits for the responses before sending anything to cassandra.
So in order to fit the the new invariants we need to seperately keep track of what responses we are waiting for from both redis and cassandra.
However in the end it didnt add too much more complexity.
Once shotover reaches the point where it can send without waiting for responses, this transform will benefit from it greatly since it can respond to any cached requests immediately even if there are uncached requests in the same batch, before this PR that was impossible.
Additionally this is the final transform that required porting, so I've now removed the `Deprecated invariants` from the transform invariants documentation.
We can now proceed with …
> RedisCache: port to MessageId invariants

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
Implements producer + consumer logic for the kafka java test driver.
It passes for the single instance cluster tests, which is great!
But it also fails for all the multi instance cluster tests so I've disabled those tests for now. (just the java ones, the cpp clustered tests are still running)
I think its sensible to disable those tests as the producer+consumer is the juicy part, so we're better off having producer+consumer coverage for single than admin for both single+clustered.
I believe the cluster tests are failing due to a shotover bug, so I will fix that bug in a follow up PR and reenenable all the java tests then.
> Implement java producer + consumer

- shotover/src/transforms/kafka/sink_cluster/mod.rs
fixes the potential race condition raised in https://github.com/shotover/shotover-proxy/issues/1522.
> KafkaSinkCluster race condition fix

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
This PR has a few bug fixes included in one PR, since they are all needed to get the java driver working on kafka cluster + single shotover tests.
kafka cluster + multi shotover are still broken and will be investigated + fixed in a follow up.
A lot of the differences in the drivers stem from the cpp driver using an older version of the protocol.
So all of the codepaths for the new protocol were previously untested.
fetch sessions were previously unhandled.
https://cwiki.apache.org/confluence/display/KAFKA/KIP-227%3A+Introduce+Incremental+FetchRequests+to+Increase+Partition+Scalability
We need to detect when the server has setup a fetch session (when a fetch response includes a non-zero fetch_session) and then ensure that all fetch requests that specify that fetch_session are routed back …
> fix kafka cluster bugs discovered by java driver

- shotover-proxy/benches/windsock/cloud/mod.rs
Originally I avoided printing these out and instead manually added printlns when I really needed to debug something.
But since we now have cloud creation as a previous step I'm not so worried about the extra noise of printing these.
And the ability to ssh into the machines when something goes wrong is invaluable.
> write ssh instructions to stdout when creating cloud resources

- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_single.rs
While kafka sounds like it would make use of pushed messages due to its pubsub model, responses are never sent without a corresponding request.
A fetch request is resent everytime the client wants another fetch response.
So these pushed messages senders can be just removed, I assume they were originally added due to copy/pasting from another transform as a base and it was just assumed that kafka would need push messages.
> Remove pushed_messages mpsc from kafka transforms

- Cargo.lock
- Cargo.toml
- shotover/Cargo.toml
- shotover/src/http.rs
- shotover/src/lib.rs
- shotover/src/observability/mod.rs
- shotover/src/transforms/tee.rs
Simplifies the implementation of our configuration webservers and removes the duplicate hyper dependency.
Currently this PR regresses release build time by 9s on my machine.
I thought we might win back some build time by the removal of hyper 0.14 but in this measurement of 9s I have already removed hyper 0.14
Not sure if its worth proceeding with this cost to build time.
> Replace hyper with axum

- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
- shotover-proxy/tests/redis_int_tests/mod.rs
- shotover/src/connection.rs
- shotover/src/lib.rs
- shotover/src/transforms/redis/sink_single.rs
This PR is the first step towards a unified connection abstraction that we can use for all protocols/transforms/sources.
Currently each protocol and sometimes even each sink of a protocol will use its own connection abstraction, these are large slightly different reimplementations of the same idea, so we should unify them to improve maintainability.
Some of these implementations are missing:
* robust error handling - kafka, redis and server.rs are missing this.
* messages send/received in batches - all sinks except RedisSinkSingle are currently missing this.
* triggers force_run_changes on received messages - all sinks except RedisSinkSingle are currently missing this.
So the way forward I've chosen here is to create a new Connection type that handles the above missing features and then …
> Connection abstraction

- .github/workflows/create_comment.yaml
This was broken in https://github.com/shotover/shotover-proxy/pull/1493
no real way to test this without actually checking in, so lets see how this goes.
> Fix GA comment creation

- .github/workflows/windsock_benches.yaml
- shotover-proxy/benches/windsock/cassandra/bench.rs
- shotover-proxy/benches/windsock/kafka/bench.rs
- shotover-proxy/benches/windsock/redis/bench.rs
Windsock used to special case the "name" tag such that the  `name=` prefix was removed.
To reduce complexity for the user by making tags more predictable that functionality was removed.
However we are still left with tags named "name" when we would be better off calling this tag "db".
> windsock: Rename "name" tag to "db"

- shotover/src/codec/kafka.rs
- shotover/src/connection.rs
- shotover/src/message/mod.rs
- shotover/src/transforms/kafka/sink_single.rs
- shotover/src/transforms/redis/sink_single.rs
This ended up a bit involved since I needed to add dummy response generation to the Connection type in order to get kafka working.
The connection logic used by cluster_connection_pool.rs already has this implemented https://github.com/shotover/shotover-proxy/blob/main/shotover/src/transforms/util/cluster_connection_pool.rs#L290 and many transforms rely on this.
The new implementation in Connection is more robust though, the one in cluster_connection_pool.rs has issues with cancel safety and a possible race condition.
The actual porting of KafkaSinkSingle to Connection is pretty straightforward, is very similar to RedisSinkSingle
windsock benchmarks show no regressions.
> Port KafkaSinkSingle to Connection

- shotover/src/codec/cassandra.rs
- shotover/src/connection.rs
- shotover/src/frame/cassandra.rs
- shotover/src/message/mod.rs
- shotover/src/server.rs
- shotover/src/transforms/cassandra/peers_rewrite.rs
- shotover/src/transforms/cassandra/sink_single.rs
- shotover/src/transforms/kafka/sink_single.rs
- shotover/src/transforms/redis/sink_single.rs
- test-helpers/src/connection/cassandra.rs
This PR includes two changes that needed to be included in a single PR as they are dependent on each other:
* CassandraSinkSingle uses the new Connection type instead of the old Cassandra specific CassandraConnection.
* CassandraSinkSingle and CassandraPeersRewrite no longer use `Transform::transform_pushed` and instead expect cassandra events to come through the regular `Transform::transform` chain.
+ CassandraPeersRewrite only works with CassandraSinkSingle so they had to be done together but I see no issue with leaving CassandraSinkCluster for another PR.
Additionally this PR adds logic to the cassandra codec to assign request_id's to incoming responses.
This could technically be in a prereq, but its fairly straightforward so I'm including it here.
It follows the exact same logic as …
> Port CassandraSinkSingle to Connection + remove transform_pushed impementation

- shotover/src/connection.rs
- shotover/src/server.rs
- shotover/src/transforms/cassandra/sink_single.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/node.rs
- shotover/src/transforms/kafka/sink_single.rs
- shotover/src/transforms/redis/sink_single.rs
Originally I wanted server.rs to make use of the new Connection abstraction: https://github.com/shotover/shotover-proxy/pull/1551
But at this point I think that sink transforms and server.rs have very different needs so its better to just make Connection a sink specific abstraction.
This includes renaming to ConnectionSink and removing all attempts at compatibility with server.rs
> Rename Connection -> ConnectionSink

- shotover/src/connection.rs
- shotover/src/transforms/cassandra/sink_single.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/node.rs
- shotover/src/transforms/kafka/sink_single.rs
- shotover/src/transforms/redis/sink_single.rs
In this PR we finally receive some of the performance wins the recent refactors have been leading towards.
The changes to make this happen are:
* Fix coordinator logic to use message IDs instead of indexes
+ Its a prereq and I missed this in https://github.com/shotover/shotover-proxy/pull/1548
* Add timeout logic to connection.
+ Without this there is no way to maintain our read timeouts when we swap to try_recv since it is not async.
* Replace Connection::recv with Connection::try_recv
+ this is where the actual performance gains come from
+ Using try_recv means we no longer wait for all messages to arrive and can immediately return from and rerun the chain. This means the sending of more requests is no longer blocked on responses coming back.
1KB messages get +30% throughput and -15% …
> KafkaSinkCluster use try_recv instead of recv

- Cargo.lock
- Cargo.toml
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
- shotover/Cargo.toml
- shotover/src/codec/redis.rs
- shotover/src/frame/mod.rs
- shotover/src/transforms/redis/sink_cluster.rs
* The "decode-mut" feature is now under the "bytes" feature
* A bunch of methods and types were renamed
* the Redirection type + to_redirection method were removed, they are quite simple so I just reimplemented them in RedisSinkCluster.
* bytes-utils is now reexported within redis-protocol, since we only use that for interacting with redis-protocol, we now use the reexport instead of bytes-utils directly.
> Update redis-protocol 0.4 to 0.5

- shotover/src/transforms/cassandra/sink_cluster/mod.rs
https://github.com/shotover/shotover-proxy/pull/1476 ported CassandraSinkCluster to use MessageId.
Well almost, it missed one case, which is the handling of use statements.
I spent a bunch of time thinking about how to handle processing them with MessageId's instead of indexes.
Its definitely possible but it also adds a bunch of extra complexity and I'm not sure if its worth it in the first place.
So @cjrolo I'm interested in your thoughts on how often cassandra clients make use of `use`ing a namespace.
With this PR every time the client uses a `use namespace` statement shotover will close all outgoing connections in use by the transform instance (1 connection per cassandra node in the cluster).
Those connections will then be reopened as shotover routes requests to …
> CassandraSinkCluster index removal

- shotover/src/transforms/cassandra/sink_cluster/rewrite.rs
Previously we were modifying `self.to_rewrite` assuming that it only contained `TableToRewrite`s from the current request batch but it may actually contain `TableToRewrite`s from previous request batches as well.
This happens to work currently since we complete rewriting within a single request batch, but as of https://github.com/shotover/shotover-proxy/pull/1553 that will no longer be the case.
> CassandraSinkCluster rewrite.rs fix

- shotover-proxy/tests/cassandra_int_tests/cluster/mod.rs
- shotover/src/transforms/cassandra/sink_cluster/mod.rs
- shotover/src/transforms/cassandra/sink_cluster/node.rs
- shotover/src/transforms/cassandra/sink_cluster/topology.rs
Pulled out of https://github.com/shotover/shotover-proxy/pull/1553
In this PR:
* We pass a few extra variables around to allow the construction of the SinkConnection. (read_timeout and force_run_chain)
* We alter the logic of the topology task a little to handle the case where we send a request and await a response but get an event instead of a response.
+ This previously did not occur but occurs now because we no longer separate events into `Transform::transform_pushed`
> Port CassandraSinkCluster topology task to new Connection type

- shotover/benches/benches/chain.rs
- shotover/src/server.rs
- shotover/src/transforms/chain.rs
- shotover/src/transforms/distributed/tuneable_consistency_scatter.rs
- shotover/src/transforms/mod.rs
This PR moves client_details from being passed at chain run time to chain build time.
This improves performance in 2 ways:
* client_details string is no longer reallocated and deallocated every chain run
* shotover_chain_latency histogram is no longer recreated every chain run
This results in a very nice improvement to chain overhead, 25% faster in a chain containing just a loopback transform:
In reality this is a very small win for actual workloads, I'm guessing ~0.3% from what I could see in the profiler, but since it improves performance for all protocols and workloads its very much worth doing.
> Avoid cloning client_details

- shotover/src/transforms/cassandra/sink_cluster/rewrite.rs
Currently CassandraSinkCluster rewrite logic relies on the responses arriving in order but https://github.com/shotover/shotover-proxy/pull/1567 will change them to be out of order.
This PR fixes the rewrite logic so it no longer gives up if it encounters an out of order message.
> fix CassandraSinkCluster rewrite logic

- shotover-proxy/tests/test-configs/kafka/cluster-2-racks/topology-rack1.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-2-racks/topology-rack2.yaml
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- test-helpers/src/connection/kafka/cpp.rs
We should be able to specify the addresses of shotover nodes as a domain name.
This PR makes that possible by allowing the host name to be an arbitrary string.
> KafkaSinkCluster accept shotover addresses as domain names

- shotover/src/connection.rs
- shotover/src/transforms/cassandra/sink_cluster/topology.rs
- shotover/src/transforms/cassandra/sink_single.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_single.rs
- shotover/src/transforms/redis/sink_single.rs
This PR improves SinkConnection to be more robust and efficient. https://github.com/shotover/shotover-proxy/pull/1565 started on this work but I didnt realize how deep the issue went.
1. First I realized that the fix in #1565 only fixed try_recv. recv had the same issue and that was unfixed. So this PR adds the fix to `recv` as well.
2. I realized that fixing #1565 introduced a bunch of needless allocations. The fix to this is to have the user pass in the `&mut Vec<Message>` that they will be adding to. This is a fairly ergonomic solution since sinks often directly append the result to another vec anyway.
+ In doing this I renamed `recv` -> `recv_into` and `try_recv` -> `try_recv_into` to better suit the new functionality.
+ Additionally I had to port all the transforms to use this new …
> SinkConnection improvements

- docs/src/user-guide/observability.md
- shotover-proxy/tests/runner/observability_int_tests.rs
- shotover/src/codec/redis.rs
- shotover/src/server.rs
- shotover/src/transforms/chain.rs
- shotover/src/transforms/mod.rs
Progress towards https://github.com/shotover/shotover-proxy/issues/1507
The final PR for the removal of transform_pushed.
No users of transform_pushed remain so it can be just cleanly removed.
> Remove Transform::transform_pushed

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- test-helpers/src/connection/kafka/cpp.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
The typo of `partitions3` -> `paritions3` rendered the partitions3 case useless as it was only working with one partition.
This PR fixes that and also fixes the tests to actually work with a topic spread across 3 partitions for all tests using a single node kafka cluster.
multi node kafka clusters will be fixed in a follow up as they are hitting a more complicated issue.
It is fine to remove the old partition3 test case for multi node tests since it was effectively identical to the partition1 test case anyway.
In order to test a topic with 3 partitions we need a way to assert on records received out of order.
This is because kafka has no ordering guarantees across partitions and the producer can write each record to any partition when no key is provided.
And the test has a record with no …
> Fix kafka int tests with 3 partitions to actually use 3 partitions

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/test-configs/kafka/cluster-tls/topology.yaml
- test-helpers/src/cert.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
I've skipped support for the CPP driver for now, it should be possible ( https://github.com/fede1024/rust-rdkafka/issues/657 and https://github.com/confluentinc/librdkafka/wiki/Using-SSL-with-librdkafka ) but will require use of pem certs, so we'll need to do something like `use_tls(truststore: &str, ca_cert: &str)` to support both.
This PR extends `kafka_int_tests::cluster_tls` to cover both source and sink TLS.
In follow up PRs individual tests will be added for the source and sink as part of the SCRAM implementation.
> Kafka: end to end TLS integration test

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
Completes phase 0 of https://github.com/shotover/shotover-proxy/issues/1585
Our previous half-working implementation of session_id handling has been removed, it will be reintroduced in phases 1 and 2. Instead we just set session_id in fetch responses to 0 so the client will always send full requests starting a new session from scratch.
This PR introduces a system of splitting requests and merging their responses.
This is done by changing `PendingRequest` -> `PendingRequestTy` and making it a field of the new `PendingRequest` type.
This then allow us to add a `PendingRequest.combine_responses` field where a value of 1 indicates no responses to be combined and a higher value indicates how many responses should be combined into a single response.
Then we define the logic for splitting …
> KafkaSinkCluster: support topics with multiple partitions

- .config/nextest.toml
- .github/workflows/build_and_test.yaml
The latest nextest release now supports including extra files into the nextest archive: https://github.com/nextest-rs/nextest/issues/1340
Previously we were temporarily relying on a nextest fork to get this functionality but now we can swap back to upstream.
> Use upstream nextest

- docs/src/SUMMARY.md
- docs/src/dev-docs/debugging.md
- test-helpers/src/test_tracing.rs
Introduces some documentation on tracking down the cause of bugs aimed at absolute beginner shotover developers.
Includes shotover specific guidance as well as general rust guidance.
While writing the docs I noticed that shotover defaults to log level `INFO` while the integration tests default to log level `WARN`, rather than documenting the mismatch I just fixed it so that the integration tests log at INFO level.
> Add bug investigation docs

- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/redis_int_tests/mod.rs
- shotover/src/message/mod.rs
- shotover/src/server.rs
- shotover/src/transforms/cassandra/sink_cluster/rewrite.rs
- shotover/src/transforms/filter.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/null.rs
- shotover/src/transforms/tee.rs
This PR addresses a few issues:
* internal error response generation has been broken since the recent transform invariant refactorings.
+ To resolve this, internal error response generation is completely redone. A `PendingRequests` type is introduced to keep track of pending requests. It uses a different method for tracking depending on the protocol.
* flushing was triggering after internal error generation, this is bad since transforms do not attempt to maintain their internal invariants when returning an error.
+ To resolve this, I changed shotover to skip flushing if the chain was closed due to a transform error and additionally documented shotover's behavior here as a transform invariant.
* We were cloning entire messages which is a performance concern since, while its true that newly …
> Redo internal error response generation

- shotover/src/transforms/mod.rs
This code has been unused since we removed `Transform::transform_pushed`, lets get rid of it.
As a bonus, removing it reduces the size of `Wrapper` by 8 bytes.
I also removed `Transform::set_pushed_messages_tx` as I noticed we missed that too.
> Remove TransformIter

- .cargo/config.toml
- shotover-proxy/Cargo.toml
- shotover-proxy/benches/windsock/cloud/aws.rs
- shotover-proxy/benches/windsock/main.rs
- shotover-proxy/tests/kafka_int_tests/mod.rs
- test-helpers/Cargo.toml
- test-helpers/src/connection/kafka/mod.rs
- windsock-cloud-docker/src/container.rs
I'm proposing that rdkafka-driver-tests should be renamed to `kafka-cpp-driver-tests`, since its not obvious that rdkafka is the name of the cpp driver for kafka. 
This is more consistent with:
* the driver test abstractions which always refer to rdkafka as just `cpp`
* other similar features, we already have `cassandra-cpp-driver-tests`
> Rename feature `rdkafka-driver-tests` -> `kafka-cpp-driver-tests`

- docs/src/transforms.md
- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/node.rs
closes https://github.com/shotover/shotover-proxy/issues/1575
We recently concluded that SCRAM support is not feasible for KafkaSinkCluster.
The only way to achieve it would be to include username/password pairs within shotovers config, however that is very undesirable and largely defeats the purpose of SCRAM anyway.
As such I think the best way forward is to handle clients attempting to use SCRAM by telling them SCRAM is not enabled so that they may attempt to use another authentication method if it is enabled.
This PR does so and also performs some minor cleanup on general SASL handling.
If we do find a way to support SCRAM in the future I think this logic would still be useful to have as a fallback when the user has not configured passwords to enable SCRAM.
> KafkaSinkCluster disable SCRAM

- shotover-proxy/tests/runner/runner_int_tests.rs
- shotover-proxy/tests/test-configs/invalid_protocol_mismatch.yaml
- shotover/src/config/chain.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/redis/sink_single.rs
Progress towards https://github.com/shotover/shotover-proxy/issues/520
This PR improves topology validation and allows for new kinds of topologies:
* We now catch and report to the user when two protocol incompatible transforms are connected to each other. Previously this would just blow up at runtime with a confusing error.
* We now allow topologies like: `CassandraToRedisTransform` -> `Tee`
+ Previously this would have failed since Tee relies on the protocol type being correctly set in `TransformContextConfig` but the protocol was only set to the protocol of the source and any changes to the protocol via previous transforms was ignored.
Not sure if up chain and down chain are the clearest way to name these but I also cant think of anything better.
I considered incoming and outgoing but …
> Transforms declare supported protocols

- shotover/src/transforms/kafka/sink_cluster/mod.rs
Previously we were creating multiple coordinators per key.
The java driver does not like this and raises an exception, so this PR avoids doing that.
The comments in the code change do a pretty good job of explaining more details.
This issue showed up in the currently disabled `cluster_1_rack_multi_shotover::case_1_java` but I cant enable the test yet since there are still other deeper issues causing the test to fail.
> Fix FindCoordinatorResponse rewriting for java driver

- changelog.md
- custom-transforms-example/src/redis_get_rewrite.rs
- shotover/src/config/chain.rs
- shotover/src/config/topology.rs
- shotover/src/transforms/cassandra/peers_rewrite.rs
- shotover/src/transforms/cassandra/sink_cluster/mod.rs
- shotover/src/transforms/cassandra/sink_single.rs
- shotover/src/transforms/coalesce.rs
- shotover/src/transforms/debug/force_parse.rs
- shotover/src/transforms/debug/log_to_file.rs
- shotover/src/transforms/debug/printer.rs
- shotover/src/transforms/debug/returner.rs
- shotover/src/transforms/filter.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_single.rs
- shotover/src/transforms/load_balance.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/null.rs
- shotover/src/transforms/opensearch/mod.rs
- shotover/src/transforms/parallel_map.rs
- shotover/src/transforms/protect/mod.rs
- shotover/src/transforms/query_counter.rs
- shotover/src/transforms/redis/cache.rs
- shotover/src/transforms/redis/cluster_ports_rewrite.rs
- shotover/src/transforms/redis/sink_cluster.rs
- shotover/src/transforms/redis/sink_single.rs
- shotover/src/transforms/tee.rs
- shotover/src/transforms/throttling.rs
This PR adds up_chain_protocol and down_chain_protocol implementations for every transform, and then removes the default implementation for these methods, making them mandatory.
I renamed some of the variants since looking at them with fresh eyes today I can see some issues:
* `Sink` -> `Terminating` - A terminating transform is one that does not send messages down chain, while a sink is a transform that sends messages to a DB. A sink is always terminating but a terminating transform is not always a sink. So this should have been called terminating.
* `SameAsIncoming` -> `SameAsUpChain` - UpChain used to be called Incoming and I missed this when renaming everything.
> Make up_chain_protocol/down_chain_protocol mandatory

- Cargo.lock
- rust-toolchain.toml
- shotover/src/transforms/cassandra/sink_cluster/rewrite.rs
The clone_from changes are required due to a new clippy lint.
https://rust-lang.github.io/rust-clippy/master/index.html#/assigning_clones
> Update to rust 1.78 🦀🦀🦀

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- test-helpers/Cargo.toml
- test-helpers/src/connection/cassandra/cql_ws.rs
- test-helpers/src/connection/cassandra/mod.rs
We had some maintenance issues keeping this dependency in a repo. https://github.com/shotover/cql-ws
It's small enough that it can just be a module within our `test-helpers` crate. 
~~https://github.com/shotover/shotover-proxy/pull/1602 is a pre-req~~
> Move cql ws to shotover

- shotover/src/lib.rs
progress towards: https://github.com/shotover/shotover-proxy/issues/1615
We have long held the understanding that unsafe code should never go into the shotover crate itself.
With new contributors joining, lets make this rule explicit rather than implicit.
> deny unsafe_code in shotover

- ec2-cargo/src/main.rs
progress towards: https://github.com/shotover/shotover-proxy/issues/1615
Very minor fixes.
* reduce noise on startup by quietly unzipping awscli.
* we use anyhow for user facing errors in ec2-cargo so we need to disable RUST_LIB_BACKTRACE by default. We do the same thing already in shotover itself.
> Small ec2-cargo fix

- shotover-proxy/tests/lib.rs
- shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
- shotover-proxy/tests/redis_int_tests/mod.rs
progress towards https://github.com/shotover/shotover-proxy/issues/1615
the test `passthrough_redis_down` asserts that a specific error is returned by shotover when the redis instance is down.
Since mac os and linux have different error codes for connection refused the test passes on linux but fails on macos.
This PR fixes the test to also run on macos.
This is done by having a constant included into the assertion that is equal to `61` on macos and equal to `111` on all other OSs.
There are probably other OSs that this doesnt fix but thats fine, at this time we only care about linux and macos.
> Fix redis_int_tests::passthrough_redis_down on macos

- Cargo.lock
- docs/src/transforms.md
- shotover-proxy/benches/windsock/kafka/bench.rs
- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/topology-single.yaml
- shotover/Cargo.toml
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/node.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
closes https://github.com/shotover/shotover-proxy/issues/1600
Possibly useful resources:
* [SCRAM RFC](https://datatracker.ietf.org/doc/html/rfc5802)
* [SCRAM implementation for python kafka driver](https://github.com/dpkp/kafka-python/pull/1918/files)
This PR introduces a new optional config to `KafkaSinkCluster`:
```yaml
authorize_scram_over_mtls:
mtls_port_contact_points: ["172.16.1.2:9094"]
tls:
certificate_authority_path: "tests/test-configs/kafka/tls/certs/localhost_CA.crt"
certificate_path: "tests/test-configs/kafka/tls/certs/localhost.crt"
private_key_path: "tests/test-configs/kafka/tls/certs/localhost.key"
verify_hostname: true
```
The documentation added in `docs/src/transforms.md` explains what this feature does and why we want it, so please refer to it.
**In terms of …
> KafkaSinkCluster: authorize_scram_over_mtls

- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/node.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
progress towards: https://github.com/shotover/shotover-proxy/issues/1618
This PR is the first step towards a more robust scram_over_mtls implementation:
* It introduces a task that runs in the background and manages delegation tokens for all KafkaSinkCluster instances.
* The task currently just implements caching of tokens across all connections.
In the future the task will also be used for:
* detecting when tokens are ready to be used without a hardcoded sleep.
* recreating tokens before they expire
* prefetching all known tokens at startup
Since this task going down would leave the shotover instance in a very broken state:
* unwrap/panic is never used, instead an error is returned for all error cases.
* The task is wrapped in a loop that will restart the task from scratch if it …
> scram_over_mtls - phase2 - caching task

- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/topology-single.yaml
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
This PR replaces the hardcoded 4s wait with logic to check that all brokers have received the new delegation token.
This is done by sending a DescribeDelegationToken request to all brokers until we receive a response that contains the delegation token we just created.
This is done such that we confirm one node has received the token before moving onto the next node.
This minimizes requests sent.
Alternatively we could wait until one node has received the token. (a node that isnt the node we created the token on)
And then at that point send requests to all other nodes in parallel.
This will cut off a bit of latency in token creation.
If we need to improve latency in the future this would be useful to attempt, but I've left it out of this PR to keep this PR simple.
Further notes:
* A …
> Scram over mtls phase3 - proper token wait

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
This PR brings us closer to full support for the java driver.
The java driver integration tests that are currently disabled are now enabled but some of the test cases within those integration tests are still disabled.
This is done by calling a `minimal_test_suite` function and calling it when running the java driver.
The fixes to shotover was to handle prefetching topic metadata for fetches using the newer protocol version used by the java driver.
The new protocol specifies topics by their id instead of their name.
Previously we were only prefetching topic metadata by name but now we also do it by topic id.
This involved:
1. finding a list of all topic id's in the current message batch. (route_requests method)
2. Including these topic id's in the metadata request (get_metadata_of_topics …
> Fix Kafka java driver multi shotover tests

- shotover/src/transforms/kafka/sink_cluster/mod.rs
When we attempt to route a fetch request for which we have no record of its topic we issue a warning since it is impossible to route correctly.
We were previously including the topic name (`topic` field) in the warning but the kafka protocol has deprecated the topic name in favor of the topic uuid (`topic_id` field) .
This was resulting in warnings that look like:
`no known partition replica for topic "", routing message to a random node so that a NOT_LEADER_OR_FOLLOWER or similar error is returned to the client`
So this PR now uses the topic name if provided and fallsback to the topic id when needed.
> KafkaSinkCluster: Improve unknown topic warnings

- shotover/src/transforms/kafka/sink_cluster/node.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
This PR completes a TODO left in the code from https://github.com/shotover/shotover-proxy/pull/1626
[Delegation tokens](https://docs.confluent.io/platform/current/kafka/authentication_sasl/authentication_sasl_delegation.html) are created by a super user and allows a connection to kafka to authenticate as a specific user.
Shotover creates them to allow proxying scram connections which would otherwise be unable to be proxied.
The token task in scram_over_mtls.rs creates  delegation tokens when the transforms request them.
It will cache the token and fetch new tokens if they are not in the cache yet.
The tokens are stored in a type called `DelegationToken`.
This contains the `token_id` which acts as the tokens username and the `hmac` which acts as the tokens password. …
> Store delegation token hmac as base64

- shotover/src/transforms/cassandra/sink_cluster/mod.rs
CassandraSinkCluster has a really large `send_message` method, it should be broken down into multiple smaller functions.
To start with lets pull out the request routing logic into a `route_requests` method, this matches a function of the same name and purpose in `KafkaSinkCluster`.
The `send_message` function is also really poorly named but that should be addressed by moving the contents into `Transform::transform` which should occur in another PR to keep scope down.
The "Files changed" diff is very confusing and doesnt properly show the moving of the routing logic.
If you look at the individual commits you can see that the routing logic is removed and then readded as a separate function.
I recommend pasting the large chunk of logic that is removed and readded into a diff tool to verify …
> CassandraSinkCluster: pull routing logic into separate function

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/benches/benches/codec/kafka.rs
- shotover/src/codec/kafka.rs
This managed to avoid being hit because the test cases were running acks=0 last and never sending any more messages down those connections.
But while investigating https://github.com/shotover/shotover-proxy/pull/1588 this started showing up in the acks0 test case presumably because the java driver was reusing the connections it sent the acks=0 produce requests down.
Codecs are an optional helper mechanism provided by the `tokio_util` crate.
They make it easy to attach an implementation of a protocol to a TCP socket.
In shotover every database that we support has a unique codec implemented for its protocol.
There is no single `Codec` type, instead there are separate read and write codecs, called the [Encoder](https://docs.rs/tokio-util/latest/tokio_util/codec/trait.Encoder.html) and the …
> Kafka: fix producing with acks=0

- shotover/benches/benches/codec/cassandra.rs
- shotover/benches/benches/codec/kafka.rs
This PR makes the encoding microbenchmarks more realistic.
Once some messages have passed through shotover, the BytesMut passed into the codecs will enough have capacity for the average message. So its not realistic to test against a BytesMut with no allocation.
Additionally I'm hoping this will resolve the noisy benches that codspeed keeps reporting, since the variability in the bench is due to the BytesMut allocation.
> codec encode benches: reuse BytesMut

- shotover/src/transforms/kafka/sink_cluster/mod.rs
Completes Phase 1 in https://github.com/shotover/shotover-proxy/issues/1585
To improve the performance of `FetchRequests`, Kafka allows clients to create a "session" so the broker doesn't send unnecessary information over the network, i.e. topics or partitions that have unchanged since the last time the client received information about them.
This is done with a `session_id` that is sent with an `IncrementalFetchRequest` by the client to let the broker know it is part of a particular session.
`KafkaSinkCluster` currently sets the `session_id` to 0 before sending to the routed node because it's possible for Shotover to send a request with a `session_id` to a different broker to the one the session was created on, causing a `SessionIdNotFound` error.
Setting the `session_id` to 0 has the …
> KafkaSinkCluster disable session creation

- shotover/src/transforms/kafka/sink_cluster/mod.rs
Progress towards: https://github.com/shotover/shotover-proxy/issues/1526
With this PR shotover should now route all requests to their correct rack.
In order to catch misconfigurations, or even shotover bugs, a `shotover_out_of_rack_requests_count` metric is introduced to count out of rack requests.
This matches the `shotover_out_of_rack_requests_count` metric used in CassandraSinkCluster.
Fetch requests can be routed to any replica, some of which are in shotover's rack and some are outside of shotover's rack.
Previously we were just sending fetch requests to a random replica.
But with this PR we now always send to a replica within shotover's rack, unless such a replica does not exist in which case we fall back to any replica at all.
To make this routing cheap to perform at runtime, …
> KafkaSinkCluster: rack aware routing for fetch requests

- shotover/src/message/mod.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
This PR is a minor refactor of the scram over mtls task:
* `create_delegation_token_for_user` is renamed to `create_delegation_token_for_user_with_wait`
* And a new `create_delegation_token_for_user` is created which performs the actual token creation.
In order for the token creation logic to live in sub function, we need a way to take ownership of the parsed contents of a message so that we can return it.
So I added a `into_frame()` method on `Message` to allow for this.
Usually we cant take ownership of a message because we need to return it back to the client, but in this case shotover requested this message so its free to consume/destroy it if needed.
We could alternatively have just cloned the frame, but this approach is cheaper and I expect this method will be useful in the future …
> scram_over_mtls task minor refactor

- shotover-proxy/tests/cassandra_int_tests/cluster/mod.rs
- shotover/src/sources/cassandra.rs
- shotover/src/sources/kafka.rs
- shotover/src/sources/redis.rs
- shotover/src/tls.rs
- shotover/src/transforms/cassandra/sink_cluster/mod.rs
- shotover/src/transforms/cassandra/sink_single.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
- shotover/src/transforms/kafka/sink_single.rs
- shotover/src/transforms/redis/sink_single.rs
- shotover/src/transforms/util/cluster_connection_pool.rs
This PR changes the TLS connection builders (i.e., `TlsConnector::new` and `TlsAcceptor::new`) to use references to the TLS configs (i.e., `TlsConnectorConfig` and `TlsAcceptorConfig`) rather than clone the TLS config objects, which in theory should improve shotover performance to a slight extent.
Closes #1619.
> Make TLS connection builders take references to configs instead of cloning

- shotover/src/transforms/kafka/sink_cluster/mod.rs
closes https://github.com/shotover/shotover-proxy/issues/1526
I thought the `out_of_rack_requests` metric would need to be reported at the routing stage.
Which is why I left it for a follow up PR, I thought it was going to require modifications to all of our `route_to_*` methods.
But it turns out its far simpler to just report it at the sending stage, which is what this PR does.
We just compare the rack of the node we are about to send against shotover's rack and record the metric if there is a mismatch.
I left a `tracing::debug` at the previous location of `self.out_of_rack_requests.increment(1);` to help disambiguate why we are getting out of rack requests.
> KafkaSinkCluster: increment out_of_rack_requests metric for all out of rack requests

- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/lib.rs
Similar to https://github.com/shotover/shotover-proxy/pull/1617, this PR fixes the OS error code in `cassandra_int_tests::passthrough_cassandra_down` for macOS.
All the error messages of `Connection refused (os error ...)` should be using the OS-dependent `CONNECTION_REFUSED_OS_ERROR` now.
All the passthrough tests now pass on macOS.
Closes #1643
> #1643 Fix cassandra_int_tests::passthrough_cassandra_down on macOS

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/topology1.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/topology2.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/topology3.yaml
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
progress towards https://github.com/shotover/shotover-proxy/issues/1618
This PR:
* introduces a new integration test `cluster_sasl_scram_over_mtls_multi_shotover`, previously we just had `cluster_sasl_scram_over_mtls_single_shotover`
+ This tests with multiple shotover's running which could reveal some edge cases
+ It also uses various numbers of elements in `mtls_port_contact_points` for each shotover yaml, which will exercise different cases within the broker discovery logic
* Replaces the simple list of connections with a list of nodes.
+ This is needed so we can avoid creating duplicate connections and recreate connections if they go down.
* Adds a `find_new_brokers` method which performs broker discovery.
> KafkaSinkCluster: scram_over_mtls broker discovery

- Cargo.lock
- Cargo.toml
- shotover/Cargo.toml
This PR upgrades `cached` from 0.50 to 0.51, and `scylla` from 0.12 to 0.13.
`cargo upgrades` don't show `cached` and `scylla` anymore.
Closes #1622
> #1622 Upgrade cached and scylla

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
closes https://github.com/shotover/shotover-proxy/issues/1641
Make sure to enable "Hide Whitespace" when reviewing.
auto topic creation is an optional functionality of kafka enabled on the broker by `auto.create.topics.enable`.
When this is enabled, if a broker receives a produce request for a topic that does not exist, that topic is automatically created.
This PR makes two fixes:
* Do not fail the transform when an UnknownTopicOrPartition error occurs. This error is expected since the client can send unknown topics when performing auto topic creation.
* No longer report a warning when we route a produce request to a random node. Routing to a random node actually occurs in regular usage when auto topic creation is enabled, so warning is not appropriate here. Instead I reduced the warning …
> KafkaSinkCluster: run java driver against standard test suite

- docs/src/transforms.md
- shotover/src/transforms/kafka/sink_cluster/mod.rs
When running `cargo nextest run --no-default-features --features kafka kafka_int_tests::cluster_1_rack_single_shotover --nocapture` logs from the java driver can be observed complaining that leavegroup requests were not routed to the coordinator of the group.
This is because shotover is simply not performing that routing!
So this PR implements routing for LeaveGroup requests.
The fix can be confirmed by rerunning  `cargo nextest run --no-default-features --features kafka kafka_int_tests::cluster_1_rack_single_shotover --nocapture` and observing that the error level logs are gone now.
> KafkaSinkCluster: route LeaveGroup requests

- docs/src/user-guide/configuration.md
- docs/src/user-guide/observability.md
- shotover-proxy/tests/runner/observability_int_tests.rs
- shotover-proxy/tests/test-configs/shotover-config/config_metrics_disabled.yaml
- shotover/src/config/mod.rs
- shotover/src/runner.rs
This PR makes the field `observability_interface` optional in `configuration.yaml`. The Shotover metrics reporting will be disabled when this field is not specified.
A test function has been added to verify Shotover can still process Redis requests with metrics disabled. As discussed with @rukai, we don't need to check that querying the prometheus endpoint returns the error of connection refused because the endpoint address is not specified at all.
Closes #1611
> #1611 Allow disabling Shotover metrics

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/docker-compose.yaml
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
This PR pulls the majority of the changes out of https://github.com/shotover/shotover-proxy/pull/1651 since they require no code changes to land.
To support the new test cases, this PR first extends the kafka connection abstraction.
This abstraction abstracts over both the CPP driver and java driver.
For this PR we can get away with just supporting the java driver since the cpp driver doesnt support SCRAM and so we cant use it for this test anyway.
This PR adds:
* a `KafkaAdmin::describe_topic` method
+ we only care about checking if the describe request succeeded or failed, so we dont actually need to return any info on the topic. But we follow the structure of a proper describe_topic method so that it can be extended to a full implementation in the future if needed.
* a …
> KafkaSinkCluster scram_over_mtls - initial integration tests

- docs/src/transforms.md
- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/topology-single.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/topology1.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/topology2.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/topology3.yaml
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
This PR extends the token task to also recreate delegation tokens before they expire.
It exposes a new config option `delegation_token_lifetime_seconds` in the docs we give an example of
```yaml
delegation_token_lifetime_seconds: 86400 # 1 day
```
which is the recommended lifetime and the one we will be using internally.
Largely this config option was driven by my wanting a way to integration test this functionality without leaving a test running for 24 hours.
But I think its also going to be valuable for end users to tweak this value.
The queueing logic of new tokens to recreate is isolated into a RecreateTokenQueue type.
We then use a [tokio select](https://docs.rs/tokio/latest/tokio/macro.select.html) to await both the recreation queue and transform token requests.
We need to ensure …
> KafkaSinkCluster: scram_over_mtls - token recreation

- docs/src/dev-docs/setting-up-macos.md
https://github.com/chipmk/docker-mac-net-connect allows us to access docker containers by IP, which is a requirement of our clustered tests.
This PR documents installing docker-mac-net-connect as a requirement for running shotover's integration tests on mac os.
After following these instructions, my macbook is now passing all tests except for 2 cassandra tests. And excluding the tests for optional drivers enabled by `--features`
> Document running clustered tests on macos

- shotover-proxy/tests/redis_int_tests/mod.rs
- shotover/src/transforms/redis/sink_cluster.rs
This PR registers and stores the `Counter` instance in `RedisSinkCluster` instead of recreating the instance every time the method `send_error_response` is called.
Closes #1650
> #1650 RedisSinkCluster - Avoid recreating Counter

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/node.rs
This PR extends the test cases added in https://github.com/shotover/shotover-proxy/pull/1652
It introduces a very similar case, run on a fresh shotover instance but running the stages of the test in a different order, in an effort to find possible token usage edge cases.
In doing so it uncovered a race condition in shotover.
When parsing metadata responses, we were previously updating the local nodes list only when the node was new globally.
However this is incorrect, we may still need to update the local nodes list even if the node is not new globally.
So this PR fixes this issue by pulling `self.update_local_nodes()` out of the `if new {` statement.
I've also left in a debug implementation for KafkaNode since I've found that we often want to be able to include it in temporary debug logs …
> KafkaSinkCluster scram_over_mtls - full integration tests

- shotover/src/transforms/kafka/sink_cluster/mod.rs
We need to change our metadata response processing to store each partitions leader_epoch and make use of it when updating our partitions metadata state. 
We should only update a partition when the leader epoch in the response is newer (a smaller integer) than the existing epoch. This ensures that if we get the metadata from a node that is a bit out of date we dont regress the state of the metadata.
However in order to enable cleaning up of deleted partitions we should still delete partitions if missing in the response, since otherwise there would be no way to clean these up.
This PR implements this.
> KafkaSinkCluster: use leader_epoch

- shotover/benches/benches/chain.rs
This PR adds a benchmark function for QueryCounter which includes a chain of QueryCounter followed by Loopback. It sends several redis commands to trigger the increment of the QueryCounter metric.
Progress towards #1649
> #1649 Add a microbenchmark for QueryCounter

- rust-toolchain.toml
We update to new rust versions as they come out.
They have strong backwards compatibility guarantees so are very low risk.
But also provide faster compile times and new features.
> Update to rust 1.79 🦀🦀🦀

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
The kafka cluster has a lot of state that shotover must keep track of for routing purposes.
This includes things like which brokers are holding which partitions.
Currently shotover populates its internal records of this state but it has no way to invalidate these records.
This PR implements this missing invalidation.
To handle changes to the cluster we need to handle routing errors as these indicate that the cluster has changed. 
This PR handles the 3 kinds of routing errors as follows: 
* NOT_CONTROLLER set controller_broker to BrokerId(-1) 
* NOT_COORDINATOR remove group from group_to_coordinator_broker 
* NOT_LEADER_OR_FOLLOWER 
* remove topic from topic_by_name and topic_by_id 
* alternatively, if supported on this api version, immediately update topic_by_name/topic_by_id as per …
> KafkaSinkCluster - routing error handling

- shotover/src/transforms/query_counter.rs
Stores QueryCounter's `counter_name` as `&'static str` (i.e., leaks the `counter_name` string so that its memory allocation is not freed for the lifetime of the shotover process. This should improve shotover performance as it reduces cloning.
We can observe minor improvement in query_counter benchmark regarding allocating and freeing memory.
Progress towards #1649.
> #1649 Leak query counter name to improve QueryCounter performance

- shotover/benches/benches/chain.rs
While assisting with https://github.com/shotover/shotover-proxy/issues/1649 I noticed that our chain benches are slightly inaccurate in that they run the against a fresh transform chain every time.
In a more realistic scenario the chain is reused across requests and the transforms can cache values internally after processing requests that can be reused on the following request.
Due to the way criterion works we cant reuse the chain from the previous iteration of the bench.
So the best way to solve this is to send an unmeasured request batch through the chain during setup.
This ensures that each iteration of the bench will operate on a chain which has had exactly one request batch pass through it already.
For the query_counter bench it will be useful to measure in both ways, so I've split …
> chain microbenchmarks: run the chains once before benching to avoid measuring init time

- shotover/src/transforms/query_counter.rs
This PR stores the query counters in a HashMap and reuses them when processing messages instead of registering query counters in every transform. According to the benchmark report, `query_counter_pre_used` gains 14% improvement thanks to the faster `transform`.
`query_counter_fresh` becomes a bit slower but it's expected because the first transform runs create the counters and insert them into the hashmap.
Progress towards #1649
> #1649 Reuse query counters

- Cargo.lock
- shotover/Cargo.toml
- shotover/src/transforms/query_counter.rs
This PR upgrades the metrics + metrics-exporter-prometheus dependencies, and is the last task of https://github.com/shotover/shotover-proxy/issues/1649.
> #1649 Upgrade metrics + metrics-exporter-prometheus dependencies

- shotover/src/transforms/kafka/sink_cluster/mod.rs
This PR clears the optional fields `FetchResponse::node_endpoints`, `PartitionData::preferred_read_replica` and `PartitionData::current_leader` in the Fetch response processed by the KafkaSinkCluster `process_responses()` function . This is to avoid passing these values to the client which will make the client try to bypass shotover and connect to Kafka brokers directly.
Closes #1665
> #1665 Clear optional fetch response fields to avoid making clients try to bypass shotover

- shotover/src/transforms/kafka/sink_cluster/mod.rs
This PR clears the optional fields `ProduceResponse::node_endpoints` and `PartitionProduceResponse::current_leader` in the Produce response processed by the KafkaSinkCluster `process_responses()` function . This is to avoid passing these values to the client which will make the client try to bypass shotover and connect to Kafka brokers directly.
Closes https://github.com/shotover/shotover-proxy/issues/1664
> #1664 Clear optional produce response fields to avoid making clients try to bypass shotover

- shotover-proxy/tests/cassandra_int_tests/cluster/single_rack_v4.rs
- shotover-proxy/tests/cassandra_int_tests/collections/mod.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/cassandra_int_tests/prepared_statements_all.rs
- shotover-proxy/tests/cassandra_int_tests/routing.rs
- test-helpers/src/connection/cassandra/connection.rs
- test-helpers/src/connection/cassandra/connection/cdrs.rs
- test-helpers/src/connection/cassandra/connection/cpp.rs
- test-helpers/src/connection/cassandra/connection/scylla.rs
This PR only changes test code.
This PR contains no functional changes to the tests.
`cassandra/connection.rs` is split up into connection.rs, scylla.rs, cdrs.rs and cpp.rs.
This is done by introducing `ScyllaConnection`, `CdrsConnection` and `CppConnection` types that hold all wrapping logic for each driver.
I attempted to keep this as straightforward as possible, however there were some important renames that needed to be done, so I included those in this PR.
The renames include:
* CdrsTokio -> Cdrs - Shortened form since we write this so much
* datastax -> cpp - while the driver is written by datastax, so is other drivers, so its a bit ambiguous. Cpp matches the naming style used by the kafka drivers abstraction.
* Types like `ScyllaBatch` are renamed to just `Batch` since its no …
> Splitup cassandra connection abstraction

- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls/create_token.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls/recreate_token_queue.rs
This PR splits up the original monolithic module `scram_over_mtls` into submodules `recreate_token_queue` and `create_token` in order to prepare for the improvement on token handling in https://github.com/shotover/shotover-proxy/issues/1667. It doesn't change the functionality of the module `scram_over_mtls`.
Closes #1656
> #1656 Split up scram_over_mtls module into submodules

- Cargo.lock
- test-helpers/Cargo.toml
- test-helpers/src/connection/java.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/mod.rs
The j4rs java interop crate is quite flexible but it allows for a few things which bring us no value:
* working with multiple JVM's
+ We only use a single JVM
* returns a Result<T, E> on every operation that touches the JVM in case the jvm explodes
+ In this case the only reasonable thing for us to do is panic.
* Differentiates between values returned from java `Instance` and values that will be sent into java `InvocationArg`
+ I believe this is done for performance reasons, but we dont need to be concerned about that level of performance since this is an integration test
All of these features were causing great complexity for our java driver integration tests, so I introduced a wrapper that does not expose the above features.
It reduces the lines of code used to implement the kafka java …
> Introduce j4rs wrapper to simplify testing java drivers

- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/node.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls/create_token.rs
This PR removes the field `delegation_token` from the struct `AuthorizeScramOverMtls` to avoid caching the token in `AuthorizeScramOverMtls` instances. Instead, we store the username used to generate delegation tokens in this struct and fetch the delegation token from the `TokenTask` every time it's needed.
Progress towards #1667
> #1667 Remove cached delegation token from AuthorizeScramOverMtls

- Cargo.lock
- shotover/Cargo.toml
- test-helpers/Cargo.toml
This PR:
* Updates j4rs, I need features in the newer version for my cassandra driver work.
* Updates dashmap, I noticed the new version had some performance improvements so I'm updating it now.
* Ran `cargo update` as part of general maintenance.
I left other trivial updates in https://github.com/shotover/shotover-proxy/issues/1648 since they are not needed now and can be kept around as a good first issue for rony.
> Update dashmap + j4rs

- shotover-proxy/tests/cassandra_int_tests/collections/mod.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover-proxy/tests/cassandra_int_tests/prepared_statements_all.rs
- test-helpers/src/connection/cassandra/connection.rs
- test-helpers/src/connection/cassandra/connection/java.rs
- test-helpers/src/connection/java.rs
This PR implements support for the cassandra java driver for a subset of our cassandra integration tests:
* passthrough_standard
* passthrough_encode
* cassandra_redis_cache
* cassandra_5
Other tests do not run with the cassandra driver due to missing features in the cassandra driver abstraction.
We can come back to these at a later time.
`NATIVE_COL_TYPES` becomes `fn supported_native_col_types` so that we can disable the Decimal and Varint types for the cassandra driver.
We will need to do some complex refactoring to enable those types in the cassandra driver, so its left out of scope of this PR.
Again, since we cant support decimal from the java driver right now we avoid testing decimals in prepared_statement_all.rs like we already do for the cpp driver.
Various functionality of the …
> Add cassandra java driver to test suite

- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
closes https://github.com/shotover/shotover-proxy/issues/1667
This PR is to add a comment to the token task in scram_over_mtls about not bing able to expire other users' delegation tokens at the moment. See more details in https://github.com/shotover/shotover-proxy/pull/1685.
> Add comment on not being able to expire other users' delegation tokens 

- docs/src/dev-docs/contributing.md
- docs/src/dev-docs/setting-up-macos.md
This PR adds a tip on making [docker-mac-net-connect](https://github.com/chipmk/docker-mac-net-connect) work on macs with ARM CPUs.
> Add a tip on docker-mac-net-connect

- shotover-proxy/tests/cassandra_int_tests/collections/mod.rs
- shotover-proxy/tests/cassandra_int_tests/collections/vector.rs
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover/src/frame/value.rs
- shotover/src/frame/value/cassandra.rs
- shotover/src/frame/value/redis.rs
- test-helpers/src/connection/cassandra/connection/java.rs
- test-helpers/src/connection/cassandra/result_value.rs
- test-helpers/src/connection/java.rs
This PR fixes a bug causing shotover to error out when processing cassandra custom types.
In doing so we enable support for cassandra 5's new vector types.
The problem is that the cassandra-protocol crate will return an Error when it tries to parse a Custom cassandra value, this makes sense from the perspective of the crate since it does not know how to handle this type. If the user wants to use the custom type they should use a driver that knows about this type.
However from the shotover perspective its reasonable for the client and cassandra to use a custom type that shotover knows nothing about, in this case we should just pass on the bytes as is.
To achieve this we add an enum `CustomOrStandardType` which allows us to store either a Custom type (not supported by cassandra-protocol) or …
> Cassandra 5 vector support

- .gitignore
- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/node.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
- test-helpers/src/connection/kafka/mod.rs
- test-helpers/src/connection/kafka/node.rs
- test-helpers/src/connection/kafka/node/index.js
- test-helpers/src/connection/kafka/node/package-lock.json
- test-helpers/src/connection/kafka/node/package.json
The exact difference in behaviour is that all the existing drivers will always send an ApiVersions request as the first request when opening a new connection.
However the sarama and kafkajs driver will sometimes skip the ApiVersions request when opening a connection. This is valid use of the protocol and its a bug in shotover that we are not handling this case properly.
Skipping the ApiVersions request resulted in shotover attempting to open the first outgoing connection of an incoming connection using a delegation token, this failed since we havent yet gathered the username required for creating a delegation token.
The fix here is to only use token auth when OriginalScramState::AuthSuccess.
If we are in any other state we should perform no handshake.
Along with the fix, this PR also …
> Fix sarama and kafkajs drivers

- ec2-cargo/src/main.rs
- shotover-proxy/build/install_ubuntu_deps.sh
We have recently added external dependencies for our integration tests and were not careful about updating scripts that need to install them.
So this PR:
* Adds jre + npm to ec2-cargo installed deps
* Adds npm to install_ubuntu_deps.sh script
> Install new deps in cargo-ec2

- Cargo.lock
- ec2-cargo/readme.md
- ec2-cargo/src/main.rs
- shotover-proxy/benches/windsock/cloud/aws.rs
This allows us to use ec2-cargo and windsock on our internal aws accounts.
For now I'm happy to hardcode `us-east-1b` since we are an unusual case where `us-east-1c` is not suitable.
I also added a readme.md to document how to use ec2-cargo.
@justinweng-instaclustr you should give this a go to make sure it works for you.
Note that cassandra tests currently fail on arm due to lack of support from the docker image we use.
So if using the default arm instance, I would just run the kafka tests.
> Set aws-throwaway AZ

- shotover/Cargo.toml
https://github.com/shotover/shotover-proxy/pull/1564 accidentally disabled tls 1.2 by setting `default-features = false` and not manually reenabling the `tls12` feature.
This PR fixes that by reenabling the `tls12` feature
> Enable tls 1.2

- shotover/src/transforms/kafka/sink_cluster/mod.rs
While investigating the current state of KafkaSinkCluster for designing a system to handle down kafka nodes, I noticed that it could do with some minor cleanup:
* I added some comments to explain whats going on in recv_responses
* process_sasl_authenticate has no need to be async, so async is removed.
> Minor KafkaSinkCluster cleanup

- shotover/src/transforms/mod.rs
The transforms module is a core part of our public API, so it should be well documented.
This PR adds documentation for many missing fields.
I noticed `TransformContextConfig::protocol` should really be named `TransformContextConfig::up_chain_protocol` but I have not renamed it because that would force us into shotover 0.5 so soon after 0.4, so I left a TODO instead.
> Add missing documentation to transforms module

- shotover-proxy/tests/test-configs/cassandra/cassandra-5/docker-compose.yaml
- shotover-proxy/tests/test-configs/cassandra/cluster-v5/docker-compose.yaml
- test-helpers/src/docker_compose.rs
Actually use the new image added by https://github.com/shotover/cassandra-test-images/pull/7
> Cassandra 5.0 beta1 -> rc1

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover/Cargo.toml
Needed for https://github.com/shotover/shotover-proxy/pull/1696
May as well wait for https://github.com/shotover/shotover-proxy/pull/1693 as well.
> Release shotover 0.4.1

- shotover/src/transforms/kafka/sink_cluster/mod.rs
This is reduces the need for reallocating and parsing address strings by moving the conversion from string into KafkaAddress into the TransformBuilder creation stage instead of the Transform creation stage.
It is also a prereq to https://github.com/shotover/shotover-proxy/pull/1703
> KafkaSinkCluster: store first_contact_points as KafkaAddress

- shotover/src/transforms/kafka/sink_cluster/mod.rs
Reduce boilerplate for implementing routing logic.
Slight improvement to the current codebase, but will be even more useful for https://github.com/shotover/shotover-proxy/pull/1703
> KafkaSinkCluster add constructor for PendingRequestTy::Routed

- Cargo.lock
- Cargo.toml
- shotover/Cargo.toml
- shotover/src/transforms/kafka/sink_cluster/node.rs
To work around missing features in the sasl crate while implementing the scram_over_mtls functionality, I published a temporary fork of the sasl crate for shotover to use while the functionality was being upstreamed.
I used the git commit hash as the name of the crate instead of inventing a reasonable to avoid polluting the crates.io namespace with a more useful name https://crates.io/crates/a8da96aa9ee5ce956b7069f92a4ca762efc75133
Since then the [upstream sasl crate](https://crates.io/crates/sasl) has a released a new version: 0.5.2
This PR swaps to this new version, there is a small breaking change since the upstreamed version ended up deviating from the initial implementation used in our fork.
In addition, this PR also removes unneeded features enabled in tokio for the shotover crate. …
> Move to upstream sasl crate + remove unneeded tokio features

- Cargo.lock
- shotover/Cargo.toml
- test-helpers/Cargo.toml
- test-helpers/src/connection/cassandra/cql_ws.rs
rustls needs to be updated at the same time since its part of tokio-tungstenite's public API
Changes might look complicated but they are entirely within test logic and is the equivalent to the upgrade we did within shotover itself in https://github.com/shotover/shotover-proxy/pull/1387
> Update tokio-tungstenite and rustls in test-helpers

- shotover/src/transforms/kafka/sink_cluster/node.rs
I used the wrong type for this field in https://github.com/shotover/shotover-proxy/pull/1703 and didnt realize until I went to use it.
Calling clone on a box will clone the contents of the box as well which is not what we want.
What we want is an Arc, which will not clone its contents and instead share the contents between all its clones via reference counting.
> Fix KafkaNode state field type

- .github/workflows/license_check.yaml
We use cargo-deny to ensure that we only depend on licenses that are compatible with shotovers apache license.
The [latest release](https://github.com/EmbarkStudios/cargo-deny/releases/tag/0.16.0) of cargo-deny includes breaking changes to the configuration and we werent pinning the version of cargo-deny that we use.
This results in CI being broken since the last release of cargo-deny.
Oops.
This PR fixes CI by pinning the version of cargo-deny to the last release our config is compatible with.
> Fix cargo-deny

- shotover/src/transforms/coalesce.rs
prereq for https://github.com/shotover/shotover-proxy/pull/1717
1717 requires changes to these tests that will become a lot easier if avoid the duplication in the tests
> Cleanup coalesce transform tests

- custom-transforms-example/src/redis_get_rewrite.rs
- shotover/benches/benches/chain.rs
- shotover/src/server.rs
- shotover/src/transforms/cassandra/peers_rewrite.rs
- shotover/src/transforms/cassandra/sink_cluster/mod.rs
- shotover/src/transforms/cassandra/sink_single.rs
- shotover/src/transforms/chain.rs
- shotover/src/transforms/coalesce.rs
- shotover/src/transforms/debug/force_parse.rs
- shotover/src/transforms/debug/log_to_file.rs
- shotover/src/transforms/debug/printer.rs
- shotover/src/transforms/debug/returner.rs
- shotover/src/transforms/filter.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_single.rs
- shotover/src/transforms/load_balance.rs
- shotover/src/transforms/loopback.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/null.rs
- shotover/src/transforms/opensearch/mod.rs
- shotover/src/transforms/parallel_map.rs
- shotover/src/transforms/protect/mod.rs
- shotover/src/transforms/query_counter.rs
- shotover/src/transforms/redis/cache.rs
- shotover/src/transforms/redis/cluster_ports_rewrite.rs
- shotover/src/transforms/redis/sink_cluster.rs
- shotover/src/transforms/redis/sink_single.rs
- shotover/src/transforms/tee.rs
- shotover/src/transforms/throttling.rs
This PR reduces the overhead of shotover's transform/chain abstractions by passing `Wrapper` by reference instead of by value.
Passing by value is usually not a performance issue in rust.
However, in this case quite a few things collided to create a minor performance issue:
* `Wrapper` is quite large, taking up 80 bytes on the stack. A large contributor to this is the `local_addr: SocketAddr` field which is 32 bytes.
* `Transform::transform is an async function and async functions need to store and restore the state of all variables across await points. If these variables are larger, then it is more expensive to perform this store+restore.
* Being part of the public API of `shotover` crate and also being part of a trait implementation that is called as a `Box<dyn ..>` trait object means …
> Pass in Wrapper as &mut

- changelog.md
- custom-transforms-example/src/redis_get_rewrite.rs
- shotover/src/transforms/cassandra/peers_rewrite.rs
- shotover/src/transforms/cassandra/sink_cluster/mod.rs
- shotover/src/transforms/cassandra/sink_single.rs
- shotover/src/transforms/chain.rs
- shotover/src/transforms/coalesce.rs
- shotover/src/transforms/debug/force_parse.rs
- shotover/src/transforms/debug/log_to_file.rs
- shotover/src/transforms/debug/printer.rs
- shotover/src/transforms/debug/returner.rs
- shotover/src/transforms/filter.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_single.rs
- shotover/src/transforms/load_balance.rs
- shotover/src/transforms/loopback.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/null.rs
- shotover/src/transforms/opensearch/mod.rs
- shotover/src/transforms/parallel_map.rs
- shotover/src/transforms/protect/mod.rs
- shotover/src/transforms/query_counter.rs
- shotover/src/transforms/redis/cache.rs
- shotover/src/transforms/redis/cluster_ports_rewrite.rs
- shotover/src/transforms/redis/sink_cluster.rs
- shotover/src/transforms/redis/sink_single.rs
- shotover/src/transforms/tee.rs
- shotover/src/transforms/throttling.rs
Fixes some issues with https://github.com/shotover/shotover-proxy/pull/1724/files
I found that trying to use Wrapper after it was borrowed by `Transform::transform` was impossible.
That is:
```rust
let mut wrapper = Wrapper::new();
// this line is fine by itself
transform.transform(&mut wrapper);
// but this line fails to compile due to the above line holding onto the reference forever.
println!("{:?}", wrapper.requests);
```
This is very strange since after `transform.transform(&mut wrapper)` the reference to the wrapper should be dropped and we should be able to use wrapper again.
However it turns out this is expected behavior.
I found this article helpful in explaining why exactly this was occurring.
https://tfpk.github.io/lifetimekata/chapter_4.html
The article suggests using …
> Fix transform lifetimes

- shotover-proxy/benches/windsock/profilers/samply.rs
This PR fixes the currently broken CI.
e.g. https://github.com/shotover/shotover-proxy/pull/1723 -> https://github.com/shotover/shotover-proxy/actions/runs/10444413933/job/28918919779?pr=1723
Samply is an external tool used for profiling, our benchmarks automatically install the tool if its not already installed.
We started hitting compilation issues when building/installing samply due to a semver violation by one of it dependencies.
The addition of `--locked` fixes the compilation error by forcing it to use the versions specified in its Cargo.lock file.
I confirmed this  fixes the issue in this instance and should prevent future issues of this kind.
I also updated the installed commit to the latest commit of samply to `75a8971b4291db8091a346431a1727ffcec4f038`, in order to pull in any …
> Fix CI by installing samply with --locked

- shotover/src/server.rs
This PR:
* pulls changes out of https://github.com/shotover/shotover-proxy/pull/1722
* Is purely a refactor - the logic remains exactly the same
There are a few renames:
* `process_messages` -> `run_loop`
+ process_messages is confusing since we already have a `.process` method and its not clear what the difference is.
- the difference is that it runs the chain in an infinite loop. So better to name it after the `run` method that calls it and add `_loop`
+ `send_receive_chain_loop` could also be a reasonable name
* `process` -> `send_receive_chain`
+ it takes requests as args and sends them down the chain, sending the response to the client, so this rename makes it clear what exactly is being processed.
The main point of the PR is to move sending of responses into `send_receive_chain`.
To …
> server.rs - move response handling into .process()

- shotover/src/server.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/mod.rs
In order for shotover to properly recreate the behavior of certain databases it needs to be able to close incoming connections from the client.
Databases will close the connection on the client if it misbehaves, this can include things like failed auth and sending requests that cannot be parsed according to the databases wire protocol.
We need to be able to recreate this behavior to avoid subtle differences in behavior between shotover and the database.
Shotover currently lacks a way for a transform to close the incoming connection to the client.
This is a problem since cluster sink transforms need to be able to close the connection since they need to emulate a chunk of the servers behavior.
This PR fills this missing hole in the API shotover exposes to transforms and makes use of this …
> Add Wrapper::close_client_connection

- changelog.md
- custom-transforms-example/src/redis_get_rewrite.rs
- shotover/benches/benches/chain.rs
- shotover/src/server.rs
- shotover/src/transforms/cassandra/peers_rewrite.rs
- shotover/src/transforms/cassandra/sink_cluster/mod.rs
- shotover/src/transforms/cassandra/sink_single.rs
- shotover/src/transforms/chain.rs
- shotover/src/transforms/coalesce.rs
- shotover/src/transforms/debug/force_parse.rs
- shotover/src/transforms/debug/log_to_file.rs
- shotover/src/transforms/debug/printer.rs
- shotover/src/transforms/debug/returner.rs
- shotover/src/transforms/filter.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_single.rs
- shotover/src/transforms/load_balance.rs
- shotover/src/transforms/loopback.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/null.rs
- shotover/src/transforms/opensearch/mod.rs
- shotover/src/transforms/parallel_map.rs
- shotover/src/transforms/protect/mod.rs
- shotover/src/transforms/query_counter.rs
- shotover/src/transforms/redis/cache.rs
- shotover/src/transforms/redis/cluster_ports_rewrite.rs
- shotover/src/transforms/redis/sink_cluster.rs
- shotover/src/transforms/redis/sink_single.rs
- shotover/src/transforms/tee.rs
- shotover/src/transforms/throttling.rs
The name `Wrapper` can be traced back to the beginning of time.
Its not a very useful name and doesnt really mean anything at all.
Lets rename it to `ChainState` since it holds various state about the chain that the transform is in.
> rename Wrapper -> ChainState

- shotover/src/transforms/mod.rs
avoids the possibility of runtime panic due to unwrap, which allows the optimizer to go harder.
Super minor performance improvement I doubt it will show up in any benchmarks, but it did reduce the size of the compiled binary by 2KB.
It also changes the address to 0.0.0.0:0 which is more clearly a dummy address.
> use const address for wrapper flush

- shotover/benches/benches/chain.rs
- shotover/src/config/chain.rs
- shotover/src/server.rs
- shotover/src/transforms/mod.rs
- shotover/src/transforms/parallel_map.rs
- shotover/src/transforms/redis/cache.rs
- shotover/src/transforms/tee.rs
This was left as a TODO to avoid breaking changes, since then we found the need for breaking changes anyway, so lets make the change now.
> Rename TransformContextConfig::protocol -> up_chain_protocol

- shotover/src/transforms/kafka/sink_cluster/connections.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls/connection.rs
Currently KafkaSinkCluster ignores failures to receive messages:
https://github.com/shotover/shotover-proxy/blob/17ccad5e257bf06836283ad8c49970b3dd63e749/shotover/src/transforms/kafka/sink_cluster/mod.rs#L1041
This is quite bad since many kinds of issues are silently ignored, none of our other transforms behave this way.
This PR fixes this by bubbling up errors when receiving from a connection.
However, there are a few latent issues hidden by the lack of error handling here:
* https://github.com/shotover/shotover-proxy/pull/1722
* recreate connections before the delegation token expires - done in this PR.
These must be resolved before we can enable handling of receive errors.
When scram_over_mtls is enabled, connections will be closed when the token it auth'd with expires.
This PR …
> KafkaSinkCluster - handle receive errors

- shotover/src/transforms/kafka/sink_cluster/connections.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/node.rs
This PR:
* sets the `KafkaNode::state` field to `NodeState::Down` whenever a connection error is encountered.
+ This sets us up to make use of that fields value as part of our routing logic in a follow up PR.
* recreates lost connections where it is safe to do so.
+ send - never recreate lost connections on send, since we cant tell if the sent message was received or not. Possibly in the future we could recreate lost connections in certain conditions. But its not really important.
+ receive - never recreate lost connections on receive, we only check for received messages if they are pending, and if there were pending responses we would not be able to recreate the connection.
+ control_send_receive - we can recreate connections as needed. Since control connections are used for metadata …
> KafkaSinkCluster - set KafkaNode::state

- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/node.rs
A helper method `random_broker_id` is added since this is such a common operation that needs to be done.
> KafkaSinkCluster: when choosing a random broker prioritize up nodes

- shotover/src/transforms/kafka/sink_cluster/mod.rs
Previously we were exposing internal cluster BrokerId's to the client.
However these need to be rewritten to the BrokerId's used by the shotover instances.
This PR introduces the required message rewriting logic.
The `isr_nodes` (in-sync-replica nodes) can follow the same logic as `replica_nodes`, so the logic is just copied over from there.
> KafkaSinkCluster - improve metadata response rewriting

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- test-helpers/src/connection/kafka/cpp.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
This was a missing test case that upon implementation revealed a bug in shotover.
Since we cannot create a topic with replication_factor 3 on a kafka cluster with only 1 node, `cluster_test_suite` is introduced for the cluster tests to use without regressing the single/passthrough tests.
To get the tests to pass we required:
* one change to the test logic - we need to set produce [acks](https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html#acks) to "all"
+ It kind of makes sense in that, adding replicas means that there is now a difference in behavior between `acks=1` and `acks=all`, acks=1 will not wait for the replicas to acknowledge the produced record.
+ On the other hand I'm not entirely sure why we need it since an ack from the leader should be …
> Test kafka with replication_factor 3

- docs/src/dev-docs/contributing.md
We document the dependencies as if the user were running `-p shotover-proxy` to build a final binary, but we never actually instruct the user to include that flag.
> Document that `-p shotover-proxy` should be used when building for shipping

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- test-helpers/src/connection/kafka/cpp.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
I wrote this test case to try to reproduce an issue were we were hitting sequence out of order errors.
It turns out that issue was only occurring in a very old version of shotover, but this integration test represents a unique case that is worth testing, so lets land it.
This PR also renames the topics `batch_test_partitions_*` -> `multi_topic_batch_partitions_*` to extend the naming scheme to include the new topics introduced by this PR.
> KafkaSinkCluster - add multi_partition integration test case

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover-proxy/tests/test-configs/kafka/cluster-1-rack/docker-compose-short-idle-timeout.yaml
- shotover/src/connection.rs
- shotover/src/transforms/kafka/sink_cluster/connections.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls/connection.rs
- test-helpers/src/connection/kafka/mod.rs
Kafka brokers have a config field `connections.max.idle.ms`, when a connection has been idle for longer than this timeout.
Normally a client can expect idle connections to timeout after some time of being unused.
However when KafkaSinkCluster is sitting in between the client and the broker there can be some unexpected behaviour.
For example:
1. We have a kafka cluster configured with `connections.max.idle.ms=5s`.
2. A client sends a request every 1s.
3. Shotover routes the first request to node A
4. Shotover routes the next 10 requests to node B
5. Shotover routes another request to node A
+ this request will fail due to the connection hitting idle time out even though the client was sending one request per second, well within the timeout!
With more reasonable timeout values this issue is …
> KafkaSinkCluster: handle broker closing connection due to idle timeout

- .github/workflows/windsock_benches.yaml
- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover-proxy/benches/windsock/kafka/bench.rs
- shotover-proxy/benches/windsock/kafka/mod.rs
Updates to latest windsock, making use of the new consumer latency functionality.
To calculate the consumer latency we:
* serialize the current `SystemTime` in the first 12 bytes of the produced record payload
* take those bytes from the consumed record payload and turn them back into a `SystemTime` then call `.elapsed()` to determine the amount of time passed.
This matches the behaviour of rdkafka_performance: https://github.com/confluentinc/librdkafka/blob/master/examples/rdkafka_performance.c
I did not use a serialization library for this as I need to ensure they fit exactly into 12 bytes so we know what our minimum size of payload needs to be.
As a result of the new minimum of 12 bytes, the existing 1B bench case was turned into a 12B bench case.
> windsock: measure consume latency

- docs/src/user-guide/observability.md
- shotover-proxy/tests/runner/observability_int_tests.rs
- shotover/src/server.rs
Opening new connections is quite expensive on kafka, not only do we have to reperform authentication, the new transform instance created for this new connection must fetch its own metadata from kafka.
To give visibility into this I have added this `connections_opened` metric which increments every time a new connection is opened.
The results of this metric on the windsock benchmark:
We can see that
* we initially create 4 connections, presumably 2 for the producer and 2 for the consumer.
* after that no more connections are created
So we can conclude that the performance issues is not caused by the client creating more connections.
I believe this metric should still be added as its helpful for ruling out such possibilities in the future.
> Add connections_opened metric

- docs/src/user-guide/observability.md
- shotover-proxy/tests/runner/observability_int_tests.rs
- shotover/src/transforms/chain.rs
Every time shotover processes a transform chain, multiple requests and responses are batched and processed together.
This can be seen by the ChainState, which is passed through each transform in the chain, [containing multiple requests](https://github.com/shotover/shotover-proxy/blob/4693aab8b6f1a4bdcc5cfdf6789860d34baede73/shotover/src/transforms/mod.rs#L151).
This batching is purely opportunistic, we don't intentionally wait for requests or responses but if there are multiple requests or responses pending at the time we go to process them then they will be all processed in a single batch.
Lets call this batch a "chain batch".
Shotover has an existing metric `shotover_chain_messages_per_batch_count` which measures the number of requests included in a chain batch.
At the time this metric …
> fix `shotover_chain_messages_per_batch_count` metric

- shotover/src/transforms/kafka/sink_cluster/mod.rs
PendingRequestTy was always a bad name.
PendingRequestState is more accurate since this value is used to maintain the current state of the pending request.
This rename will free up the name PendingRequestTy to be used by something else I am working on.
> rename PendingRequestTy -> PendingRequestState

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- test-helpers/src/connection/kafka/cpp.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
Add integration test cases for `fetch.min.bytes` and `fetch.wait.max.ms`.
We will be implementing logic to adhere to these values in https://github.com/shotover/shotover-proxy/pull/1756 so we want to make sure that we have some coverage of them. This PR can be merged first since we dont have any correctness issues with these values, only performance issues.
Since we have two new fields that we want to be able to configure the consumer with, its time that we refactor `connect_consumer` to use the builder pattern instead of creating argument soup.
> Add integration tests for fetch.min.bytes and fetch.wait.max.ms

- shotover-proxy/benches/windsock/kafka/bench.rs
- shotover/src/transforms/kafka/sink_cluster/connections.rs
- shotover/src/transforms/kafka/sink_cluster/kafka_node.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls/create_token.rs
- shotover/src/transforms/kafka/sink_cluster/shotover_node.rs
- Add a new `ShotoverNodeState` field to `ShotoverNode`. We are not reusing the existing `NodeState` for Kafka because it's possible that we will have different node states for Shotover in the future.
- Add a new configuration `check_shotover_peers_delay_ms` to `KafkaSinkCluster` which will be used when checking connection to nodes and setting node states.
- Move `ShotoverNode` code into a new file `kafka/sink_cluster/shotover_node.rs`
- Rename `kafka/sink_cluster/node.rs` to `kafka/sink_cluster/kafka_node.rs` and `NodeState` to `KafkaNodeState`
> Add NodeState to ShotoverNode + some renaming

- shotover-proxy/tests/test-configs/kafka/cluster-1-rack/topology2.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-1-rack/topology3.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-2-racks/topology-rack2.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-plain/topology2.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-plain/topology3.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/topology2.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/topology3.yaml
Copied from Lucas's comment below:
The `local_shotover_broker_id` field is currently only used for rack aware routing.
We weren't correctly setting it in our integration tests, the tests still passed since rack aware routing is purely an optimization and not needed for correctness.
We really should fix these configs so that we are running our integration tests with a configuration closer to production.
The way the field works is it configures the broker id that shotover should become.
Shotover looks up the entry in `shotover_nodes` that has that broker id and acts as that node.
> Fix local_shotover_broker_id in test configs

- shotover/src/message/mod.rs
- shotover/src/transforms/debug/force_parse.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/redis/cluster_ports_rewrite.rs
Shotover `Message`s have 3 states they can be in, they progress from `RawBytes` -> `Parsed` -> `Modified`
https://github.com/shotover/shotover-proxy/blob/0db4f69e39eec2944c6a9141bbad7b2919613aee/shotover/src/message/mod.rs#L564-L576
When `Message::frame()` is called the message is moved to the `Parsed` state.
When `Message::invalidate_cache()` is called and the message is in `Parsed` state the message is moved to `Modified` State.
These states allow shotover to maintain a source of truth for the message without throwing away work.
For example:
* once the frame is parsed from the raw bytes (`Parsed` or `Modified`) the frame never needs to be reparsed.
* As long as the frame has not been modified (`RawBytes` or `Parsed`) the encoding stage does not need to reencode the raw bytes from the …
> KafkaSinkCluster: fix response recombine

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
From inspecting the messages passing through shotover I could see that ListOffsets is hitting NOT_LEADER_OR_FOLLOWER errors. (error code 6)
For example:
```
shotover   02:07:50.445929Z  INFO connection{id=41 source="kafka"}: shotover::transforms::debug::printer: Response: Kafka version:7 correlation_id:54 ListOffsets(ListOffsetsResponse { throttle_time_ms: 0, topics: [ListOffsetsTopicResponse { name: TopicName("partitions3_case4"), partitions: [ListOffsetsPartitionResponse { partition_index: 0, error_code: 6, old_style_offsets: [], timestamp: -1, offset: -1, leader_epoch: -1, unknown_tagged_fields: {} }], unknown_tagged_fields: {} }], unknown_tagged_fields: {} })
```
After some retries it will eventually hit the correct node and succeed:
```
shotover   02:07:51.047014Z  INFO …
```
> Implement routing for ListOffsets

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- test-helpers/src/connection/kafka/cpp.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
some info on transactions at the protocol level: https://cwiki.apache.org/confluence/display/KAFKA/Transactional+Messaging+in+Kafka
This PR adds a basic integration test for kafka transactions.
In order to get this integration test to pass support routing logic for the following message types is added to KafkaSinkCluster:
* InitProducerId
+ if a transaction id is provided: route to the transaction coordinator
+ if no transaction id is provided: route to a random node
* EndTxn
+ route to the transaction coordinator
* AddPartitionsToTxn
+ if version <= 3: route to the transaction coordinator
+ if version > 3: split request, route each split request to the transaction coordinator, and then rejoin the responses.
To support this new routing logic I also had to add logic for fetching the …
> KafkaSinkCluster transaction request routing

- Cargo.lock
- ec2-cargo/src/main.rs
- shotover-proxy/Cargo.toml
- shotover-proxy/benches/windsock/cloud/aws.rs
- windsock-cloud-docker/Cargo.toml
This PR makes use of the new functionality added in https://github.com/shotover/aws-throwaway/pull/60 to fix running benchmarks in our internal environment.
I also cleared out some unused dependencies
> Fix windsock cloud benches

- docs/src/transforms.md
- shotover-proxy/benches/windsock/kafka/bench.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
This PR makes the check_shotover_peers_delay_ms field optional.
When it is not provided the shotover peers check task is not started meaning that shotover nodes are always considered up and no TCP connections are created against shotover peers.
I think this field should be mandatory, we should force users to configure shotover to route around down shotover nodes, however, for now, lets make it optional to make it an easier transition.
> Allow disabling shotover peers check

- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/split.rs
Attempt at DRY'ing up the splitting logic, seeing if its worth it or not.
fetch splitting deviates too far from the logic of the rest of the splitting methods, so I've not attempted to implement it with the new RequestSplitAndRouter trait.
Since this only saves 40 lines, normally I would say its not worth the complexity of traits here.
However there are two reasons I think we should go ahead with this:
1. The logic that is DRY'd is actually pretty tricky to get right, hence why it has so many comments explaining whats going on. So having that implemented only once is quite valuable, on the other hand while the `RequestSplitAndRouter` trait implementations take ~25 lines each to implement, they are very difficult to get wrong since its mostly just specifying types so the type checker will …
> refactor splitting

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- test-helpers/src/connection/kafka/cpp.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
This PR is largely integration tests.
The functional changes are straightforward routing changes.
Routing logic is added for:
* AddOffsetsToTxn - standard transaction coordinator routing
* TxnOffsetCommit - standard group coordinator routing
+ unlike the other transactions requests this one routes by the group id, I'm sure theres some reason for this internally.
The integration tests required a few changes to the KafkaConnection test helper:
* Expanded send_offsets_to_transaction to allow specifying the topic partition -> offset mapping, allowing the method to actually do something useful rather then just a noop.
* Added abort_transaction method allowing us to test aborting transactions
* assert_no_consume_within_timeout to help with testing aborted transactions, giving us a way to assert …
> KafkaSinkCluster: Add more transactions integration tests

- Cargo.lock
- shotover/Cargo.toml
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls/create_token.rs
- shotover/src/transforms/kafka/sink_cluster/split.rs
- shotover/src/transforms/kafka/sink_single.rs
Update to the [recently released](https://github.com/tychedelia/kafka-protocol-rs/pull/95) kafka-protocol 0.13.0 
The largest change was https://github.com/tychedelia/kafka-protocol-rs/pull/90 which converted all IndexMap fields to use Vec instead.
This change was required due to the protocol actually supporting duplicate keys at the protocol level. (Its up to the broker to reject responses that are invalid due to duplicate keys)
The easiest way to fix this is to change those fields to Vecs and store the key in the struct.
This approach also comes with some performance benefits at the decode stage as can be seen by the improvement to the `decode_request_produce_create` benchmark.
Due to the replacement of IndexMap with Vec there was only 1 lookup that would have to be turned into an O(N) …
> Update kafka-protocol crate

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
This PR attempts to resolve intermittent failures such as https://github.com/shotover/shotover-proxy/actions/runs/11378756458/job/31655385620 by adding a check after topic creation that all the created topics have propagated across the cluster.
To do that we:
* java driver - extend the createTopics wrapper to allow querying multiple topics at once and return the number of partitions for each topic. 
* cpp driver - just add a sleep, the rust wrapper for the driver doesnt support describeTopics yet.
> kafka integration tests - wait for topics to be created

- test-helpers/src/connection/kafka/mod.rs
We were investigating a rare CI failure that we couldnt reproduce locally in https://github.com/shotover/shotover-proxy/pull/1770
In order to give us more information on whats going on the next time we hit this failure I've extended the assertion in assert_consume to give all the context it can.
Heres an example output:
```
Consumed an unexpected record:
expected topic "shotover_nodes_go_down_test" ️and it matched
expected message "initial" but the message was "incorrect produce value"
expected key Some("Key") and it matched
expected offset 0 and it matched
```
> Improve consumer assertion

- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/split.rs
When shotover encounters a request type it does not know how to route it will route it to a random node.
This is a reasonable guess and in the worst case the broker will respond with a routing error which we return to the client.
However this does make it hard to track down issues caused by this random routing which can occur when
* an existing message type hasnt had routing implemented yet
* new message types are added to kafka
To make it easier to diagnose these issues this PR does two things:
* Adds explicit routing handling for all message types we currently cover in our integration tests
* Adds a warning if a request is unhandled and therefore routed to a random node.
Unfortunately things are never that simple.
The OffsetForLeaderEpoch request is being sent to shotover as part of our …
> warn when shotover doesnt know how to route a request

- changelog.md
- docs/src/transforms.md
- shotover-proxy/benches/windsock/kafka/bench.rs
- shotover-proxy/tests/test-configs/kafka/cluster-1-rack/topology-single.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-1-rack/topology1.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-1-rack/topology2.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-1-rack/topology3.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-2-racks/topology-rack1.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-2-racks/topology-rack2.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-3-racks/topology-rack1.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-3-racks/topology-rack2.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-3-racks/topology-rack3.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-mtls/topology.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-plain/topology-single.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-plain/topology1.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-plain/topology2.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-plain/topology3.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/topology-single.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/topology1.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/topology2.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/topology3.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram/topology-single.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-tls/topology.yaml
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/shotover_node.rs
This PR splits `ShotoverNodeConfig::address` into `address_for_peers` and `address_for_clients`.
This allows shotover to support previously impossible networking setups where the shotover cluster communicates between itself using different addresses than is used by the clients to connect to the cluster.
The implementation is very straightforward: just replace the existing field with 2 new fields and use those fields in the appropriate places.
> Split ShotoverNodeConfig::address into address_for_peers and address_for_client

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover/benches/benches/codec/kafka.rs
- shotover/src/codec/kafka.rs
- shotover/src/codec/mod.rs
- shotover/src/frame/kafka.rs
- shotover/src/frame/mod.rs
- shotover/src/message/mod.rs
- shotover/src/transforms/kafka/sink_cluster/connections.rs
- shotover/src/transforms/kafka/sink_cluster/kafka_node.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- test-helpers/src/connection/kafka/python.rs
- test-helpers/src/connection/kafka/python/auth_fail.py
- test-helpers/src/connection/kafka/python/main.py
- test-helpers/src/lib.rs
This PR implements the legacy SASL implementation still in use by the python driver.
I am not aware of any other drivers that use it.
The [protocol docs](https://kafka.apache.org/protocol.html#sasl_handshake) describe the situation pretty well.
To summarize, when the client sends a SaslHandshake request of version 0, the client and broker will perform all SASL communication over raw packets.
Implementing this within shotover requires a lot of complexity, but it is ultimately manageable, and the implementation does not impact non-legacy SASL.
While the docs do not specify this, I am assuming that the client will always send its raw sasl requests immediately after sending a v0 SaslHandshake. The python driver at least behaves this way, and we would have to resort to heuristics to detect …
> Fix sasl with python-kafka

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- test-helpers/src/connection/kafka/cpp.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
This PR cleans up the existing testing for kafka delete_groups:
* Previously there was an admin_cleanup function in the cpp driver modules that was hardcoded to the cpp driver.
+ this was leftover from the very earliest integration tests we had for kafka
+ This PR moves this logic into the higher level `kafka_int_tests` module, calling the new `KafkaAdmin::delete_groups` method 
* Previously the java driver was untested, but this PR adds a delete_groups implementation for the java driver.
* Previously we ignored some failures in the cpp driver when deleting groups, I've not been able to reproduce those failures, so I just removed the extra handling.
> kafka_int_tests: cleanup delete_groups test

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/split.rs
- test-helpers/src/connection/kafka/cpp.rs
The integration test demonstrates an issue without the code changes, but only in the java driver and the test still passes, you have to inspect the messages to see there is in issue.
The java driver will actually retry failed portions of the request, leading to the following exchange:
```
shotover   23:27:06.525234Z  INFO connection{id=112 source="kafka"}: shotover::transforms::debug::printer: Request: Kafka version:2 correlation_id:4 client_id:"adminclient-3" DeleteGroups(DeleteGroupsRequest { groups_names: ["consumer_group_with_offsets", "some_group", "some_group1"], unknown_tagged_fields: {} })
shotover   23:27:06.529449Z  INFO connection{id=112 source="kafka"}: shotover::transforms::debug::printer: Response: Kafka version:2 correlation_id:4 DeleteGroups(DeleteGroupsResponse { …
```
> KafkaSinkCluster split DeleteGroups request

- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/split.rs
closes https://github.com/shotover/shotover-proxy/issues/1764
I was not able to find a way to reproduce this, I suspect that no drivers actually make use of this functionality.
Regardless, I think we should just handle this correctly since its pretty straightforward to implement.
I'm fairly confident it is correct due to its similarity to other split messages like DeleteGroups that also route by group id.
> KafkaSinkCluster: Split OffsetFetch

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- test-helpers/src/connection/kafka/cpp.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
Adds a test case for consumers that consume from more than one topic at a time.
This was an attempt to reproduce https://github.com/shotover/shotover-proxy/issues/1764 but while it did not reproduce the issue, it is still worth landing the extra test case for the improved coverage.
> KafkaSinkCluster: test multi topic consuming

- shotover/src/transforms/kafka/sink_cluster/mod.rs
Where possible we should avoid the variable name `message` instead use either `request` or `response`. This makes the code easier to read since it gives more context to the type of message being stored.
> KafkaSinkCluster: improve message naming

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover/Cargo.toml
Version 0.5.0 is skipped since the `v0.5.0-preview1` tag ended up being used as 0.5.0 internally.
> Release shotover 0.5.1

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/split.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
This turned out to be more complicated than I initially thought.
When `AdminClient.listConsumerGroups` is called, the java driver sends a `ListGroups` request to all brokers and then combines the responses, removing any duplicate entries.
To ensure that all groups are included shotover should also send requests to all brokers and combine them.
However we should avoid sending requests outside of shotovers rack to reduce the load of the operation.
This should still include all the results as the client will query all shotover nodes, and each shotover node will query a portion of the kafka brokers, ensuring all kafka nodes are queried.
A second commit was added to avoid running the new test case in the tests with a down shotover node, since that resulted in test failures as the down shotover …
> KafkaSinkCluster: route ListGroups request

- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover/src/transforms/cassandra/sink_cluster/rewrite.rs
- test-helpers/src/connection/cassandra/go.rs
- test-helpers/src/connection/cassandra/go/basic.go
- test-helpers/src/connection/cassandra/go/go.mod
- test-helpers/src/connection/cassandra/go/go.sum
- test-helpers/src/connection/cassandra/mod.rs
Turns out https://github.com/shotover/shotover-proxy/issues/1793 contains 2 issues.
1. Shotover emits a noisy error when a client submits an invalid prepared query. Shotover should just pass the error onto the client without reporting it as an error in shotover.
2. There is some kind of infinite loop where prepared queries never succeed. This is unrelated to the 1st issue.
This PR reproduces the 1st issue and fixes it.
However I am not yet able to reproduce the 2nd issue, so that will be attempted in follow up work.
> cassandra go driver fix error logs

- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover/src/transforms/cassandra/sink_cluster/rewrite.rs
closes https://github.com/shotover/shotover-proxy/issues/1793
This PR reproduces the issue in an integration test and then fixes the issue with a code change.
Shotover works well with clients that perform token aware routing of prepared execute requests.
However, if the client is not performing token aware routing, shotover may not be able to route the execute request correctly.
And while the gocql driver is initializing it sends execute requests through its control connection (not routed by token) therefore hitting this issue.
As a result the gocql driver ends up in a loop as it keeps retrying but never succeeding to prepared and execute the query.
The exact issue follows this flow:
1.   client sends request to create prepared query over control connection
2.   shotover routes request to …
> Fix hang in gocql init

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/split.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
This PR implements routing for ListTransactions requests by applying the same routing logic to ListTransactions as we did for ListGroups in https://github.com/shotover/shotover-proxy/pull/1790
However, I found that while the java driver deduplicates entries in ListGroups responses it does not do the same for ListTransactions responses.
So I had to alter the logic in `split_request_by_routing_to_all_brokers` to avoid duplicates.
As a result ListGroups is actually more efficient as we better distribute the load across shotover instances by avoiding querying the same node twice.
The comment on `split_request_by_routing_to_all_brokers` explains the new logic pretty well:
```rust
/// Route broadcast requests to all brokers split across all shotover nodes.
/// That is, each shotover node in a …
```
> Route ListTransactions request

- shotover-proxy/benches/windsock/kafka/bench.rs
- shotover-proxy/tests/test-configs/kafka/cluster-1-rack/docker-compose-short-idle-timeout.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-1-rack/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-2-racks/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-3-racks/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-mtls/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-plain/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-tls/docker-compose.yaml
See the comment for explanation of why this improves test runtime.
On my machine without this config:
* kafka_int_tests::cluster_1_rack_single_shotover::case_2_java takes 135s
* kafka_int_tests::cluster_1_rack_single_shotover::case_1_cpp takes 107s
on my machine with this config:
* kafka_int_tests::cluster_1_rack_single_shotover::case_2_java takes 42s or 65s
* kafka_int_tests::cluster_1_rack_single_shotover::case_1_cpp takes 42s
> Set a magic config which makes our kafka integration tests complete in half the time

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
The implementation is straightforward, DeleteRecords can be routed to any node, so we just pick one at random.
The integration test adds deleteRecords support to our java driver wrapper and adds a test case that calls deleteRecords and asserts that the records were deleted.
> KafkaSinkCluster: DeleteRecords

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- test-helpers/src/connection/java.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
This PR is mostly adding new methods to the java driver wrapper and adding an integration test case.
The listConsumerGroupOffsets and deleteConsumerGroupOffsets methods of the java admin client are now exposed, and we use them to write an integration test that lists all offsets of a group, deletes one of them and then lists them again to assert that it is deleted.
The actual implementation is straightforward: route the OffsetDelete request using the standard group coordinator routing via group id
It is a bit surprising that listConsumerGroupOffsets doesnt have a corresponding message type but it actually reuses the OffsetFetch message type used by the consumer client. So there are no changes to shotover required to support this functionality.
> KafkaSinkCluster: route OffsetDelete

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/split.rs
- test-helpers/src/connection/kafka/mod.rs
I didnt inspect the messages passing through for error codes in https://github.com/shotover/shotover-proxy/pull/1799 and allowed an incorrect routing implementation through.
It still passed the test due to java driver retrying on failure and shotover eventually randomly choosing the correct node to route to.
This PR fixes the issue by properly routing DeleteRecords by splitting it up and routing according to the node hosting the partition. The splitting logic is the same as fetch and produce message types but needs to be reimplemented to operate on the DeleteRecords struct instead.
I added a new integration test case to get coverage over the case where splitting happens (more than one partition to delete)
> KafkaSinkCluster: Fix DeleteRecords routing

- .github/workflows/build_and_test.yaml
This PR fixes a tricky CI caching issue introduced by https://github.com/shotover/shotover-proxy/pull/1801
#1801 pulled in https://github.com/astonbitecode/j4rs/pull/115 which fixes j4rs so that the build.rs script runs on the first build only, instead of on the first and second builds only. (it never ran on 3rd, 4th etc. builds)
However we are accidentally relying on this fact in our CI setup.
We build j4rs which sets up the target/debug/jassets directory.
The main branch CI run caches the `target` directory excluding jassets since its not a typical rust target file.
On the next PR branch run CI restores `target` from the main branch cache such that j4rs is fully compiled (no build.rs to run) but the jassets directory is missing.
Previously, since the build.rs would rerun on the 2nd …
> Attempt to fix CI

- shotover/src/transforms/kafka/sink_cluster/mod.rs
as per https://cwiki.apache.org/confluence/display/KAFKA/KIP-730:+Producer+ID+generation+in+KRaft+mode AllocateProducerIds is only sent as a cross broker RPC, and shotover does not support cross broker requests.
> KafkaSinkCluster: error on AllocateProducerIds

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
I was not able to get the integration test into a state that would allow ElectLeaders to succeed.
However from reading: https://cwiki.apache.org/confluence/display/KAFKA/KIP-460%3A+Admin+Leader+Election+RPC it looks like ElectLeaders should be routed to the control broker, so thats what I've done in this PR.
> KafkaSinkCluster: route ElectLeaders request

- .github/workflows/build_and_test.yaml
https://github.com/shotover/shotover-proxy/pull/1806 did not fix the issue, so this is attempt #2
As per the comment included in the CI change there is no way to properly fix this without upstream changes, so this PR provides an immediate workaround with the downside of increased CI time.
I am confident this will fix the issue this time since the PR passes without having to delete the cache.
> Fix CI - Attempt #2

- .pre-commit-config.yaml
This silences a warning for internal developers and will have no affect for external developers.
> Add config for internal precommit hook

- .github/workflows/build_and_test.yaml
https://github.com/shotover/shotover-proxy/pull/1808 was a success, but it only fixed debug builds, leaving all of the release builds broken as well.
To fix this, this PR includes the `${{ matrix.cargo_flags }}` in the clean flags.
This will include `--release` for release builds and nothing for debug builds, ensuring that release builds also have j4rs built from scratch, same as debug builds.
I'm not sure why #1808 seemed to completely fix the issue, maybe the main branch caches hadnt actually been written to yet.
> CI fix Attempt #3

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
This PR fixes the intermittent failures in cluster_3_racks_multi_shotover_with_2_shotover_down.
```
thread 'kafka_int_tests::cluster_3_racks_multi_shotover_with_2_shotover_down::case_1_java' panicked at /home/rukai/Projects/Crates/shotover/shotover-proxy/test-helpers/src/connection/kafka/mod.rs:261:13:
Consumed an unexpected record:
expected topic "shotover_nodes_go_down_test" ️and it matched
expected message "Message1" but the message was "initial"
expected key Some("Key") and it matched
expected offset 1 but the offset was 0
```
Locally I could reproduce the issue in about 1/5 test runs. I've run this PR for 40 runs and not reproduced the issue.
My understanding of the problem is:
1. We create a consumer group and consume 1 record. (we do not commit the offset)
2. We kill 2 shotover …
> cluster_3_racks_multi_shotover_with_2_shotover_down fix intermittent failures

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
This PR adds support for both ListPartitionReassignments and AlterPartitionReassignments.
They are done together because having both makes it easier to write a useful test.
The test looks like:
1. Create a partition reassignment by calling `admin.alterPartitionReassignments`
2. List partition reassignments by calling `admin.listPartitionReassignments` and then asserting that the created reassignment is listed.
The actual handling of the message types is trivial to implement and just requires routing to a random node.
> KafkaSinkCluster: route *PartitionReassignments

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/split.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
Implement routing for DescribeProducers message type, follows the same routing logic as fetch and produce messages where we route by partition location.
> KafkaSinkCluster: route DescribeProducers

- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/split.rs
This PR includes 2 unrelated changes to routing:
1. prefetch required routing metadata for `DeleteRecords` and `OffsetDelete`.
+ This was missed in https://github.com/shotover/shotover-proxy/pull/1803 and https://github.com/shotover/shotover-proxy/pull/1802
+ Without this logic we would not be able to route these message types unless another message type was recently sent that relies on the same metadata. That is how the issue went unnoticed.
2. Change `RequestSplitAndRouter::get_request_frame` to return `&mut Self::Request` instead of `Option<&mut Self::Request>`
+ This does not change functionality or fix anything but makes it easier to catch mistakes
+ The caller ignored the value if it was None which made for a very tricky to track down issue due to a typo when implementing …
> Routing fixes

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/split.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
another split message type.
It follows the same logic as AddPartitionsToTxn version > 3 message type, where we route and split by transaction id.
The integration tests are following the same pattern as DescribeGroups: https://github.com/shotover/shotover-proxy/pull/1816/files
> KafkaSinkCluster: route DescribeTransactions requests

- shotover/src/transforms/kafka/sink_cluster/mod.rs
It was harder to confirm this one is actually exclusively used broker to broker, but seems reasonable to assume so from what I did find.
If we do ever find clients that call this we can implement routing for it then.
> KafkaSinkCluster: error on AlterPartition request

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/split.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
yet another split message type.
It follows the same logic as DeleteGroups message type where we route and split by group id.
> KafkaSinkCluster: route DescribeGroups request

- shotover/src/transforms/kafka/sink_cluster/mod.rs
- test-helpers/src/connection/kafka/java.rs
In order to reproduce the issue, this PR bumps the java driver used in integration tests from 3.7 to 3.8.
j4rs does not appear to support multiple versions of dependencies, so I think the best way to get coverage across different protocol versions is to use the java driver (well maintained and kept up to date with the latest kafka protocol) as the upper bound and the cpp driver as the lower bound (basic maintenance and uses far older versions of the kafka protocol)
The cause of the failures on 3.8 is that the driver is now sending out DescribeCluster requests which shotover does not yet support.
So this PR implements support for the DescribeCluster message type.
The implementation is very similar to the Metadata request. In fact the functionality provided by DescribeCluster is just a …
> Support kafka java driver 3.8

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/test-configs/kafka/cluster-2-racks/docker-compose-kafka-3.9.yaml
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- test-helpers/src/docker_compose.rs
While we do not need to support kafka 3.9 yet, adding an integration test for it is very useful since when investigating how a message type is used in kafka 3.6, being able to check if its used in 3.9 helps rule out if it is actually in 3.6 or not.
To get the integration tests passing with kafka 3.9 I had to handle 2 new message types, this was done by rewriting ApiVersions responses to say that we dont support these message types at all. Refer to the comments in the code for the reasoning.
In the future we could extend the ApiVersions rewriting logic to ensure that future changes to kafka message types dont break shotover, but that is out of scope of this PR.
> KafkaSinkCluster: Add kafka 3.9 integration test

- shotover/src/transforms/kafka/sink_cluster/mod.rs
UnregisterBroker is a replacement for ControlledShutdown.
So the same reasoning as https://github.com/shotover/shotover-proxy/pull/1791 applies here.
> Error on UnregisterBroker

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/split.rs
- test-helpers/src/connection/java.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
This PR implements routing for `DescribeLogDirs`.
When the java driver routes `DescribeLogDirs` it sends it to a broker specified by the user.
When `kafka-log-dirs.sh` routes `DescribeLogDirs` it sends an identical request to every node in the cluster.
To handle this type of broadcast request shotover routes the request to all nodes in the rack. For other examples look at ListGroups, ListTransactions etc.
We route the request to all nodes in shotover's rack and then combine the results.
We alter the log dir path to avoid collisions with results from other racks, the new path looks like `actual-kafka-broker-id3:/original/log/dir/path`.
For more details on the reasoning behind this, look at the comment on `fn prepend_destination_to_log_dir`.
> KafkaSinkCluster: route DescribeLogDirs request

- shotover-proxy/tests/kafka_int_tests/mod.rs
- shotover-proxy/tests/kafka_int_tests/test_cases.rs
- shotover-proxy/tests/test-configs/kafka/cluster-2-racks/docker-compose-kafka-3.9.yaml
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- test-helpers/src/connection/kafka/cpp.rs
- test-helpers/src/connection/kafka/java.rs
- test-helpers/src/connection/kafka/mod.rs
Kafka is introducing a new consumer group protocol, at the moment nothing uses it, but having now researched it its fairly straightforward to implement, so lets do so.
Details:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-848:+The+Next+Generation+of+the+Consumer+Rebalance+Protocol#KIP848:TheNextGenerationoftheConsumerRebalanceProtocol-ConsumerGroupHeartbeatAPI
But the TL;DR is just that there is a new message type `ConsumerGroupHeartbeat` that we need to route to the group coordinator.
To actually test the message type we need to set a broker config to enable this functionality as a kind of "early access", since we already have a kafka 3.9 specific test case, I added this config to the kakfa 3.9 test and added a specific test case to the 3.9 test, to test the new consumer …
> KafkaSinkCluster: Support new consumer protocol

- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/split.rs
This PR will remain as draft until https://github.com/shotover/shotover-proxy/pull/1825 is landed. Changes on top of #1825 are in a separate commit.
ConsumerGroupDescribe is a replacement for the existing DescribeGroups message type.
No need to add new integration tests for this PR as we are already hitting this message type in our integration tests, we have avoided implementing this message type in shotover by modifying ApiVersions responses to instruct the client that we do not support ConsumerGroupDescribe.
This PR removes the ApiVersions rewrite so that the driver will make use of ConsumerGroupDescribe and then implements routing logic for ConsumerGroupDescribe.
ConsumerGroupDescribe requests are split up by group id, like the existing routing logic for message types DeleteGroups, …
> KafkaSinkCluster: route ConsumerGroupDescribe request

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover/Cargo.toml
Before we merge https://github.com/shotover/shotover-proxy/pull/1822 lets do one final release of the 0.5.x version.
> Release shotover 0.5.3

- shotover/src/transforms/kafka/sink_cluster/mod.rs
This PR address #1763 
It removes the `destination` associated field from all of the variants of the `PendingRequestState` enum, and moves this state to the parent  type `PendingRequest`.
This eliminates the need to pass the `destination` when transitioning between states.
> KafkaSinkCluster - move destination field from PendingRequestState into PendingRequest

- shotover-proxy/tests/kafka_int_tests/test_cases.rs
This PR attempts to fix an intermittent failure:
```
called `Result::unwrap()` on an `Err` value: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: 
Stack backtrace:
0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.93/src/backtrace.rs:27:14
1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/result.rs:1987:27
2: test_helpers::connection::java::Value::call_async_fallible::{{closure}}
at /home/runner/work/shotover-proxy/shotover-proxy/test-helpers/src/connection/java.rs:332:24
3: …
```
> Attempt to fix kafka cluster test intermittent failure

- test-helpers/src/connection/kafka/python/main.py
Attempts to fix the below failure that occurred in https://github.com/shotover/shotover-proxy/actions/runs/11964647835/job/33357613709
```
kafka_int_tests::cluster_sasl_scram_over_mtls_nodejs_and_python ---
{"level":"WARN","timestamp":"2024-11-22T01:33:58.889Z","logger":"kafkajs","message":"KafkaJS v2.0.0 switched default partitioner. To retain the same partitioning behavior as in previous versions, create the producer with the option \"createPartitioner: Partitioners.LegacyPartitioner\". See the migration guide at https://kafka.js.org/docs/migration-guide-v2.0.0#producer-new-default-partitioner for details. Silence this warning by setting the environment variable \"KAFKAJS_NO_PARTITIONER_WARNING=1\""}
{"level":"ERROR","timestamp":"2024-11-22T01:33:59.862Z","logger":"kafkajs","message":"[C …
```
> `kafka_int_tests::cluster_sasl_scram_over_mtls_nodejs_and_python` attempt to fix intermittent failure

- shotover-proxy/tests/valkey_int_tests/basic_driver_tests.rs
On a sufficiently fast machine these tests fail since the timestamps are equal.
The fix is to use `>=` comparison to allow the equal case to also pass the test.
> Fix valkey test_save

- shotover/src/transforms/kafka/sink_cluster/mod.rs
Reasoning is in error message.
> KafkaSinkCluster: Error on AlterReplicaLogDirs

- shotover/src/transforms/cassandra/sink_cluster/mod.rs
closes https://github.com/shotover/shotover-proxy/issues/1843
On my local machine:
* the problem reproduces itself within 10 runs of the test.
* with this PR, the test ran 100 times without reproducing the issue
I dont think this issue is common enough to rush out a release for, but this intermittent failure did turn out to be a real issue.
> CassandraSinkCluster fix lost messages

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/build.yaml
- .github/workflows/lint.yaml
- changelog.md
- docs/src/dev-docs/contributing.md
- docs/src/dev-docs/debugging.md
- docs/src/sources.md
- docs/src/user-guide/configuration.md
- docs/src/user-guide/writing-custom-transforms.md
- test-helpers/src/connection/mod.rs
Covers most of the remaining changes:
* Adds a changelog entry for shotover 0.6
* A bunch of docs fixes
* Fix feature change missed in https://github.com/shotover/shotover-proxy/pull/1836 , it seems like a bug in `cargo hack` that this was able to slip through, I've raised an issue here https://github.com/taiki-e/cargo-hack/issues/259
Remaining work:
* Update example docs in this repo
* rename redis-cache directory - https://github.com/shotover/shotover-proxy/pull/1848
* Update external example repos - TODO after release of shotover 0.6
> "redis" -> "valkey" docs misc changes

- website/src/main.rs
While this line passes locally for me since the file always exists, in an environment where the code has never run before the file does not exist, resulting in website generation failing in CI.
This PR fixes it by ignoring the error instead of unwrapping.
> Quick fix for website generator

- .github/workflows/publish-to-pages.yaml
- README.md
- shotover-proxy/config/topology.yaml
- shotover/src/config/topology.rs
- shotover/src/transforms/coalesce.rs
PR https://github.com/shotover/shotover-proxy/pull/1853 altered the `on:` section of the publish-to-pages workflow such that it would only run when: the branch is main AND the tag starts with `v`.
However the intention was to run when: the branch is main OR the tag starts with `v`.
This PR fixes the issue:
* I verified on my fork of the repo that the behavior is as expected
* and the documentation also indicates this is the correct approach: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-branches-and-tags
I also noticed we have a bunch of links to the website which will be invalid with the new website, so I've swapped them over to the new links.
> Fix website deploy

- shotover-proxy/benches/windsock/kafka/bench.rs
- shotover-proxy/tests/test-configs/kafka/bench/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-1-rack/docker-compose-short-idle-timeout.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-1-rack/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-2-racks/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-3-racks/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-mtls/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-plain/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram-over-mtls/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-sasl-scram/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/cluster-tls/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/passthrough-mtls/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/passthrough-sasl-plain/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/passthrough-sasl-scram/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/passthrough-tls/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/passthrough/docker-compose.yaml
- shotover-proxy/tests/test-configs/kafka/single-sasl-scram-plaintext-source-tls-sink/docker-compose.yaml
- test-helpers/src/docker_compose.rs
Ensure support for our internal usage of shotover by updating to the kafka version we use.
> Update integration tests to kafka 3.8.1

- shotover-proxy/build/build_release.sh
In https://github.com/instaclustr/atsc/pull/141 I discovered that shotover's compiled binary had a bug preventing it from being included in releases for over a year.
This PR applies the same fix as done in the ATSC repo, which fixed the problem over there.
> Fix binary release

- Cargo.lock
- shotover/Cargo.toml
- shotover/src/codec/kafka.rs
- shotover/src/frame/kafka.rs
- shotover/src/transforms/kafka/sink_cluster/api_versions.rs
- shotover/src/transforms/kafka/sink_cluster/kafka_node.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls/create_token.rs
The ApiVersions response is used by the broker to describe which message types and which versions of those message types are supported by the broker.
This allows clients to make use of new functionalities where possible but fallback to more basic function if the new message versions are not supported by the broker.
Consider the following scenario:
* Broker supports message type Foo V2
* Client supports message type Foo only up to V1
* Shotover can parse Foo V1 and Foo V2 via kafka-protocol crate.
+ However, shotover's rewrite or routing logic for Foo is only compatible with Foo v1. Foo V2 has a new field that needs to be taken into account but since the client currently only supports Foo V1 we have no way to observe this incompatibility in an integration test.
A new version of the client …
> ApiVersions rewrite unit test

- Cargo.lock
- shotover-proxy/Cargo.toml
- shotover/Cargo.toml
While it would be nice to include [kafka-protocol 0.14](https://github.com/tychedelia/kafka-protocol-rs/pull/101) in shotover 0.6 its not clear when it will be released so I think its best to move forward without it.
This PR releases shotover 0.6 the main changes of which are:
* renaming of redis -> valkey
* forwards compatibility with kafka via ApiVersions rewriting
> Release shotover 0.6

- Cargo.toml
- shotover/src/codec/cassandra.rs
- shotover/src/codec/kafka.rs
- shotover/src/connection.rs
- shotover/src/frame/cassandra.rs
- shotover/src/frame/kafka.rs
- shotover/src/frame/mod.rs
- shotover/src/frame/valkey.rs
- shotover/src/message/mod.rs
- shotover/src/server.rs
- shotover/src/transforms/cassandra/sink_cluster/mod.rs
- shotover/src/transforms/cassandra/sink_cluster/rewrite.rs
- shotover/src/transforms/cassandra/sink_cluster/topology.rs
- shotover/src/transforms/chain.rs
- shotover/src/transforms/debug/log_to_file.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
- shotover/src/transforms/kafka/sink_cluster/scram_over_mtls/create_token.rs
- shotover/src/transforms/protect/crypto.rs
- shotover/src/transforms/tee.rs
- shotover/src/transforms/util/cluster_connection_pool.rs
- shotover/src/transforms/valkey/cluster_ports_rewrite.rs
- shotover/src/transforms/valkey/sink_cluster.rs
This PR removes all cases that could possibly lead to logging message contents:
* The first and most important change is to remove trace level logs from release binaries. This is done by adding the `release_max_level_debug` feature. This allows trace level logs to log message contents for debugging purposes while making it impossible for these logs to make it into production.
* Move a few debug level logs to trace level logs since they include message contents.
* Remove message contents from some errors that include values, these errors needed to be combined with another bug in shotover or a bug in the client or DB for message contents to be logged. This PR removes that possibility entirely.
* the vast majority of the PR is just minor syntax cleanup of moving arguments inline with the …
> Dont log message contents

- Cargo.lock
- Cargo.toml
- custom-transforms-example/tests/test.rs
- shotover-proxy/benches/windsock/cloud/aws.rs
- test-helpers/src/docker_compose.rs
- test-helpers/src/shotover_process.rs
~~Blocked on https://github.com/shotover/tokio-bin-process/pull/44~~
[Rust 2024 will be marking `env::set_var` as unsafe](https://doc.rust-lang.org/edition-guide/rust-2024/newly-unsafe-functions.html), since unsafe is forbidden in this repo we need to remove all usage of `env::set_var` before we can upgrade to rust 2024.
This PR removes a specific usage of `env::set_var` and replaces it with a more specific version that only sets the env vars of a specific child process.
However achieving this was a little complex:
1. First we update to the latest version of tokio-bin-process, the new version uses a builder API for constructing `BinProcess`s which required a bunch of changes to how we use it.
2. Then we use the new `with_env_var` method on the builder to set the required env vars.
After …
> Remove `env::set_var` usage

- .github/workflows/build_and_test.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- windsock-cloud-docker/src/container.rs
Ubuntu 20.04 Actions runner image has been deprecated since Feb 2025 and is fully unsupported by April 2025. We will move away from ubuntu 20.04 to either 22.04 and 24.04.
https://github.com/actions/runner-images/issues/11101
> Replace the usage of ubuntu 20.04

- docs/src/SUMMARY.md
There are currently some dead links on this page: https://shotover.io/docs/main/dev-docs/contributing.html
The SUMMARY.md file is used to generate the sidebar:
And pages not included in the sidebar are not generated at all.
So to ensure these pages are generated, this PR includes them in the sidebar.
> Fix missing docs pages

- .github/workflows/license_check.yaml
- Cargo.lock
- Cargo.toml
- deny.toml
- docs/src/dev-docs/setting-up-linux.md
- shotover-proxy/Cargo.toml
- shotover/Cargo.toml
- shotover/src/tls.rs
- test-helpers/src/connection/cassandra/cql_ws.rs
There are a few things in favor of aws-lc-rs.
its maintained by amazon whereas ring is maintained by a single person who has declared it to be in maintenance mode.
it is the default backend for rustls, and due to cargo feature unification its very easy for the aws-lc-rs backend to be enabled accidentally.
This is reason enough to move over.
But we are currently forced to make a new decision to move or stay since the AWS SDK has enabled the aws-lc-rs features of rustls, which breaks shotover at runtime after a cargo update is run. We ran into this issue during https://github.com/shotover/shotover-proxy/pull/1882 
So I think the decision should definitely be to move over to aws-lc-rs.
Also see this ticket which had some useful discussion: https://github.com/awslabs/aws-sdk-rust/issues/1264 …
> Prefer aws-lc-rs over ring

- .github/workflows/bench_run.yaml
- Cargo.lock
- Cargo.toml
- shotover-proxy/Cargo.toml
- shotover-proxy/tests/cassandra_int_tests/mod.rs
- shotover/Cargo.toml
- test-helpers/Cargo.toml
Upgrade the following dependencies, which do not need Rust code changes:
- cached
- governor
- rstest
- j4rs
- hex-literal
We use the latest `codspeed` that has the `--jobs` option but it's not tagged as release yet, so we build from the commit as specified in `bench_run.yaml` .  We will double-back to it later after we have the new version.
> Upgrade dependencies that do not need code changes

- Cargo.lock
- Cargo.toml
- shotover-proxy/build/install_ubuntu_packages.sh
- shotover-proxy/tests/cassandra_int_tests/protect.rs
- shotover/src/transforms/protect/crypto.rs
Upgrade the `bincode` crate to version 2.0.1
The option `-DCMAKE_POLICY_VERSION_MINIMUM=3.5` has been added to the `cmake` command in `install_ubuntu_packages.sh` to solve the build failure when building cpp packages.
> Upgrade bincode to version 2.0.1

- rust-toolchain.toml
- shotover-proxy/tests/cassandra_int_tests/cluster/multi_rack.rs
- shotover-proxy/tests/cassandra_int_tests/cluster/single_rack_v3.rs
- shotover-proxy/tests/cassandra_int_tests/cluster/single_rack_v4.rs
- shotover/src/transforms/cassandra/sink_cluster/token_ring.rs
- shotover/src/transforms/kafka/sink_cluster/connections.rs
https://blog.rust-lang.org/2025/04/03/Rust-1.86.0.html
The main exciting thing for us is much faster linux aarch64 builds, since rustc is now compiled with thinLTO + PGO on that platform.
The repeat_n changes are to address the new clippy lint: https://rust-lang.github.io/rust-clippy/stable/index.html#manual_repeat_n
The doc comment changes are to address the new clippy lint: https://rust-lang.github.io/rust-clippy/stable/index.html#doc_overindented_list_items
> Update to rust 1.86 🦀🦀🦀

- shotover/src/transforms/kafka/sink_cluster/mod.rs
closes https://github.com/shotover/shotover-proxy/issues/1903
This issue obfuscated the real cause while trying to resolve a local setup issue.
I imagine it could also lead to confusion in possible production misconfigurations as well.
Solution: that unwrap needs to be replaced with an if let so that we do nothing when its None
> KafkaSinkCluster: Fix connect error handling when we dont have cluster metadata yet.

- Cargo.lock
- ec2-cargo/Cargo.toml
- shotover/Cargo.toml
- shotover/src/transforms/kafka/sink_cluster/api_versions.rs
- test-helpers/Cargo.toml
Updates the kafka-protocol, tokio-tungstenite, and cargo_metadata to their latest version.
redis crate was left as is since upgrading it is complicated.
The other changes in Cargo.toml are due to vs code's auto-formatter, agree'd with lucas that we'll leave in the auto-formatting to make it easier to work with in vs code.
The kafka-protocol crate changed the known kafka message types/versions, so check_api_version_backlog had to be tweaked accordingly.
> 3 dependencies updated

- shotover-proxy/tests/runner/hotreload_int_tests.rs
- shotover/src/hot_reload_client.rs
- shotover/src/hot_reload_server.rs
- shotover/src/json_parsing.rs
- shotover/src/lib.rs
- shotover/src/runner.rs
- test-helpers/src/shotover_process.rs
This PR implements a task for the socket handoff feature for hot reload. A Unix Socket Client that will enable replacement shotover instance to communicate with original instance during hot reload operations.
- Unix Socket Client - Replacement shotover connects to Original Shotover via Unix Domain Sockets
- CLI Integration - A new cli arguement '--hotreload-from-socket' implemeted for client mode
- Request/Response Model - Client sends 'SendListeningSockets' request and receives file descriptors
- Startup Integration: Client automatically connects during shotover initialisation.
- Client connects to Unix socket at specified path
- Sends a JSON request for transferring listening sockets
- Receives a JSON response
- Logging of communication that happend
The communication between the client …
> UNIX SOCKET HANDOFF - CLIENT SIDE IMPLEMENTATION

- rust-toolchain.toml
- shotover/benches/benches/chain.rs
- shotover/src/frame/cassandra.rs
- shotover/src/transforms/kafka/sink_cluster/mod.rs
- test-helpers/src/connection/kafka/cpp.rs
Updates from rust 1.87 to rust 1.89
The code changes are to fix a new warning introduced in rust 1.89.
For complete details see [the release blog](https://blog.rust-lang.org/2025/08/07/Rust-1.89.0/#mismatched-lifetime-syntaxes-lint).
But the purpose of the new warning is just to enforce consistency in the way lifetimes are written. The original and new code are functionally identical.
The perf improvements picked up by codspeed are due to rust 1.88 fixing a perf bug in 1.87 that [we knowingly allowed through](https://github.com/shotover/shotover-proxy/pull/1906#issuecomment-2982858924).
> Update to rust 1.89

- shotover/src/sources/cassandra.rs
- shotover/src/sources/kafka.rs
- shotover/src/sources/mod.rs
- shotover/src/sources/opensearch.rs
- shotover/src/sources/valkey.rs
- This PR addresses the issue: https://github.com/shotover/shotover-proxy/issues/1924. 
- Consolidated the protocol-specific `*Source` types (CassandraSource, KafkaSource, ValkeySource, OpenSearchSource) into a single unified Source struct, eliminating code duplication while maintaining identical functionality.
> Refactor sources to use unified Source struct

- shotover/src/transforms/cassandra/sink_cluster/topology.rs
closes https://github.com/shotover/shotover-proxy/issues/1923
In shotover's [CassandraSinkCluster](https://shotover.io/docs/latest/transforms.html#cassandrasinkcluster) transform we query `system.peers_v2` to get the full list of cassandra nodes in the cluster.
We specifically prefer `system.peers_v2` over `system.peers` since it includes port information, without which we need to assume the default port of 9042.
This PR fixes the CassandraSinkCluster transform to be compatible with the [DSE](https://www.datastax.com/resources/datasheet/datastax-enterprise) database which does not have a `system.peers_v2` table and only has a `system.peers` table. Consider:
| DB | `system.peers` | `system.peers_v2` | officially support by shotover |
|----|--------|--------|--|
| DSE | yes | no | no |
| …
> CassandraSinkCluster - fix system.peers fallback

- shotover/src/transforms/cassandra/sink_cluster/topology.rs
This PR helps to diagnose issues when the system.peers queries run by the [CassandraSinkCluster](https://shotover.io/docs/latest/transforms.html#cassandrasinkcluster) transform are failing. 
This improved error reporting was needed to diagnose https://github.com/shotover/shotover-proxy/pull/1934
If you are unfamiliar with rust's match functionality, you might want to [read up on them](https://doc.rust-lang.org/book/ch06-02-match.html).
Shotover will query the [system.peers](https://docs.datastax.com/en/cql-oss/3.3/cql/cql_using/useQuerySystemTableCluster.html) table when it needs to learn what cassandra nodes are in the cluster.
In this PR we alter how we handle the response to the `system.peers` table.
Previously cassandra returning an error and cassandra returning an unexpected response …
> CassandraSinkCluster - improve system.peers error log

- shotover/src/transforms/cassandra/peers_rewrite.rs
closes https://github.com/shotover/shotover-proxy/issues/1923
All messages that pass through shotover are stored in the [Message](https://docs.rs/shotover/latest/shotover/message/struct.Message.html) type. These messages are passed through each of shotover's configured [transforms](https://shotover.io/docs/latest/user-guide/concepts.html#transform) which can inspect and possibly modify the messages.
Please read over this section from the linked `Message` docs:
As it explains the different states a message can be in.
The bug this PR is fixing is that we accidentally call [invalidate_cache](https://docs.rs/shotover/latest/shotover/message/struct.Message.html#method.invalidate_cache) on all responses passing through the CassandraPeersRewrite transform, which means all responses must be …
> Fix CassandraPeersRewrite invalidating the cache of all responses

- shotover-proxy/tests/runner/hotreload_int_tests.rs
- shotover/src/hot_reload/client.rs
- shotover/src/hot_reload/fd_utils.rs
- shotover/src/hot_reload/json_parsing.rs
- shotover/src/hot_reload/mod.rs
- shotover/src/hot_reload/protocol.rs
- shotover/src/hot_reload/server.rs
- shotover/src/server.rs
Implements actual file descriptor passing using [Unix socket ancillary data](https://doc.rust-lang.org/std/os/unix/net/struct.SocketAncillary.html#method.add_fds), building on the PR -https://github.com/shotover/shotover-proxy/pull/1940's [UDS crate](https://docs.rs/uds/latest/uds/tokio/struct.UnixSeqpacketConn.html#method.send_fds) foundation. This eliminates the need for sudo access by leveraging the kernel's built-in file descriptor transfer mechanism.
Previously, our hot reload used pidfd_getfd which required sudo privileges. Unix sockets provide an out-of-band mechanism for sending file descriptors between processes using ancillary data. This tells the OS that the destination process now has permission to access the FD, eliminating the need for privileged access.
-  If FDs are …
> Implement FD transmission via Unix Socket Ancillary Data 
