shotover/shotover-proxy

shotover-proxy/tests/runner/observability_int_tests.rs
Fix the test that is breaking main
=> RedisSource fix

README.md, docs/src/transforms.md, docs/src/user-guide/introduction.md
Some of the headings were wrong.
=> Fix doc headings

shotover-proxy/src/protocols/cassandra_protocol2.rs
Mostly just removing unnecessary use of std::mem::replace
=> cassandra_protocol2.rs cleanup

shotover-proxy/src/protocols/cassandra_protocol2.rs
* Simplifies the implementation
* Removes dependency on feature added in our cassandra-proto fork (in upstream Row.metadata and Row.row_content are private)
* Less allocation
=> remove use of feature specific to cassandra-proto fork

docs/src/transforms.md, shotover-proxy/src/transforms/tee.rs
Validate subchains in Tee and update doc example to be correct
=> Tee subchain fixes

shotover-proxy/src/server.rs, shotover-proxy/src/transforms/chain.rs, shotover-proxy/src/transforms/util/cluster_connection_pool.rs, shotover-proxy/src/transforms/util/unordered_cluster_connection_pool.rs
Concurrent logs now look like this:
This allows us to see through the noise and form a sequence of events from concurrent logs.
Possibly we should be using a random id instead of an incrementing value. - Discussed with kuangda: incrementing will be fine for now
Relevant docs: https://docs.rs/tracing/0.1.29/tracing/trait.Instrument.html
=> Instrument async code with tracing spans

shotover-proxy/src/protocols/cassandra_protocol2.rs
previous function: https://github.com/shotover/cassandra-proto/blob/a8f52fd0821277d4d40d88cf7b5753292c72200b/src/types/mod.rs#L642
new function: https://github.com/AlexPikalov/cassandra-proto/blob/ef0ed2c392f2530ea9f92029966636a8b17bdc9f/src/types/mod.rs#L248
They both convert the i32 into a big endian Vec<u8>
=> Remove another cassandra-proto fork feature

.dockerignore, .github/workflows/release.yml, Dockerfile
Example of how to use, assuming your config and topology file are in the home dir:
`docker run -t -v /home/conor:/config shotover-proxy --help`
`docker run -t -v /home/conor:/config shotover-proxy -t config/top1.yaml -c config/config.yaml`
I've registered a "shotover" user on Dockerhub and will also integrate publishing our releases in this PR.
=> Dockerfile for Shotover

.github/workflows/release.yml, .github/workflows/test.yml, shotover-proxy/build/install_ubuntu_packages.sh
- Add a script to install dependencies needed for testing on ubuntu
- run the release workflow in tests
- rename some workflows to clearer names
=> dependency install script and testing release workflow

shotover-proxy/src/protocols/cassandra_protocol2.rs, shotover-proxy/src/transforms/cassandra/sink_single.rs
Just a few small cleanups I pulled out of another larger PR.
=> Minor cassandra cleanup

shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
from my vaguely scientific testing I came up with the following table:
```
optimizations      get/set loop     test_pass_through time to complete
--release          1                3.5s
--release          10000            3.5s
all opt=3          1                4.0s
deps opt=3         1                4.5s
none               1                6.0s
deps opt=3         10000            15s
none               10000            30s
```
* `--release` - I ran with `test --release`, includes all the crazy release optimizations like LTO and stuff
* `deps opt=3` - set debug mode to have just the dependencies at opt-level=3, all other optimizations unchanged.
* `all opt=3` - set debug mode to have everything at opt-level=3, all other optimizations unchanged.
reducing the number of iterations in this …
=> Easy win in test runtime

shotover-proxy/tests/cassandra_int_tests/basic_driver_tests.rs, shotover-proxy/tests/cassandra_int_tests/mod.rs
=> Cassandra table int tests

shotover-proxy/tests/cassandra_int_tests/basic_driver_tests.rs, shotover-proxy/tests/cassandra_int_tests/mod.rs
=> Cassandra UDT int tests

shotover-proxy/src/transforms/load_balance.rs
Just renames variables to be more accurate and adds a comment explaining the intended use.
I actually cant think of how you would write a shotover config to make use of the "cloning = new connection" design, but that does seem to be the intended design.
=> Cleanup load balance

shotover-proxy/examples/redis-cluster-dr/docker-compose.yml, shotover-proxy/src/transforms/chain.rs, shotover-proxy/src/transforms/load_balance.rs, shotover-proxy/src/transforms/tee.rs, shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
closes https://github.com/shotover/shotover-proxy/issues/385
Solves the problem by taking ben's suggested chain_to_clone solution in the tee transform.
The redis-cluster-dr example was extended to use authentication instead of creating an entirely new test to allow for testing this case without a large hit to test runtime.
=> Fix redis auth issue

shotover-proxy/src/protocols/cassandra_codec.rs, shotover-proxy/src/transforms/redis/cache.rs
Mostly variable renames ~~but I also fixed a panic on misconfiguration.~~
=> Various redis cache cleanup

shotover-proxy/tests/helpers/mod.rs
closes https://github.com/shotover/shotover-proxy/issues/436
To observe the fix run:
```shell
cargo test test_shotover_responds
ps aux | grep shotover-proxy
```
with a panic here:
Before the fix there will be a stray process:
```
rukai      90854  0.0  0.0 376504 23804 pts/3    Sl   14:25   0:00 /home/rukai2/Projects/Crates/shotover/shotover-proxy/target/debug/shotover-proxy -t examples/null-redis/topology.yaml
```
After the fix there will be no such process.
=> Fix stray shotover processes

Cargo.lock, shotover-proxy/Cargo.toml, shotover-proxy/src/message/mod.rs, shotover-proxy/src/protocols/cassandra_codec.rs, shotover-proxy/src/protocols/redis_codec.rs, shotover-proxy/src/transforms/distributed/consistent_scatter.rs, shotover-proxy/src/transforms/protect/mod.rs, shotover-proxy/src/transforms/redis/cache.rs, shotover-proxy/src/transforms/redis/timestamp_tagging.rs
=> Add new value variants

shotover-proxy/src/transforms/redis/cache.rs
Implementation is now less brittle and easier to understand.
Anything touching ValueHelper will need to be rewritten but that will happen later when we figure out how we are going to serialize/deserialize the values.
=> Redis cache cleanup

Cargo.lock, rust-toolchain.toml, shotover-proxy/Cargo.toml
- update to newest Rust version
- update out of date dependencies
=> Update to Rust 1.58

shotover-proxy/src/message/mod.rs, shotover-proxy/src/transforms/chain.rs
Details [here](https://rust-lang.github.io/rust-clippy/master/index.html#return_self_not_must_use).
=> Add #[must_use] to methods returning self

shotover-proxy/src/config/topology.rs
=> remove get_demo_config

shotover-proxy/src/message/mod.rs, shotover-proxy/src/protocols/cassandra_codec.rs
Moves the value_to_expr and expr_to_value functions into From impls.
This generally makes sense and is already done for RedisFrame.
But it also make progress towards https://github.com/shotover/shotover-proxy/issues/445 as we need access to this logic from transforms.
=> Implement From between Value and SQLValue

shotover-proxy/src/transforms/protect/mod.rs
Pulls some small cleanups out of the message details PR.
I will heavily the refactor the tests in a separate PR
=> small Protect transform cleanup

shotover-proxy/src/message/mod.rs, shotover-proxy/src/protocols/cassandra_codec.rs, shotover-proxy/src/protocols/redis_codec.rs, shotover-proxy/src/server.rs, shotover-proxy/src/transforms/debug/returner.rs, shotover-proxy/src/transforms/kafka_sink.rs, shotover-proxy/src/transforms/redis/sink_cluster.rs
=> Move MessageDetails::ReturnToSender to a field on Message

shotover-proxy/src/transforms/cassandra/connection.rs, shotover-proxy/src/transforms/cassandra/mod.rs, shotover-proxy/src/transforms/cassandra/sink_single.rs, shotover-proxy/src/transforms/util/mod.rs
As per the discussion on https://github.com/shotover/shotover-proxy/pull/481
=> ConnectionPool -> CassandraConnection

docs/src/transforms.md, shotover-proxy/src/transforms/filter.rs, shotover-proxy/src/transforms/loopback.rs, shotover-proxy/src/transforms/mod.rs, shotover-proxy/src/transforms/protect/mod.rs
=> Loopback transform directly returns the message

shotover-proxy/src/protocols/cassandra_codec.rs
Current implementation assumes there will always be metadata, we should first check if the `NO_METADATA` flag was included before trying to use `col_spec` to convert the `row_content` into a `MessageValue`.
There is also a PR <s>open</s> merged on cdrs-tokio that fixes another issue associated with this: https://github.com/krojew/cdrs-tokio/pull/76
The combination of these PRs will fix the bug discovered on https://github.com/shotover/shotover-proxy/pull/486.
=> NO_METADATA CassandraCodec fix

shotover-proxy/tests/helpers/mod.rs
It is possible on very slow machines for the building part of `cargo run` to cause `test_shotover_responds_sigterm` to timeout due to spending the entire timeout time building shotover instead of running it.
I am confident that we dont need a timeout on `cargo build`, so this PR first runs that to ensure shotover is completely built before running `cargo run`.
This should fix the CI failures I am getting in https://github.com/shotover/shotover-proxy/pull/494
Even if it doesnt, then its still a useful protection against a possible failure case.
=> Fix ShotoverProcess timeout

shotover-proxy/benches/chain_benches.rs, shotover-proxy/src/transforms/filter.rs
Each iteration includes one filtered and one non-filtered message.
=> Add benchmark for filter transform

shotover-proxy/src/frame/cassandra.rs, shotover-proxy/src/message/mod.rs, shotover-proxy/src/transforms/redis/cache.rs
Closes https://github.com/shotover/shotover-proxy/issues/473
Taken from https://github.com/shotover/shotover-proxy/pull/453
=> rewrite redis cache to use message.original

shotover-proxy/src/transforms/protect/mod.rs, shotover-proxy/tests/cassandra_int_tests/basic_driver_tests.rs
closes https://github.com/shotover/shotover-proxy/issues/476
Currently the protect transform serializes the encrypted values to bincode and then stores the result in a MessageValue::Bytes.
The MessageValue::Bytes fails to round trip through cassandra because the current cassandra AST lacks a way to represent binary blobs.
Previously that didnt cause any problems because the query_values message details never got assembled back into the outgoing message.
But as of this PR this functionality actually works so this PR reverts the serialization to use serde instead of bincode as we can easily round trip through a string value.
Once we get a proper cql ast we can revert back to bincode and MessageValue::Bytes.
=> rewrite protect to use message.original

shotover-proxy/benches/cassandra_benches.rs
- Add TLS benchmarks.
- Change new methods of `BenchResources` to accept strings for topology and docker-compose files instead to reduce duplicated code. 
- Add `new_tls` method and move setup code to another method so it can be reused.
=> Cassandra TLS benchmarks

Cargo.lock, shotover-proxy/tests/helpers/mod.rs, shotover-proxy/tests/runner/runner_int_tests.rs, test-helpers/Cargo.toml, test-helpers/build.rs, test-helpers/src/lib.rs, test-helpers/src/shotover_process.rs
Would allow us to make use of it in an external benchmark crate.
=> Move ShotoverProcess into test-helpers

shotover-proxy/benches/cassandra_benches.rs
Uses the added new_lazy_shared function to lazily create a single BenchResources that is shared by every benchmark that needs the same resources.
There is of course a lot of variance between runs but 32m looks pretty good.
=> Improve bench time by minimizing docker container creation

shotover-proxy/benches/chain_benches.rs
Compared to https://github.com/shotover/shotover-proxy/pull/565/files it benches only the transform giving us a less noisy result.
https://github.com/shotover/shotover-proxy/pull/565/files is still useful for giving an overview.
=> Cassandra request throttling non-integration bench

shotover-proxy/src/transforms/throttling.rs, shotover-proxy/tests/cassandra_int_tests/basic_driver_tests.rs, shotover-proxy/tests/test-configs/cassandra-request-throttling.yaml
=> Minimum value for Request Throttling config

shotover-proxy/src/transforms/redis/sink_cluster.rs
* Removes the TODO: It seems the author got confused and thought redis was supposed to use `RedisFrame::Integer` within commands.
However the spec clearly says that commands only consist of `RedisFrame::BulkString`: https://redis.io/docs/reference/protocol-spec/#resp-protocol-description
* Removes the `RedisFrame::Integer` handling
* One less allocation (`&str` instead of `String`)
=> Simplify eval routing

shotover-proxy/src/transforms/redis/sink_cluster.rs
"CLIENT LIST",  "CLIENT SETNAME" and "SCRIPT KILL" would never match because a command containing a " " will never match here as commands are already split by spaces.
* "SCRIPT KILL" is reimplemented with the intended mapping
* "CLIENT LIST" is removed, it will continue to receive RoutingInfo::AllNodes as intended
* "CLIENT SETNAME" is removed, it will continue to receive RoutingInfo::AllNodes even though this wasnt the intention.
I'll do another pass over these mappings in a follow up PR but I wanted to remove these nonsense cases first.
=> Fix invalid command routes

rust-toolchain.toml, shotover-proxy/src/transforms/mod.rs
https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html
=> Update to rust 1.60

rustfmt.toml
=> Add edition to rustfmt.toml

docs/src/SUMMARY.md, docs/src/transforms.md, docs/src/user-guide/configuration.md, docs/src/user-guide/observability.md, shotover-proxy/src/admin/mod.rs, shotover-proxy/src/lib.rs, shotover-proxy/src/observability/mod.rs, shotover-proxy/src/runner.rs
- Closes #424
- Clean up the code for the observability interface a bit (just renaming and moving stuff to be more appropriate)
=> Improve metrics docs

shotover-proxy/src/transforms/redis/sink_cluster.rs
Just a minor cleanup.
The enum currently has only one variant and the variant could just as well live directly in RoutingInfo and ChannelResult.
I think this is better because it encourages making routing more generic rather than hardcoded to a specific command, although we can still easily hardcode handling for a specific command like we do for Auth when needed.
If we ever find we do need such an abstraction it can be easily readded.
=> Remove RedisClusterSink Command enum

shotover-proxy/build/install_ubuntu_packages.sh
Until the cert is updated we will need this for the CI to work. I will re enable cert checking once it's updated.
=> Temp CI fix

shotover-proxy/src/transforms/util/cluster_connection_pool.rs
There are two changes here:
1. Make the logic easier to follow by modifying the connection list in place instead of creating a new one that overwrites the old one.
2. Previously the stored list of connections would be truncated if there were more connections than requested due to `existing_connections.iter().take(connection_count).cloned()`. This is no longer true and the truncation now only occurs on the returned list `connections[..connection_count].to_vec()`
There shouldnt be any functional changes other than change 2, if you spot any thats a mistake.
=> redis connection pool cleanup+improvement

shotover-proxy/build/install_ubuntu_packages.sh
Cert has been updated so we can remove this now.
=> Enable cert check

shotover-proxy/src/config/topology.rs, shotover-proxy/src/transforms/chain.rs
as discussed on https://github.com/shotover/shotover-proxy/pull/652
=> Move ChannelMessage to chain.rs and rename

shotover-proxy/tests/helpers/cassandra.rs
Pulled out of https://github.com/shotover/shotover-proxy/pull/598
Justification is in the comment
=> Improve cassandra_connection panic message

shotover-proxy/src/transforms/redis/sink_cluster.rs
Just some random cleanups im pulling out of a feature PR.
* No need to use Derivative(debug) when we arent filtering out any of the fields.
* latest_contact_points now does less allocations
* moved the errors variable to be declared just before its used.
=> minor redis cleanup

Cargo.lock, shotover-proxy/Cargo.toml, shotover-proxy/src/transforms/protect/aws_kms.rs, shotover-proxy/src/transforms/protect/crypto.rs, shotover-proxy/src/transforms/protect/key_management.rs, shotover-proxy/src/transforms/protect/local_kek.rs
Replaced with https://github.com/RustCrypto/AEADs
=> remove sodium oxide

shotover-proxy/src/transforms/cassandra/peers_rewrite.rs
=> change peers rewrite port to u16

shotover-proxy/src/config/topology.rs
=> Small cleanup

Cargo.lock, shotover-proxy/Cargo.toml, shotover-proxy/benches/chain_benches.rs, shotover-proxy/src/codec/cassandra.rs, shotover-proxy/src/frame/cassandra.rs, shotover-proxy/src/transforms/cassandra/peers_rewrite.rs, shotover-proxy/src/transforms/redis/cache.rs, shotover-proxy/tests/cassandra_int_tests/protect.rs
closes https://github.com/shotover/shotover-proxy/issues/575
cql3-parser is updated to receive a required bug fix to batch parsing
=> Convert batch QUERYs into BATCHs

shotover-proxy/example-configs-docker/redis-cluster-ports-rewrite/docker-compose.yml, shotover-proxy/example-configs-docker/redis-cluster/docker-compose.yml, shotover-proxy/example-configs/redis-cluster-dr/docker-compose.yml, shotover-proxy/example-configs/redis-cluster-handling/docker-compose.yml, shotover-proxy/example-configs/redis-cluster-hiding/docker-compose.yml, shotover-proxy/example-configs/redis-cluster-tls/docker-compose.yml, shotover-proxy/tests/test-configs/redis-cluster-auth/docker-compose.yml, shotover-proxy/tests/test-configs/redis-cluster-ports-rewrite/docker-compose.yml
=> docker-compose versions

shotover-proxy/src/transforms/chain.rs, shotover-proxy/src/transforms/load_balance.rs, shotover-proxy/src/transforms/tee.rs
* use AtomicU64 instead of a mutex, its technically faster but that doesnt matter as its just test code, I only changed it because its simpler
+ The Ordering value doesnt matter here at all, as they are all suitable for an atomic counter.
* reworded various tracing log messages
=> Small chain.rs cleanup

Cargo.lock, rust-toolchain.toml, shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
Opening this for discussion as to whether we want to update to the latest. I know the last one had some slow compilation problems.
=> new rust version

Cargo.lock, shotover-proxy/Cargo.toml, shotover-proxy/src/message/mod.rs
The one use of this library can be better expressed using methods from std anyway.
=> Remove byteorder dep

shotover-proxy/src/codec/redis.rs
Equivalent to the hexdump logs already in place for cassandra.
I found these useful in the development of https://github.com/shotover/shotover-proxy/pull/645
=> Add redis hexdump debug logs

docs/src/transforms.md
Fixing up the protect docs with proper examples.
=> Protect docs

shotover-proxy/tests/cassandra_int_tests/mod.rs
It was pretty cleanly split into two sections anyway, may as well have them runnable separately.
Additionally the comments didn't really make sense.
`check it works with an older version of Cassandra` makes it sound like it actually does something on older versions of cassandra but what we are asserting is actually that it correctly does nothing.
Make sure to select "hide whitespace" for a sensible diff.
=> Split test_cassandra_peers_rewrite into two tests

shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
Cleanup done while trying to resolve https://github.com/shotover/shotover-proxy/issues/713 
But I dont think 713 is worth putting more time into at the moment.
=> Tiny cleanup in redis int test

docs/src/transforms.md
* CassandraSinkSingle was missing
* RedisSinkCluster had the comments mixed up
* RedisSinkSingle had the fields in an inconsistent order with RedisSinkCluster
=> Fix transform TLS docs

shotover-proxy/src/transforms/cassandra/sink_single.rs
Noticed this as im referring to it for the implementation of CassandraSinkCluster.
Although the old implementation managed to avoid an unwrap call, using the unwrap here makes the logic a lot easier to follow.
It also matches how we approach this problem in every other sink transform.
Make sure to disable whitespace for a sane diff.
=> Remove loop from CassandraSinkSingle

shotover-proxy/src/codec/cassandra.rs
Previously it would only dump the outgoing messages if the message was modified leading to much confusion.
Now it dumps every message regardless of its internal state.
The new functionality matches how redis message dumping currently works.
=> Fix debug cassandra message dump

docs/src/transforms.md, shotover-proxy/src/transforms/mod.rs, shotover-proxy/tests/cassandra_int_tests/mod.rs
Makes CassandraSinkCluster accessible in the public API
=> Move CassandraSinkCluster into beta status

shotover-proxy/src/transforms/cassandra/connection.rs
tx_process and rx_process are run as tasks and we dont await on the results so the errors are just silently ignored. 
:no_mouth: 
Possibly we should be giving a more useful error for end users, "tx_process failed" feels very "implementation detail"y, but definitely an improvement over nothing.
=> Log cassandra connection errors

shotover-proxy/src/codec/cassandra.rs
This wasnt a problem before cassandra-protocol added support for v5, but now that Version::try_from will successfully parse v5 our `CheckEnvelopeSizeError::UnsupportedVersion` path is no longer taken and we end up negotiating with the client to use v5 even though shotover doesnt support v5 yet.
The fix is to reject protocols that cassandra-protocol supports but shotover does not support.
=> CassandraCodec: fix protocol negotiation with clients that support protocol v5

shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs, shotover-proxy/src/transforms/cassandra/sink_cluster/node.rs, shotover-proxy/src/transforms/cassandra/sink_cluster/topology.rs, shotover-proxy/tests/cassandra_int_tests/cluster_multi_rack.rs, shotover-proxy/tests/cassandra_int_tests/cluster_single_rack_v4.rs
=> use socket addr for nodes

docs/src/examples/cassandra-cluster-shotover-sidecar.md, shotover-proxy/example-configs-docker/cassandra-peers-rewrite/docker-compose.yml, shotover-proxy/example-configs/cassandra-cluster-multi-rack/docker-compose.yml, shotover-proxy/example-configs/cassandra-passthrough/docker-compose.yml, shotover-proxy/example-configs/cassandra-protect-aws/docker-compose.yml, shotover-proxy/example-configs/cassandra-protect-local/docker-compose.yml, shotover-proxy/example-configs/cassandra-redis-cache/docker-compose.yml, shotover-proxy/example-configs/cassandra-request-throttling/docker-compose.yml, shotover-proxy/example-configs/cassandra-tls/docker-compose.yml, shotover-proxy/tests/cassandra_int_tests/cluster_multi_rack.rs, shotover-proxy/tests/test-configs/cassandra-passthrough-parse-request/docker-compose.yml, shotover-proxy/tests/test-configs/cassandra-passthrough-parse-response/docker-compose.yml, shotover-proxy/tests/test-configs/cassandra-peers-rewrite/docker-compose-4.0-cassandra.yaml
Update all cassandra 3 integration tests to cassandra 4 (unless we are testing our handling of something cassandra 3 specific)
=> Upgrade remaining cassandra int tests to cassandra 4.0.6

shotover-proxy/example-configs/cassandra-cluster-multi-rack/docker-compose.yml, shotover-proxy/example-configs/cassandra-cluster-tls/docker-compose.yml, shotover-proxy/example-configs/cassandra-cluster/docker-compose-cassandra-v3.yml, shotover-proxy/example-configs/cassandra-cluster/docker-compose-cassandra-v4.yml, shotover-proxy/example-configs/redis-cluster-dr/docker-compose.yml, shotover-proxy/example-configs/redis-cluster-handling/docker-compose.yml, shotover-proxy/example-configs/redis-cluster-hiding/docker-compose.yml, shotover-proxy/example-configs/redis-cluster-tls/docker-compose-with-key.yml, shotover-proxy/example-configs/redis-cluster-tls/docker-compose.yml, shotover-proxy/example-configs/redis-multi/docker-compose.yml, shotover-proxy/tests/test-configs/cassandra-peers-rewrite/docker-compose-3.11-cassandra.yaml, shotover-proxy/tests/test-configs/cassandra-peers-rewrite/docker-compose-4.0-cassandra.yaml, shotover-proxy/tests/test-configs/redis-cluster-auth/docker-compose.yml, shotover-proxy/tests/test-configs/redis-cluster-ports-rewrite/docker-compose.yml
=> use docker anchors

shotover-proxy/benches/benches/cassandra.rs, shotover-proxy/tests/cassandra_int_tests/mod.rs, shotover-proxy/tests/helpers/cassandra.rs, shotover-proxy/tests/helpers/mod.rs
prereq to https://github.com/shotover/shotover-proxy/pull/741
When we originally wrote the ShotoverManager abstraction the idea was to have it create connections so that we could one day make it guarantee that you were connecting directly to shotover. (by reading the topology.yaml or something)
But we never implemented that and then soon realized that we often wanted to create connections directly against the database bypassing shotover, and such an abstraction would have prevented that.
So considering we will never get that benefit this PR removes the ShotoverManager bit in the middle and just directly creates a CassandraConnection via `new` or `new_tls`.
This also fixes an intermittent failure due to some benchmark init logic manually creating their own connections without …
=> Cassandra_int_test refactor connection creation

shotover-proxy/src/transforms/cassandra/sink_cluster/node.rs, shotover-proxy/src/transforms/cassandra/sink_cluster/topology.rs, shotover-proxy/tests/cassandra_int_tests/cluster_multi_rack.rs, shotover-proxy/tests/cassandra_int_tests/cluster_single_rack_v3.rs, shotover-proxy/tests/cassandra_int_tests/cluster_single_rack_v4.rs
=> store tokens as murmur3 instead of string

shotover-proxy/src/codec/cassandra.rs, shotover-proxy/src/frame/cassandra.rs
Will allow us to remove the magic bytes from https://github.com/shotover/shotover-proxy/pull/812
=> Parse cassandra register messages

shotover-proxy/src/transforms/cassandra/sink_cluster/node.rs, shotover-proxy/src/transforms/cassandra/sink_cluster/topology.rs
I need the nodes to have a unique id for token aware routing and using the socket address is probably going to end up badly so I've added this field.
=> add host_id field to CassandraNode

shotover-proxy/src/transforms/util/cluster_connection_pool.rs
They are messages coming from the server so they are responses not requests.
=> Fix misnamed redis variables

shotover-proxy/src/transforms/cassandra/sink_cluster/node.rs, shotover-proxy/src/transforms/cassandra/sink_cluster/topology.rs
=> CassandraNode new method

Cargo.lock, shotover-proxy/Cargo.toml
+ the other deps that become outdated since we last updated everything
=> update cql3 parser

shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs, shotover-proxy/src/transforms/cassandra/sink_cluster/node_pool.rs
Better integrates the separately developed abstractions of https://github.com/shotover/shotover-proxy/pull/831 and https://github.com/shotover/shotover-proxy/pull/824
=> CassandraSinkCluster: Disallow inserting/removing the nodes list from outside of NodePool

shotover-proxy/src/transforms/cassandra/sink_cluster/topology.rs
This PR cleanly shutsdown the topology task once all the receivers have been dropped.
At least one receiver is always held onto for the lifetime of shotover because the original chain from which all chains are cloned from holds one within its CassandraSinkCluster.
But once shotover starts shutting down that final receiver is dropped and this task will shutdown by detecting that all receivers are closed.
The lack of this handling was causing a lot of error logs in our integration tests due to the task outliving the entirety of shotover, but those are all gone now.
=> CassandraSinkCluster: cleanly shutdown topology task

.github/workflows/build.yml
Somehow this slipped through in https://github.com/shotover/shotover-proxy/pull/839
=> Fix Ubuntu 22.04 builds

shotover-proxy/tests/cassandra_int_tests/collections.rs
This greatly reduces test runtime:
* Cuts 4s off test_passthrough (9s -> 5s)
* Cuts 54s off test_cluster_single_rack_v4 (108s -> 54s)
The wins are much larger on cluster tests because we have to wait for schema agreement after every DDL command on cluster tests.
Every test case from the old implementation is carried over into the new implementation just grouped together into the same tables.
The number of tables is now well below 150, so we no longer see any of these warnings anymore:
```
1665977080.901 [WARN] (decoder.cpp:134:bool datastax::internal::core::Decoder::decode_warnings(datastax::internal::core::WarningVec&)): Server-side warning: Cluster already contains 259 tables in 10 keyspaces. Having a large number of tables will significantly slow down schema dependent cluster …
```
=> cassandra_int_tests: reduce total table count

shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs, shotover-proxy/tests/cassandra_int_tests/cluster_single_rack_v4.rs
We already cleared the node pool of dead connections but we forgot to recreate the control connection when it goes down
The insert statements were moved outside of test_connection_handles_node_down to avoid running them twice.
=> existing connections handle down node

shotover-proxy/src/tls.rs, shotover-proxy/src/transforms/mod.rs
Got an out of context ssl error earlier that these log improvements will help with
=> Add more context to error logs

shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs, shotover-proxy/src/transforms/cassandra/sink_cluster/node_pool.rs, shotover-proxy/src/transforms/cassandra/sink_cluster/test_router.rs
These tests weren't running because the module wasn't imported.
=> fix router tests

shotover-proxy/tests/codec/util/packet_capture.rs, shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
Observed by changing the rust version to the beta release.
=> Fix new lints in upcoming release

shotover-proxy/example-configs/cassandra-cluster-tls/topology.yaml
This doesnt correspond to any field in the config struct, I guess our yaml parser just ignores unexpected fields.
=> Remove invalid line from int test config

shotover-proxy/src/transforms/cassandra/connection.rs
Cassandra messages returned to the client previously looked like:
`Internal shotover error: Broken pipe (os error 32)`
Now they look like:
`Internal shotover error: Connection to destination cassandra node 172.16.1.3:9044 was closed: Broken pipe (os error 32)")`
This comes at the cost of 2 extra allocations per cassandra connection but I think the improved error messages are worth it.
Also cleaned up a stray tracing::error that was accidentally left in a previous PR.
=> Include destination in cassandra connection errors

Cargo.lock, shotover-proxy/Cargo.toml, shotover-proxy/src/transforms/cassandra/sink_cluster/routing_key.rs, shotover-proxy/tests/cassandra_int_tests/cluster/single_rack_v4.rs, shotover-proxy/tests/cassandra_int_tests/mod.rs, shotover-proxy/tests/cassandra_int_tests/routing.rs, shotover-proxy/tests/helpers/cassandra.rs
- Add routing tests for compound and composite primary keys.
- Fix a bug in the routing key serialising
- Add tests against cdrs-tokio aswell
=> More routing tests and bug fix

shotover-proxy/tests/cassandra_int_tests/prepared_statements_simple.rs
What the comments describe is being tested wasnt actually being tested.
It seems not enough scrutiny was applied here as it was checked in commented out and then later uncommented.
=> cassandra_int_tests: fix prepared_statements_simple::use_statement

Cargo.lock, shotover-proxy/Cargo.toml
Lets land all the open bug fixes before merging this.
=> Release shotover 0.1.8

shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs, shotover-proxy/src/transforms/mod.rs
Refactor CassandraSinkCluster to use the new builder abstraction.
Also includes the fix from: https://github.com/shotover/shotover-proxy/pull/973
=> Add CassandraSinkClusterBuilder

shotover-proxy/tests/cassandra_int_tests/mod.rs
and now cassandra.
A few test cases are still left as is, I'll have to figure out how to port them from ShotoverManager later on.
=> cassandra_int_tests: replace ShotoverManager with ShotoverProcess

shotover-proxy/src/runner.rs
In most use cases shotover will be running in its own virtual machine or docker so we should use all cores available by default, the user can still specify `--core-threads 4` or whatever other value they desire if they need it.
=> Create one tokio worker thread per core (previously only 4)

shotover-proxy/src/codec/cassandra.rs, shotover-proxy/src/frame/cassandra.rs, shotover-proxy/tests/cassandra_int_tests/cluster/mod.rs
Parsing Cassandra startup messages
=> startup body support

shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs, shotover-proxy/tests/transforms/query_type_filter.rs, shotover-proxy/tests/transforms/tee.rs, test-helpers/src/bench.rs
=> ShotoverManager -> ShotoverProcess in transform int tests

shotover-proxy/src/transforms/cassandra/sink_single.rs, shotover-proxy/src/transforms/mod.rs, shotover-proxy/src/transforms/redis/sink_single.rs, shotover-proxy/src/transforms/tee.rs
Progress towards https://github.com/shotover/shotover-proxy/issues/951
=> Remove remaining custom transform clone impls

README.md, docs/src/contributing.md
Fixes some broken links to the website and updates the cassandra CPP driver installation instructions to use the method that we use these days.
=> contributing.md fixes

shotover-proxy/src/lib.rs, shotover-proxy/src/sources/cassandra.rs, shotover-proxy/src/sources/kafka.rs, shotover-proxy/src/sources/redis.rs, shotover-proxy/src/transforms/cassandra/sink_cluster/mod.rs, shotover-proxy/src/transforms/mod.rs, shotover-proxy/src/transforms/throttling.rs, test-helpers/src/connection/cassandra.rs, test-helpers/src/lib.rs, tokio-bin-process/src/lib.rs
Went through all our clippy allows, at some point we didn't need these ones anymore.
=> remove unneeded clippy allows

shotover/src/frame/kafka.rs, shotover/src/transforms/kafka/sink_single.rs
Adds rewriting for every message in https://kafka.apache.org/protocol.html that has a field named `port`.
This completes the rewriting that was started in https://github.com/shotover/shotover-proxy/pull/1057 and you can refer to that PR for more info on the network topology this is facilitating
Before this PR the client swapped back to a direct connection before a `Fetch` message occurred.
But with this PR we can now observe Fetch messages flowing through shotover.
=> More kafka port rewriting

shotover-proxy/tests/cassandra_int_tests/batch_statements.rs
pulling out a change from #1141
=> organise batch tests into functions

windsock/src/tables.rs
in response to: https://github.com/shotover/shotover-proxy/pull/1165#issuecomment-1545266596
before:
after:
@conorbros thoughts?
=> windsock: Tweak table format

shotover/src/server.rs
* terminate_tx/terminate_rx is removed, instead we just directly check if in_tx has been closed. This is equivalent as they are dropped at about the same time but is also semantically more accurate. Also updated the `Shutdown flows` comment to take this into account.
* we no longer warn on failure to send over in_tx. This fixes an erroneous warning when shotover shutsdown while clients are connected to it.
* `ErrorKind::BrokenPipe` checks have been extended to `ErrorKind::BrokenPipe | ErrorKind::ConnectionReset` as they [occur in equivalent scenarios](https://stackoverflow.com/questions/4652208/what-is-the-difference-between-java-net-socketexception-connection-reset-and-ja). This started being hit after fixing the previous bullet point.
=> server.rs read/write tasks fixes

shotover/src/transforms/cassandra/sink_cluster/mod.rs
Previously we only checked if "all nodes are down", but possibly we have nodes from other racks that we will refuse to connect to from within get_random_owned_connection_in_dc_rack.
So we need to restrict the check to be if "all nodes from our rack are down"
I swapped the if and else bodies to make the conditional expression easier to express.
=> CassandraSinkCluster: Fix initial control connection node pool check

Cargo.lock, custom-transforms-example/tests/test.rs, shotover-proxy/Cargo.toml, shotover-proxy/examples/windsock/cassandra.rs, shotover-proxy/examples/windsock/kafka.rs, shotover-proxy/examples/windsock/redis.rs, shotover-proxy/tests/runner/runner_int_tests.rs, shotover/Cargo.toml, test-helpers/Cargo.toml, test-helpers/src/shotover_process.rs
Update to tokio-bin-process 0.2
Also updates some other dependencies that didnt require any changes.
=> Update tokio-bin-process to 0.2

shotover/src/server.rs
=> server.rs comment formatting

shotover/src/transforms/kafka/sink_cluster.rs
It is valid for brokers to do this, and previously we would error out and drop the connection if shotover encountered this.
=> KafkaSinkCluster handle brokers that advertise via a hostname

shotover/src/transforms/kafka/sink_cluster.rs
In this PR:
* Moved an import
* Fixed the "KafkaSinkCluster" name string
* Moved response processing into its own method. No changes to the logic at all just moved to a new method.
+ I kept confusing myself because request processing was within a submethod but response processing was not. This change should put an end to that.
=> KafkaSinkCluster: Move response processing into method

Cargo.lock, shotover-proxy/Cargo.toml, shotover-proxy/tests/lib.rs, shotover-proxy/tests/opensearch_int_tests/mod.rs, shotover-proxy/tests/test-configs/opensearch-passthrough/docker-compose.yaml, test-helpers/src/docker_compose.rs, test-helpers/src/lib.rs
Just opensearch client -> cluster for now.
=> opensearch int tests

.config/nextest.toml, .github/workflows/build_and_test.yaml, test-helpers/src/shotover_process.rs
nextest provides very powerful [test sharding capabilities](https://nexte.st/book/partitioning)
This PR uses those capabilities to distribute our tests across 8 different GA job instances.
This gives us a time to build and run tests of 35m without a cache.
Previously this was ~1h 15m without a cache and 50m with a cache.
Once this is merged and we can make use of the cache we should be able to expect times of 25m
This is clear win, lets land this.
Currently windsock is bottlenecking our CI, taking 1 hour to complete.
I have plans to expose windsock benches as tests so that they can also take advantage of this sharding, but that will have to be a follow up PR.
In another (optional) follow up PR we can swap to using nextest locally as it has a better UX than `cargo test`.
I had to configure …
=> Use nextest in CI to partition test runs

shotover-proxy/build.rs, windsock/build.rs
Same as https://github.com/shotover/docker-compose-runner/pull/6
=> remove rerun-if-env-changed

shotover/src/transforms/tee.rs
Previously we were ignoring any validation errors occurring in the main chain.
The mismatch chain was validating fine however.
I believe this mistake occurred because the old implementation of Tee at the time transform validation was introduced was really confusing.
Since then things have been cleaned up and its really easily to see the problem is that we are performing validation on the mismatch chain instead of the tee chain.
This PR fixes the issue by introducing validation on the tee chain.
I added new unit tests to ensure the fix works.
I also refactored existing tests so that we compare an entire formatted string instead of a vec of strings, this makes it easier to visually confirm that the validation error looks as we expect.
=> Tee: fix validation

shotover/src/transforms/kafka/sink_cluster.rs
closes https://github.com/shotover/shotover-proxy/issues/1285
I've identified a bug which I believe to be the cause of the intermittent failures.
When we process the results of FindCoordinator there is no guarantee that any given shotover instance has already processed a metadata message with the node of the same broker id in the FindCoordinator.
This means we know which broker id to send to but just dont the know the actual ip address that node id corresponds to, resulting in an inability to route to it.
However FindCoordinator very handily contains the node information we need, we just never made use of it.
So in this PR I have changed our FindCoordinator handling to also introduce new nodes to our node list.
This should ensure that when handling messages like JoinGroup shotover will …
=> kafka_int_tests::cluster_multi_shotover: fix intermittent failure

shotover-proxy/benches/windsock/aws/mod.rs
This allows us to run windsock aws on aarch64.
I also noticed that `docker logs` will sometimes output errors to stderr, so I redirected stderr to stdout via `2>&1`
=> windsock aws: choose aarch64 instances if compiled for aarch64

.github/workflows/build_and_test.yaml, .github/workflows/windsock_benches.yaml
I copied this line from the documentation, but the documentation was wrong :cry: 
Refer to https://github.com/Swatinem/rust-cache/issues/165 for more details.
=> Fix CI caching

ec2-cargo/src/main.rs
Adds a windsock command to ec2-cargo that runs windsock and then downloads results to the `target/windsock_data` folder.
Does not support windsocks cloud functionality yet, that will come in a follow up PR.
But it does allow running local benches within the ec2-cargo instance.
=> Add windsock support to ec2 cargo

windsock-cloud-docker/src/main.rs
Once it was checked in and I could use it I discovered a few bugs:
* We need to do `rm -rf` to handle the case where the directory doesnt exist
* We need to copy results to the host so that we can access the bench results from there.
=> windsock docker fixes

Cargo.lock, shotover/src/transforms/kafka/sink_cluster.rs, test-helpers/Cargo.toml
We previously had to use git here due to a bug in the driver, now the new version has been released we can go back to proper versioning.
=> Move rdkafka back to crates.io

shotover/src/config/topology.rs, shotover/src/sources/cassandra.rs, shotover/src/sources/kafka.rs, shotover/src/sources/mod.rs, shotover/src/sources/opensearch.rs, shotover/src/sources/redis.rs
Not sure why these ever returned a Vec but all instances return a single item so lets remove the vec.
=> source configs return a single source instead of vec

shotover-proxy/benches/windsock/redis.rs
Since https://github.com/shotover/shotover-proxy/pull/1333 landed we can now startup redis and shotover concurrently.
Lets make use of that to improve bench startup times a little.
I dont expect huge gains here, probably just a second or less per bench.
=> windsock: redis cloud benches startup redis + shotover concurrently

shotover-proxy/benches/windsock/aws/mod.rs
I encountered a rare and subtle race condition that caused a windsock bench to fail.
We have a sanity check that ensures that all `Ec2InstanceWithShotover` arc clones are dropped before issuing a new one: https://github.com/shotover/shotover-proxy/blob/d9a609124851c435efbb134b79055960c1b4a785/shotover-proxy/benches/windsock/aws/mod.rs#L120
This was being accidentally triggered because we did not wait for a background task that had access to such a clone to terminate before ending the bench and proceeding onto the next bench when will request a new `Ec2InstanceWithShotover`
The fix is to tweak our communication with that task to ensure that we wait for the task to end (achieved by `while let Some(event) = self.event_rx.recv().await` which will keep running until the task has terminated.
=> windsock: fix rare cloud shotover shutdown race condition

shotover-proxy/tests/cassandra_int_tests/protect.rs
Added a few more tests and cleaned up the file
=> Protect tests

docs/src/sources.md
Adds the missing chain fields and documents default values of connection_limit + hard_connection_limit
=> docs source fixes

shotover/benches/benches/chain.rs
I altered the bench method to return the Vec<Message> instead of dropping it.
This means that the time taken to drop the vec of messages wont be included in the benchmark results.
I added a loopback benchmark to demonstrate the fastest possible case, it is about 2x as fast as the NullSink.
=> add loopback microbenchmark

rust-toolchain.toml, shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs, shotover/src/frame/redis.rs, shotover/src/transforms/distributed/tuneable_consistency_scatter.rs, shotover/src/transforms/query_counter.rs, shotover/src/transforms/redis/sink_cluster.rs, shotover/src/transforms/redis/timestamp_tagging.rs, windsock/src/tables.rs
I dont feel strongly either way about disabling or keeping the get_first lint https://rust-lang.github.io/rust-clippy/master/index.html#/get_first
=> Update to rust 1.75 🦀🦀🦀

shotover/src/transforms/cassandra/sink_cluster/rewrite.rs
I observed a very strange rare intermittent CI failure:
I have no idea what could cause this so I just added better error reporting so that if it occurs again we have a better chance of diagnosing whats going on.
=> Improve parse_system_nodes error reporting

shotover-proxy/tests/transforms/tee.rs, shotover/src/frame/mod.rs
the stray bracket makes it harder for a human to parse the frame display.
=> Fix stray bracket in frame display

shotover/src/server.rs
Makes the logic easier to follow by seperating the two seperate forward/backward paths instead of having them intertwined with a boolean.
=> refactor Handler::process_messages

ec2-cargo/src/main.rs
Fixes running `windsock --cloud` within ec2-cargo.
This provides an alternative to `windsock-cloud-docker` with different trade offs.
We have to compile shotover+windsock entirely on EC2 but we get faster communication with EC2 and can be run on a system without docker.
This PR also enables ec2-cargo to use the faster to compile windsock aliases introduced in https://github.com/shotover/shotover-proxy/pull/1441
=> Fix ec2-cargo windsock cloud

shotover/src/transforms/cassandra/sink_cluster/mod.rs, shotover/src/transforms/cassandra/sink_cluster/node_pool.rs, shotover/src/transforms/cassandra/sink_cluster/rewrite.rs, shotover/src/transforms/cassandra/sink_cluster/test_router.rs, shotover/src/transforms/distributed/tuneable_consistency_scatter.rs, shotover/src/transforms/protect/key_management.rs, shotover/src/transforms/protect/local_kek.rs
=> remove unused async

shotover-proxy/tests/kafka_int_tests/test_cases.rs
Huh, I dont seem to be able to reproduce the issue this test was reproducing any more.
Not sure what changed over the past month, but I've confirmed its not an intermittent problem by rerunning the test many times.
So I guess lets just land this.
I also ended up pulling out the produce/consume assertions into helper methods: `assert_produce` and `assert_consume`
=> kafka: add test for multi-partition topics

shotover/src/frame/kafka.rs
Parsing SASL messages in kafka/frame.rs
=> Kafka SASL messages

test-helpers/src/connection/kafka/java.rs
Brings the java driver a step closer to the cpp driver by implementing setup of partitions.
I also noticed that I wasnt actually waiting on the future returned by createTopics so I added that via the:
```rust
jvm.chain(admin_client)
.unwrap()
.invoke("createTopics", &[topics.into()])
.unwrap()
.invoke("all", &[])
.unwrap()
.invoke("get", &[])
.unwrap()
.collect();
```
After fixing that SASL tests started failing since I wasnt setting up SASL correctly.
So this PR also sets up SASL for the java driver.
Its similar to the cpp setup but needs different magic incantations.
=> kafka_int_tests: java driver setup partitions

shotover-proxy/tests/kafka_int_tests/test_cases.rs, test-helpers/src/connection/kafka/cpp.rs, test-helpers/src/connection/kafka/java.rs, test-helpers/src/connection/kafka/mod.rs
With this PR the java driver abstractions needed for admin setup are now at feature parity with the cpp driver.
=> Finish java driver setup functionality

shotover/src/transforms/cassandra/peers_rewrite.rs
I thought https://github.com/shotover/shotover-proxy/pull/1516 was the last one, but I've discovered one more.
=> CassandraPeersRewrite: port to MessageId invariants

shotover/src/server.rs
This flushing logic is meaningless as it is impossible to reach.
`tokio::mpsc::Receiver::try_recv` will never return any values after `tokio::mpsc::Receiver::recv`  returns None.
I have no idea what I was thinking when I wrote this in https://github.com/shotover/shotover-proxy/pull/707 :sweat_smile:
=> Remove dead code from server.rs

shotover/src/transforms/kafka/sink_cluster/mod.rs
Pulls logic from `route_requests` into two new functions named `route_produce_request` and `route_fetch_request`.
The logic remains exactly the same.
=> KafkaSinkCluster minor refactor

shotover/src/connection.rs
Pulled out of https://github.com/shotover/shotover-proxy/pull/1553
Sink transforms rely on SinkConnection to call `force_run_chain.notify_one()`  to trigger a new chain run to avoid responses getting stuck in the SinkConnection until the client sends another request.
However this approach currently has a race condition allowing messages to get stuck.
Consider this scenario:
1. SinkConnection read_task: `in_tx.send(messsages)`
2. SinkConnection read_task: `force_run_chain.notify_one()`
3. SinkConnection read_task: `in_tx.send(messsages)`
4. SinkConnection read_task: `force_run_chain.notify_one()` - Has no affect since there is already a notification.
At this point we have 2 message batches pending in the read channel.
4. server.rs in main task: `force_run_chain.notified` triggers causing a …
=> SinkConnection fix hang due to race condition

shotover/src/transforms/cassandra/sink_cluster/node.rs
This is needed by https://github.com/shotover/shotover-proxy/pull/1553
It is also possibly slightly faster to execute `get_version` now.
=> CassandraSinkCluster ConnectionFactory make version accessible without mutability

test-helpers/src/connection/cassandra.rs
=> timeout const in Cassandra test helpers

shotover/src/transforms/kafka/sink_cluster/mod.rs, shotover/src/transforms/kafka/sink_cluster/node.rs, shotover/src/transforms/kafka/sink_cluster/scram_over_mtls.rs
I had previously missed that kafka-protocol provides a [ResponseError](https://docs.rs/kafka-protocol/latest/kafka_protocol/error/enum.ResponseError.html) type for parsing kafka error codes.
This type is super useful, turning the numeric error codes into a meaningful error enum.
So this PR:
* Uses `ResponseError` to parse error codes into meaningful error names before including in shotover errors.
* Uses `ResponseError` to avoid writing error codes as magic numbers
* Adds error handling for delegation token creation responses which was previously entirely missing (in scram_over_mtls.rs)
Some notes on rust features for newstarters reviewing this PR.
rust has a core type in the standard library called Option.
It is an enum defined as:
```rust
enum Option<T> {
Some(T),
None
}
```
It is …
=> Improve KafkaSinkCluster server error handling

shotover/src/transforms/kafka/sink_cluster/mod.rs
Included comments describe the change pretty well.
=> KafkaSinkCluster - Fix race condition in add_node_if_new

shotover/src/connection.rs
This PR fixes a race condition I discovered via an intermittent CI failure.
```
Unexpected event 08:35:15.868972Z PANIC panicked at shotover/src/connection.rs:90:64:
called `Result::unwrap()` on an `Err` value: Empty
0: rust_begin_unwind
at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:652:5
1: core::panicking::panic_fmt
at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:72:14
2: core::result::unwrap_failed
at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/result.rs:1679:5
3: core::result::Result<T,E>::unwrap
at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/result.rs:1102:23
shotover::connection::SinkConnection::set_get_error
at /home/runner/work/shotover-proxy/shotover-proxy/shotover/src/conn …
```
=> Fix SinkConnection race condition

shotover/src/transforms/kafka/sink_cluster/mod.rs
This was very useful for tracking the cause of outgoing connection closed issues.
Before:
After:
=> KafkaSinkCluster - add context to anyhow errors

shotover/src/transforms/kafka/sink_cluster/connections.rs
This should probably have been done in https://github.com/shotover/shotover-proxy/pull/1715
While we already set the node state to down, we currently have no logic for setting it back to up.
If a connection can be made to the node then we should consider it back up.
Since this is the opposite logic of "connection fail" -> "set node as down" it makes sense to handle these in the same place, which is what this PR does.
=> KafkaSinkCluster handle_connection_error also set Up on success

shotover/src/transforms/kafka/sink_cluster/mod.rs
As per the documentation:
https://docs.rs/kafka-protocol/latest/kafka_protocol/messages/offset_fetch_request/struct.OffsetFetchRequest.html
The `group_id` field on `OffsetFetchRequest` is only valid for API versions 0-7.
However in the logic for determining group ids that require a metadata query (specifically `FindCoordinator`),
we currently use this field regardless of the requests API version.
As a result if a client sends a request of version 8 or 9 shotover may not have the required metadata to route this request.
This is causing a particular problem in https://github.com/shotover/shotover-proxy/pull/1734 where outdated metadata is not updated, causing shotover to continue routing to the down node.
This PR fixes our handling for API version 8-9 by adding specific handling for version …
=> Fix determining the coordinator for OffsetFetch requests

shotover/src/transforms/kafka/sink_cluster/mod.rs
This PR:
* debug logs the routing destination of each request, this should enable us to track investigate routing issues in test systems.
* debug logs writing to routing metadata
* Changes all user facing logs/errors to refer to kafka nodes as brokers, this helps make it extra clear that we are talking about kafka nodes and not shotover nodes.
* rewrites `format_topic_name` method into a `Debug` implementing struct `FormatTopicName`
+ This avoids the allocation previously needed due to returning a String
+ I wasnt sure if calling format_topic_name in a debug! log would call the method when the log isnt run, so I just removed the allocation from format_topic_name to make it faster in all cases.
Each request type is handled differently so we can provide meaningful context to each routing …
=> Add routing debug logs

shotover/src/transforms/kafka/sink_cluster/mod.rs
This PR adds extra context to our errors to make it clear that we were sending a request, and in the case of metadata requests what kind of metadata we were querying.
`group.0.clone()` is not a performance concern since `group.0` is reference counted.
=> KafkaSinkCluster improve send error messages

shotover/src/transforms/kafka/sink_cluster/mod.rs
This PR is an extension of the rewrite `fetch.max.wait.ms`/`fetch.min.bytes` solution to the consumer latency issue.
In addition to rewriting those fields on the fetch requests to 1, this PR also implements shotover side handling of the original values of those fields as sent by the client.
So for example client sends fetch request with:
* `fetch.max.wait.ms=500`
* `fetch.min.bytes=100`
Shotover will rewrite both of those fields to 1 before sending the split requests to the kafka brokers.
However shotover will store the 500 and 100 values and abide by them in its communication with the client.
The logic shotover uses to achieve this looks like:
1. send all split requests to their destination with configs rewritten to 1
2. wait for all responses to come back
* assuming a healthy cluster …
=> KafkaSinkCluster: fix consumer latency issues

shotover/src/transforms/kafka/sink_cluster/mod.rs
Currently, every request that is routed to a group coordinator results in an entry being left in `route_to_coordinator_for_group`.
We were correctly cleaning up those entries when the broker responded to those requests with an error.
But when it succeeded we were leaving that entry there.
When the connection between client <-> shotover is eventually closed that memory will be reclaimed. But a client could easily never close its connections, making this into a real memory leak concern.
There was a TODO that warned of this possibility:
```
// TODO: this approach with `find_coordinator_requests` and `routed_to_coordinator_for_group`
//       is prone to memory leaks and logic errors.
//       We should replace these fields with extra state within `PendingRequestState::Received/Sent`.
```
So …
=> KafkaSinkCluster fix memory leak when routing to group coordinator

shotover-proxy/tests/kafka_int_tests/mod.rs, shotover/src/transforms/kafka/sink_cluster/mod.rs
Since this is an expected case of normal kafka usage, we shouldnt actually warn here, instead an info level log will be sufficient.
=> Downgrade routing warn to info

shotover/benches/benches/codec/cassandra.rs
To stop [this noisy bench](https://github.com/shotover/shotover-proxy/pull/1774#issuecomment-2413030451) from showing up as a failure I propose we comment it out. See comment in the code changes for more info.
=> Disable local_result_v5_no_compression benchmark for being noisy

rust-toolchain.toml
https://blog.rust-lang.org/2024/10/17/Rust-1.82.0.html
=> Update to rust 1.82 🦀🦀🦀

shotover-proxy/tests/redis_int_tests/basic_driver_tests.rs
intermittent CI failures have gotten a bit out of hand lately.
This PR addresses the most frequent failure, which is why I'm suddenly touching redis instead of kafka.
The last time I looked into this I ended up quite confused, but that was 2 years ago and the solution was a lot easier to find this time around.
This PR extends the fix in https://github.com/shotover/shotover-proxy/pull/745 with two extra changes:
We run `CLUSTER NODES` to fetch a master node in `get_master_id`.
While redis is starting up `CLUSTER NODES` can return bizarre results where replicas are reported as masters.
The results include more masters than slaves, which is impossible because the cluster is configured with 3 masters and 3 slaves. After a while this resolves itself. 
Here is an example of such an output from …
=> redis_int_tests: Fix intermittent CI failure

shotover/src/transforms/kafka/sink_cluster/mod.rs
Refer to the comments in the implementation for the reasoning.
=> KafkaSinkCluster: error on LeaderAndIsr, StopReplica and UpdateMetadata

shotover-proxy/tests/valkey_int_tests/basic_driver_tests.rs, shotover/src/codec/valkey.rs
closes https://github.com/shotover/shotover-proxy/issues/1884
* https://valkey.io/topics/pubsub/
* https://valkey.io/commands/subscribe/
* https://valkey.io/commands/psubscribe/
* https://valkey.io/commands/unsubscribe/
* https://valkey.io/commands/punsubscribe/
* The comments in the modified `codec/valkey.rs` file
* To better understand how ValkeyEncoder and ValkeyDecoder fit into shotover, consider reading through the [end-to-end overview](https://shotovertest.rukai.xyz/docs/main/dev-docs/end-to-end-overview.html)
The problem is that the unexpected extra responses to subscribe/unsubscribe requests puts the sink decoder out of sync with the request info coming in from the sink encoder.
The approach I ended up taking to resolve this was to setup a system for skipping regular message …
=> Fix valkey pubsub hang

Cargo.lock, Cargo.toml, shotover-proxy/benches/windsock/cassandra/bench.rs, shotover-proxy/tests/cassandra_int_tests/mod.rs, test-helpers/src/connection/cassandra/connection.rs, test-helpers/src/connection/cassandra/connection/scylla.rs, test-helpers/src/connection/cassandra/result_value.rs, test-helpers/src/mock_cassandra.rs
Upgrade the Scylla crate to version 1.0.0
The details of the changes have been mentioned here https://github.com/scylladb/scylla-rust-driver/releases/tag/v1.0.0
=> Upgrade scylla crate to version 1.0.0

rust-toolchain.toml, shotover/src/codec/cassandra.rs, shotover/src/codec/kafka.rs, shotover/src/codec/opensearch.rs, shotover/src/frame/mod.rs, shotover/src/message/mod.rs, shotover/src/transforms/cassandra/sink_cluster/rewrite.rs, shotover/src/transforms/debug/returner.rs, shotover/src/transforms/kafka/sink_cluster/mod.rs
Cleared all warnings after the update 1.87.
=> rust 1.87 CI fix
